### ISSUE TITLE
remove or stop logger1 but logger2 can't work

### ISSUE THREAD

**Issue by jageli** [Delgan/loguru#1017]
logger1 = loguru.logger.bind(module="log1",config=False)
logger1.add("1.log",filter=lambda record: record["extra"]["module"] == "log1")

logger2 = loguru.logger.bind(module="log2",config=False)
logger2.add("2.log",filter=lambda record: record["extra"]["module"] == "log2")

logger1.info("logger1")
logger2.info("logger2")

logger1.remove()

logger2.info("logger222")   # Can't work why?

**Comment by Delgan** [comment]
It's important to understand that there is in fact only one logger. Using `bind()` will update the `extra` dict of subsequent calls, but the handlers are not affected. Therefore, removing handlers from `logger1` will also remove them from `logger2`, because they are effectively the same.

Calling [`logger.remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) without any argument cause all handlers to be removed. You should store and re-use the handler id returned by [`logger.add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) if you want to remove one specific handler.

```python
logger1 = loguru.logger.bind(module="log1",config=False)
handler_id_1 = logger1.add("1.log",filter=lambda record: record["extra"]["module"] == "log1")

logger2 = loguru.logger.bind(module="log2",config=False)
handler_id_2 = logger2.add("2.log",filter=lambda record: record["extra"]["module"] == "log2")

logger1.info("logger1")
logger2.info("logger2")

logger.remove(handler_id_1)

logger2.info("logger222") # Now it works.
```

**Comment by jageli** [comment]
Thank you

**Comment by jageli** [comment]
another question:
i use logger.stop(handler_id_1) to stop  handler_id_1
when i want to reopen handler_id_1, how can i do?
logger.start(handler_id_1) ?  but seems it not work.

**Comment by Delgan** [comment]
You'll need to re-`add()` a new handler with the same initial arguments.

If this is not convenient enough, you can implement a custom `filter` to enable or disable the logs on demand.
