### ISSUE TITLE
Colors not rendering in Apache WSGI logs

### ISSUE THREAD

**Issue by AVRC26** [Delgan/loguru#1026]
I integrated loguru with a django application with this handler.
```python
    dict(
        sink=sys.stderr,
        format="<g>{time:YYYY ddd MMM DD HH:mm:ss.SSSSSSZZ}</g>",
        colorize=True,
        backtrace=False, 
        diagnose=True,  
        catch=True, 
    ),
```
When I try to use django's inbuilt webserver to serve the application, the colors are shown just fine but for production environment, I use Apache WSGI to serve django application, the logs print fine in apache logs, but the colors are shown as codes instead of the actual color.

`\x1b[32m2023 Sun Nov 26 23:44:55.622738+0000\x1b[0m` - Apache Logs

![image](https://github.com/Delgan/loguru/assets/26881421/d65e1db0-01e0-4c3e-81ec-a114891f16d7) - Django Development Server logs

I tested Apache Logs both on gitbash and command prompt

**Comment by Delgan** [comment]
How do you access Apache logs? Are logs stored in a file?

The color codes are only supported by TTY devices. This is the case of most console when writing to `sys.stderr`. However, when pipe redirections are used and writing to a file, the color codes won't be converted and will appear as-is in the output.

Maybe you can use `colorize=None`. Loguru tries to detect whether `sys.stderr` supports colors, and will strip the codes otherwise.

**Comment by AVRC26** [comment]
Yes, the logs are written to apache log files, I am tailing the file to view the logs..
Is there a way to parse the color and colorize while tailing a file?

I tried with `colorize=None` and it will not print the color codes, I want to find a way to see the colors while tailing..

**Comment by Delgan** [comment]
@AVRC26 For some reason, your Apache logs contains color sequences encoded using [backslash `\xhh` escape sequence](https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences). Because of this encoding, tools such as `cat` and `tail` do not detect the colors.

The output of `cat -v file.log` in your case is:

```txt
\x1b[32m2023 Sun Nov 26 23:44:55.622738+0000\x1b[0m
```

For colors to be detected, it should instead be:

```txt
^[[32m2023 Sun Nov 26 23:44:55.622738+0000^[[0m
```

Note the `^[`: this represents an unprintable character which has been encoded as `\x1b` in your file. `^[` and `\x1b` are two alternative representations of [the ASCII escape character](https://en.wikipedia.org/wiki/Escape_character#ASCII_escape_character) (used to indicate colors). However, they are not supposed to be saved like this in the binary version of your file. Internally, it's just a byte whose value in decimal is 27. The `\x1b` is just meant to be used for human-friendly representation (since the character is unprintable by definition).

I can't explain how you ended up with such encoded character in your logs. Using `logger.add("file.log", colorize=True)` produces the expected output. This is a problem with the environment running your application or processing your logs.

As a workaround, you can combine `cat` with `echo -e` to convert the `\xhh` sequences back to their original value:

```bash
echo -e $(cat file.log)
```

**Comment by AVRC26** [comment]
@Delgan Thankyou for the detailed explanation.
`echo -e $(cat file.log)` works for validation purposes, I can not get `tail` and `echo -e` to work  together.
`sink=open("/tmp/file.log", "w")`  works as as expected.

both sys.stderr, sys.stdout sinks are raising this issue..
Could be that [mod_wsgi](https://modwsgi.readthedocs.io/en/master/) is not playing nice with colored stderr/stdout..

**Comment by Delgan** [comment]
Can I go ahead and close this ticket, or do you need additional help?

It seems the issue is not related to Loguru, therefore I'm not sure I can do anything.

**Comment by AVRC26** [comment]
Sure, thankyou.
