### ISSUE TITLE
backtrace=False, but loguru is still showing tracebacks on exceptions

### ISSUE THREAD

**Issue by jonathanhle** [Delgan/loguru#103]
`logger.add("/var/log/protectwise_bootstrap.log", backtrace=False, format="{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}")`

backtrace=False, but loguru is still showing tracebacks on exceptions

![image](https://user-images.githubusercontent.com/3851599/58755723-49d66f80-849e-11e9-8cfb-b62edaef9f23.png)

**Comment by jonathanhle** [comment]
Setting the env variable "export LOGURU_BACKTRACE=NO" seems to quiet the backtraces, but "backtrace=False" doesn't seem to turn them off.  Python 3.6.8

**Comment by Delgan** [comment]
Hi.

I guess you have two configured handlers: the first one logs messages to `sys.stderr` (this is the default handler automatically added), the second one logs messages to `"protectwise_bootstrap.log"` (the handler you manually added).

The `backtrace` properties of handlers are independent of each others. The default handler use `backtrace=True`. So, even if you add a new handler with `logger.add(..., backtrace=False)`, the default one is not modified and will display full traceback.

You can either set `LOGURU_BACKTRACE=NO` for development, or explicitly add a `sys.stderr` handler with `backtrace=False`:

```python
logger.remove()  # Remove default handler (and all others)
logger.add(sys.stderr, backtrace=False)
logger.add("protectwise_bootstrap.log", backtrace=False, format="{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}")
```

Alternatively, using [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure):

```python
# Default handler (and all others) is automatically removed while using '.configure()'
logger.configure(handlers=[
    {"sink": sys.stderr, "backtrace": False},
    {"sink": "protectwise_bootstrap.log", "backtrace": False, "format": "{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}"}
])
```

**Comment by jonathanhle** [comment]
Thanks for your help.  Really really lovely loggly module.

**Comment by DineshkumarElumalai** [comment]
Hi @Delgan 
I'm not able to disable the backtrace even after setting `LOGURU_BACKTRACE` environment variable as False. I've also tried logger.configure() method like this. 

```
logger.configure(handlers=[
    {"sink": sys.stderr, "backtrace": False}
])
```
Still it's printing the traceback. Could you please guide me?

**Comment by Delgan** [comment]
Hi @DineshkumarElumalai.

The `backtrace` attribute it controls the length of the traceback (if enabled, Loguru displays the entire traceback instead of stopping at the try/except frame like the standard exception does).

However, Loguru respects the [`sys.tracebacklimit`](https://docs.python.org/fr/3/library/sys.html#sys.tracebacklimit) value. You can disable traceback by settings it to `0`:

```python
import sys

sys.tracebacklimit = 0
```

If advanced exception formatting configuration is required, you can define your own way of displaying exceptions by using a custom `format` function as explained in the documentation: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).
