### ISSUE TITLE
How does `contextualize` work in an AWS lambda setting?

### ISSUE THREAD

**Issue by sreeprasannar** [Delgan/loguru#1045]
First of all, amazing library!
I've been trying to use it to the fullest, particularly in an AWS lambda setting. My usecase involves something like:
```
def handler(event: dict, context): 
    with logger.contextualize(request_id=request_id):
        results = foo(request_id)
```
But of course the default logger has no `extras`, so I'd have to do something like:
```
def handler(event: dict, context):
    logger.add(sys.stderr, format="{message} | {extra}")
    with logger.contextualize(request_id=request_id):
        results = foo(request_id)
```
For `x` concurrent requests, there are then `x` loggers at the same time? Trying to wrap my head around this, thanks!

**Comment by Delgan** [comment]
Hi @sreeprasannar.

For usual Python application, there is only one global `logger` instance. If you call `logger.add()` multiple times, multiple logging handlers will be attached to the `logger`. This is generally a mistake since it can cause logs to interleave with each others when using multi-threading.

However, my understanding of AWS lambdas is that they are inherently thread-safe. Each lambda invocation is executed in a dedicated container, with each instance running on its own. Therefore, I assume you can safely call `logger.add()` at the beginning of your lambda handler.

The `contextualize()` method serves two main purposes:
- When you wish for subsequent logging calls to automatically adopt a specific context without explicitly passing it to the underlying functions (like `foo()` in your example).
- When multiple functions can be executed concurrently (such as with `threading` or `asyncio`), and each function should maintain its unique logging context without interference from others.

**Comment by sreeprasannar** [comment]
Sounds good, thank you! I haven't tried it yet, but I'll post updates when I do.

**Comment by sreeprasannar** [comment]
@Delgan turns out lambda invocations are not run in dedicated containers. In my tests, every additional execution lead to duplicated logs i.e. `logger.add` was propagated across executions. This would be super dangerous in production. Bummer, it would have made logs super clean.

**Comment by Delgan** [comment]
Thanks for the update. Sorry for the misleading indications, I'm not using AWS lambda myself.

In this case, care must be taken not to configure the logger more than once.
