### ISSUE TITLE
[Question] How do I log full exception traceback when using sys.excepthook for unhandled excpetions

### ISSUE THREAD

**Issue by PyTran** [Delgan/loguru#1067]
I cannot work out how to log uncaught exceptions with the same output as caught exceptions. The below shows the code I used to compare the differences in the exception log. I would appreciate help on working out the correct way to achieve this.

```Python
import sys, traceback
from loguru import logger

def divide(a, b):
    return a/b

def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return

    exception = sys.exc_info()
    logger.opt(exception=exception).exception("Uncaught Exception")

sys.excepthook = handle_exception

print("*************************************************************")
print("***********         Caught Exception            *************")
print("*************************************************************")

try:
    divide(2,0)
except:
    logger.exception("Caught Exception")

print("*************************************************************")
print("**********         Uncaught Exception            ************")
print("*************************************************************")

divide(2,0)

```

**Output**
![image](https://github.com/Delgan/loguru/assets/51318479/3d9819ca-be4d-4adf-8c46-2279fc66d158)

**Comment by Delgan** [comment]
There are essentially two issues with the code you shared.

First, using `.opt(exception=...)` with `.exception()` is tautological and likely a mistake. This is because `logger.exception()` will automatically retrieve the current exception and will therefore suppress the one provided by `opt()`. You can see `logger.exception()` as being roughly equivalent to:

```python
logger.opt(exception=sys.exc_info()).error("Error message")
```

Secondly, Python does not call `sys.excepthook()` within the context of the exception. Therefore, `sys.exc_info()` would return `None`. Instead, you should directly use the `exc_type`, `exc_value` and `exc_traceback` arguments. They contain the uncaught exception:

```python
logger.opt(exception=(exc_type, exc_value, exc_traceback)).error("Uncaught Exception")
```

**Comment by PyTran** [comment]
Thanks very much. That works perfectly. 
Sorry about the error. I did try with `logger.opt(exception=exception).info("Uncaught Exception")` first.


This is the corrected sys.excepthook handler for reference. 
```Python
def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return

    logger.opt(exception=(exc_type, exc_value, exc_traceback)).error("Uncaught Exception")

sys.excepthook = handle_exception
```

**Comment by Delgan** [comment]
Great. I'm closing this ticket since your issue is resolved. :+1:
