### ISSUE TITLE
How does rotation logs work with loguru?

### ISSUE THREAD

**Issue by PyDataBlog** [Delgan/loguru#111]
Hi,

I am about to try loguru and logging for the first time and rotation logs seem like a logical solution for my project. How does it work in general and with loguru?

Here's how I specified the logger:
```py
logger.add(sink=working_dir + '/log_file.log',
 format=logging_format, level='DEBUG', rotation='1 week')

**Comment by Delgan** [comment]
Hi @PyDataBlog.

It basically means that one week after **the file creation datetime**, logging a message will trigger the file rotation process: the current `"log_file.log"` will be closed, renamed to `"log_file.<date>.log"` and a fresh new file will be created to receive the future messages.
This may happen while your application is running continuously since one week, or alternatively if you try to re-run your application one week after the first run.

**Comment by PyDataBlog** [comment]
> Hi @PyDataBlog.
> 
> It basically means that one week after **the file creation datetime**, logging a message will trigger the file rotation process: the current `"log_file.log"` will be closed, renamed to `"log_file.<date>.log"` and a fresh new file will be created to receive the future messages.
> This may happen while your application is running continuously since one week, or alternatively if you try to re-run your application one week after the first run.

So after the expiration of the initial 1 week, a new "`log_file.<date>.log`" file be created every single week?

**Comment by Delgan** [comment]
Correct! The rotation will occur every week, effectively creating a new `"log_file.<date>.log"` each time. :wink:
