### ISSUE TITLE
daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by MrMarvel** [Delgan/loguru#1112]
I have Process Structure:
MAIN PROCESS (MAIN THREAD):
--PROCESS0(CONTROLLER) (daemon)
----PROCESS1 (daemon)
----PROCESS2 (daemon)
------THREAD1 (daemon)
------THREAD2 (daemon)

Loguru 0.7.2
Python 3.12.2
Windows 10

Processes 1 and 2 regularly recreates from process 0.

While I was using logging it perfectly worked (spawning, killing, recreating processes/threads)
When I switched to loguru. Processes starts nice BUT every new spawn process failing during recreating with following error:
`daemonic processes are not allowed to have children`

**Comment by MrMarvel** [comment]
Also problem appears on 3.11.6

**Comment by MrMarvel** [comment]
But it works on 3.10.12

**Comment by Delgan** [comment]
Any chance you could share a minimum reproducible example please?

The "daemonic processes are not allowed to have children" error appears to be reported when starting a new process from a `daemon` one. However, Loguru does not start child process by itself. That's why I'm quite surprised that the problem you're experiencing could be linked to Loguru.

Maybe related: [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument).

**Comment by MrMarvel** [comment]
During following research I realized that problem is not directly caused by loguru (even with default logging problem sometimes appears).
Closing issue.
I was messing up with multiprocessing unstable project architecture.
