### ISSUE TITLE
RecordLevel lack of property “color”

### ISSUE THREAD

**Issue by main1015** [Delgan/loguru#1120]
There are ` color ` properties when defining what ` Level ` is, but `RecordLevel` lacks the ` color ` property when you format the output logs. In the documentation
There is no ` color ` in the “level: The severity used to log the message name (default)”, no, icon. But with the default log output

**Comment by Delgan** [comment]
This is because `color` has been deemed quite pointless within `RecordLevel`, since it cannot be formatted. Colors should be specified using markup tags like `<blue>...</blue>` and `<level>...</level>`. This allows for defining a scheme using various colors, not just the one of current level, which encompasses the common format of your logs. The `record` fields can be formatted with `{level.name}` and `{level.icon}`, but this would not map very naturally if applied to colors.

What exactly is your use case for accessing level color from a `record`?

**Comment by main1015** [comment]
This is my code:
![1712472647152](https://github.com/Delgan/loguru/assets/3272281/63a12a46-919d-410f-b63e-a14a001b6c10)
Below is the output:
![1712472667508](https://github.com/Delgan/loguru/assets/3272281/e57581b2-2c6d-4249-9a18-980e4efe2888)
However, I deleted the own output of loguru and defined the output format by myself, so there is no way to set the output color：
![1712472893143](https://github.com/Delgan/loguru/assets/3272281/e4986876-ced3-4c72-bb13-d9bad6755fe4)

**Comment by Delgan** [comment]
Can you use the special `"<level>...</level>"` [color markup](https://loguru.readthedocs.io/en/stable/api/logger.html#color) in your custom format?

**Comment by main1015** [comment]
@Delgan  
Thank you very much, I want this effect, I haven't read the document carefully before, sorry

**Comment by Delgan** [comment]
No problem, I'm closing this ticket then, since it's resolved. :+1:
