### ISSUE TITLE
Loguru 'success' level with Rich

### ISSUE THREAD

**Issue by teddyrasmussen** [Delgan/loguru#1149]
I am using `loguru` to log errors/info/whatever in a project, but using it with the `RichHandler` for easier formatting. However, the loguru logger has a success mode (`loguru.logger.success`) that Rich doesn't seem to support.

Reproduceable code:
```py
from loguru import logger
from rich.logging import RichHandler

logger.configure(
    handlers=[
        {
            "sink": RichHandler(),
            "format": "{name}:{function}:{line} - {message}",
        }
    ]
)

logger.success("This is a success message")
```

However, `RichHandler` doesn't seem to support this:

<img width="1066" alt="Screenshot 2024-06-10 at 6 20 35 PM" src="https://github.com/Delgan/loguru/assets/63609284/d4c0d487-d2e5-4a05-ad00-445617bf4eae">

Is there any way around this?

**Comment by Delgan** [comment]
Hi.

Since Rich is based on standard `logging` module, and because standard `logging` module does not have a "success" level, you'll need to add it by yourself using [`logging.addLevelName()`](https://docs.python.org/3/library/logging.html#logging.addLevelName) at the beginning of your script:

```python
logging.addLevelName(25, "SUCCESS")
```

Then if you want to customize the color, check out this ticket probably: https://github.com/Textualize/rich/issues/1161

**Comment by teddyrasmussen** [comment]
That works, thank you so much!!

**Comment by Delgan** [comment]
Great, closing the ticket then. :+1:
