### ISSUE TITLE
Problems Installing

### ISSUE THREAD

**Issue by michaeltgately** [Delgan/loguru#115]
Installed using pip but loguru had no module logger, in fact the module was empty. I then downloaded the source code and attempted to install using the setup file. Ran into two problems 1) _default.py had an ASCII error and then _logger.py on line 172 errors with *,

**Comment by Delgan** [comment]
Hi @michaeltgately. Which Python version are you using?

The symptoms you describe make me think that you are using a Python version lower than 3.5.
Loguru is only available for 3.5 and higher because older Python versions are no longer officially maintained by the Python developers, so I think it's not worth making Loguru compatible with such an old version.

However, despite this old Python version you was able to `pip install loguru` because in the past I released a non-working `loguru` version without specifying that it was for Python 3.5 only. I removed this release from PyPI, so `pip` should raise an appropriate error now, if the Python version used is too old.

If possible, please update your Python installation to 3.5 or higher. :+1:

**Comment by nuclearpinguin** [comment]
I also experienced problems with pip install.
```
➜ python --version
Python 3.6.8
➜ pip install loguru
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting loguru
  ERROR: Could not find a version that satisfies the requirement loguru (from versions: none)
ERROR: No matching distribution found for loguru
```

**Comment by Delgan** [comment]
Hi @michaeltgately, can you confirm this was a problem related to the Python version?

**Comment by Delgan** [comment]
If you encounter any other problem, let me know. ;)
