### ISSUE TITLE
Can‘t Import loguru 

### ISSUE THREAD

**Issue by huangming** [Delgan/loguru#116]
```
Successfully installed loguru-0.3.1

C:\Users\******>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import loguru
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "H:\Python34\lib\site-packages\loguru\__init__.py", line 10, in <module>
    from ._logger import Logger as _Logger
  File "H:\Python34\lib\site-packages\loguru\_logger.py", line 996
    async def catch_wrapper(*args, **kwargs):
            ^
SyntaxError: invalid syntax
```

I really want to try this module.
Thanks for any suggestions.

**Comment by Delgan** [comment]
Hi @huangming.

Loguru is only available for Python 3.5 and higher. I see you are using Python 3.4: are you able tu upgrade your Python installation?

Did you installed `loguru` using `pip`? I'm quite surprised it worked fine, I would expect it to raise an error as I explicitly specified that the minimum Python version was 3.5 in `setup.py`. :confused:

**Comment by huangming** [comment]
I see.I completely ignore the python versions.Thanks.

**Comment by putyn** [comment]
is there any way to run loguru under python3.4 ? I would like to run it on a system that uses Windows XP and the most recent python version is 3.4.

**Comment by Delgan** [comment]
@putyn Not really. Newer versions of `loguru` make use of the `async def` syntax to support coroutines, making it irremediably incompatible with Python 3.4. Older versions could be made compatible, but that would require to rewrite some parts of the code to fix multiple syntax errors I suppose. Python 3.4 status is considered "end-of-life" [since one year](https://devguide.python.org/devcycle/#end-of-life-branches), so I don't plan to support it.

You may give a try to alternative Python implementation like PyPy, maybe it is compatible with Windows XP. Otherwise, I think you're "stuck" with the standard `logging` library.
