### ISSUE TITLE
Apply colors in formatter

### ISSUE THREAD

**Issue by jo47011** [Delgan/loguru#1215]
I would like loguru to highlight all elements between `<>` automatically.

It works if I invoke it like this:
```
logger.opt(colors=True).info("This is my <blue><highlighted var></blue>.  Works fine.")
```

But I do want to apply the color automatically most likely in the formater.  Base on my last issue https://github.com/Delgan/loguru/issues/537 where we removed some secrets in the formater, which works great.

But looking into the loguru source code of the `Handler.emit()` function the `colored_message` is created before the formater is applied.
So currently I don't think this is possible, correct?  Or do you have any other approach for that?

Here is the function that I tested in the formater:
```python
    def _highlight_items(self, message):
        """Function to highlight text between < and >"""
        pattern = r"(<[^>]+>)"

        return re.sub(pattern, lambda m: f"<red>{m.group(0)}</>", message)`
```

**Comment by Delgan** [comment]
Hi @jo47011.

You're correct that the colors within the message are parsed before being sent to the formatter.

However, since you have access to the message in the `record` you can create a dynamic formatter to extract the `<...>` and decorate your message this way.

```python
from loguru import logger
import re
import sys


def highlight_formatter(record):
    message = record["message"].replace("{", "{{").replace("}", "}}")  # Escape braces
    colored_message = re.sub(r"<([^>]+)>", r"<red>\1</red>", message)
    return "[<level>{level}</level>] " + colored_message + "\n{exception}"


logger.remove()
logger.add(sys.stderr, format=highlight_formatter)

logger.info("This is my <highlighted var>. Works fine.")
```

Care must be taken to escape possible braces contained in the message to avoid formatting them twice.

However, note that by using such formatter, using `opt(colors=True)` won't have any effect for this particular sink.

**Comment by jo47011** [comment]
Great, works fine.  Thanks a lot again for your prompt support and for that great package in the 1st place 🚀 👍

**Comment by jo47011** [comment]
For future readers better use this regex instead:
```python
colored_message = re.sub(r"<(.*?)>", r"<red>\1</red>", message)
```
it can handle multiple occurences of <highlighted items> in one message.
