### ISSUE TITLE
notifiers library seems to be not maintaned, maybe it's time for a replacement?

### ISSUE THREAD

**Issue by ser** [Delgan/loguru#1248]
notifiers library does not work on python 3.12 and PR for it is hanging on its github for half of year - maybe it's time to swap for another solutions for loguru? 

i'm opening a discussion here, please comment. thanks!

**Comment by Delgan** [comment]
Thanks for the notification.

I'm open to replacing `notifiers` references in the Readme and in the documentation if you have any suggestions for an alternative modern library.

**Comment by Delgan** [comment]
Haha, yes actually I remember discovering the `apprise` library a few years ago: https://github.com/caronc/apprise/issues/44

It seems to have matured nicely and feels like a natural successor to `notifiers`. Time to update the docs, I guess. :)

**Comment by caronc** [comment]
If i recall, one issue with integrating Apprise and Loguru had to do with its (Apprise) internal usage of the Python `logging` library. This causes a bit of an infinite loop problem when introducing `loguru` ... Or no?

Maybe the scoping of `apprise` logging namespace (within loguru) can be masked? Or maybe this isn't an issue anymore?

**Comment by Delgan** [comment]
Hey @caronc, nice to see you there. :smile: 
Thanks for your insight. 


> If i recall, one issue with integrating Apprise and Loguru had to do with its (Apprise) internal usage of the Python `logging` library. This causes a bit of an infinite loop problem when introducing `loguru` ... Or no?

Yes, indeed. However to be fair, this is not something specific to Loguru. This can happen with standard `logging`, as soon as Apprise is used within a handler. Here's an example that causes an infinite loop:

```python
import apprise
import logging

WEBHOOK_ID = "123"
WEBHOOK_TOKEN = "abc"


class DiscordHandler(logging.Handler):
    def __init__(self):
        super().__init__()
        self._notifier = apprise.Apprise()
        self._notifier.add(f"discord://{WEBHOOK_ID}/{WEBHOOK_TOKEN}")

    def emit(self, record):
        message = self.format(record)
        self._notifier.notify(message)


logger = logging.getLogger(__name__)

if __name__ == "__main__":
    logging.basicConfig(handlers=[logging.StreamHandler(), DiscordHandler()], level=logging.INFO)
    logger.info("Running my app")
```

Using Loguru, a comparable problam can happen, with the difference that:
* It won't cause infinite loop nor deadlock, because in recent versions of `loguru` we detect such recursion and raise a `RuntimeError` if it happens.
* The problem can only arise if the user has installed an [`InterceptHandler`](https://github.com/Delgan/loguru?#entirely-compatible-with-standard-logging) that bridges the gap between `loguru` and standard `logging` (by default Loguru does not receive standard logs, so no recursion is possible).

> Maybe the scoping of apprise logging namespace (within loguru) can be masked? Or maybe this isn't an issue anymore?

Yes, the solution in this case is to filter out all logs coming from `apprise` library so that they are not processed by the Apprise handler. It's definitely something I need to include in the snippet.

The following is working fine:

```python
import apprise
from loguru import logger

WEBHOOK_ID = "123"
WEBHOOK_TOKEN = "abc"


class InterceptHandler(logging.Handler):
    ...

def sink(message):
    notifier = apprise.Apprise()
    notifier.add(f"discord://{WEBHOOK_ID}/{WEBHOOK_TOKEN}")
    notifier.notify(message)


if __name__ == "__main__":
    logging.basicConfig(handlers=[InterceptHandler()], level=0, force=True)

    logger.add(sink, level="INFO", filter={"apprise": False})

    logger.info("Running my app")
```

Which makes me realize that I should create a helper to automate this safety filtering regardless of the sink.
