### ISSUE TITLE
typing hint （类型注解）

### ISSUE THREAD

**Issue by 212413616** [Delgan/loguru#1250]
你好，感谢你上次的回答帮了我大忙，现在我又遇到了一个疑问，麻烦你解答一下

这是我的原始代码，我原以为它没有错误
```
from loguru import Record, logger


def debugFormatter(record: Record) -> str:
    return f"{record['time']} {record['level']} {record['message']}"


logger.add("debug.log", level="DEBUG", format=debugFormatter)


logger.debug("hello world")
```

但是我运行的时候报错
```
from loguru import Record, logger
ImportError: cannot import name 'Record' from 'loguru'
```

然后我把typing hint 删除，程序正常运行，修改后的代码如下
```
from loguru import logger


def debugFormatter(record) -> str:
    return f"{record['time']} {record['level']} {record['message']}"


logger.add("debug.log", level="DEBUG", format=debugFormatter)


logger.debug("hello world")
```

我想使用typing hint
```
def debugFormatter(record: Record) -> str:
```
但是不能import Record，这是为什么呢，期待你的回答，谢谢

**Comment by Delgan** [comment]
Hi.

Can you take a look at this section of the documentation and tell me if that answers your concerns: [Why can’t I access the Logger class and other types at runtime?](https://loguru.readthedocs.io/en/latest/resources/troubleshooting.html#why-can-t-i-access-the-logger-class-and-other-types-at-runtime)

Essentially, the problem is that the `Record` class does not exist at run-time. It's only available for your type-checker. Therefore, you should guard the `Record` import with [`typing.TYPE_CHECKING`](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING):

```python
from loguru import logger
import typing

if typing.TYPE_CHECKING:
    from loguru import Record


def debugFormatter(record: "Record") -> str:
    return f"{record['time']} {record['level']} {record['message']}"


logger.add("debug.log", level="DEBUG", format=debugFormatter)


logger.debug("hello world")
```

Alternatively:

```python
from loguru import logger
import loguru


def debugFormatter(record: "loguru.Record") -> str:
    return f"{record['time']} {record['level']} {record['message']}"


logger.add("debug.log", level="DEBUG", format=debugFormatter)


logger.debug("hello world")
```

**Comment by Delgan** [comment]
I'm noticing another error: the `debugFormatter` should return a template, it should not format the message itself.

Prefer the following:

```python
def debugFormatter(record: "loguru.Record") -> str:
    return "{time} {level} {message}"
```

**Comment by 212413616** [comment]
太感谢你了，你真的很厉害，并且解答问题很快
