### ISSUE TITLE
import tqdm will cause some logger's config change back to default

### ISSUE THREAD

**Issue by blacksnail789521** [Delgan/loguru#132]
Hi,
Thanks for your great package.

The problem is as titled.
If I import tqdm,
`from tqdm import tqdm`
some logger's config will change back to the default value. (Like colorize and backtrace.)
`logger.add(sys.stderr, level = "ERROR", colorize = True, backtrace = False)`

Thanks!

**Comment by Delgan** [comment]
Hi @blacksnail789521.

I do not see any reason why importing `tqdm` would interfere with `loguru`. :confused:  

Could you please show me a fully reproducible example?

For example, if I run this:

```python

**Comment by blacksnail789521** [comment]
You can reproduce the error by importing the tqdm before adding the logger.
For example,
`import sys
from loguru import logger
from tqdm import tqdm

logger.remove()
logger.add(sys.stderr, level = "ERROR", colorize = True, backtrace = False)

def error():
    try:
        1 / 0
    except Exception:
        logger.exception("Error!")

error()`
Or you can run your code above twice using the same kernel. (ex: Run at spyder.)
You will see this scenario.
![image](https://user-images.githubusercontent.com/5949636/63516963-a0dd6500-c520-11e9-9ac4-5608dc386229.png)
Thanks again!

**Comment by Delgan** [comment]
Sorry, but I'm still unable to reproduce the error... :grimacing: 

![2019-08-22-220607_1920x1080_scrot](https://user-images.githubusercontent.com/4193924/63546048-1d744180-c529-11e9-82e3-0d0e6b367d7b.png)

As you see, the colors are displayed as expected, and the traceback is correctly limited.

**Comment by Delgan** [comment]
Ok, I finally managed to reproduce this. What a fool, I did not realize I needed to run this on Windows... :sweat_smile:

It happens because `tqdm` calls`colorama.init()` in [`tqdm/utils.py#L34`](https://github.com/tqdm/tqdm/blob/89b73bdc30c099c5b53725806e7edf3a121c9b3a/tqdm/utils.py#L34). This function is supposed to patch the `sys.stderr` stream to properly handle ansi codes and colors on Windows. For some reason, `colorama` does not recognize the Spyder `sys.stderr` as a valid tty terminal and hence strip ansi codes instead of converting them to colors.

@blacksnail789521 I found a workaround [on another issue](https://github.com/tqdm/tqdm/issues/446#issuecomment-332602798), you can just call `deinit()` after importing `tqdm`. 👍 

```python
import sys
from loguru import logger
import colorama

logger.remove()
logger.add(sys.stderr, level = "ERROR", colorize = True, backtrace = False)

from tqdm import tqdm
colorama.deinit()

logger.error("OK?")
```

**Comment by blacksnail789521** [comment]
Many thanks!
