### ISSUE TITLE
Use only custom handlers

### ISSUE THREAD

**Issue by dr-costas** [Delgan/loguru#133]
Hi, 

Thank you for your work. I'm trying to use your package and it seems that I'm missing something. 

What I'm trying to do is to have a logger that I can use throughout my project, with specified format. 

I'm doing: 

````python
from sys import stdout

logger.add(stdout, format='-- [{time:HH:mm:ss}] {level} {message}', level='INFO',
               filter=lambda record: record['extra']['me'] is True)
logger.bind(me=True).info('Hey')
````

and I get: 

````
2019-08-21 17:06:35.238 | INFO     | __main__:<module>:1 - Hey
-- [17:06:35] INFO Hey
````

but I want to get only the: 
````
-- [17:06:35] INFO Hey
````

What am I missing?

**Comment by Delgan** [comment]
Hi @dr-costas. :)

You are seeing the log messages twice because your logger is composed with two sinks: the default one (which sends messages to `stderr`) and the one you manually added (which sends messages to `stdout`).

For convenience, the Loguru's `logger` is automatically pre-configured with a default handler, so you can just `import` it and start using it.

I think you first need to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) it (you can also use [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure)):

```python
logger.remove()
logger.add(stdout, format='-- [{time:HH:mm:ss}] {level} {message}', level='INFO',
               filter=lambda record: record['extra']['me'] is True)
```

**Comment by dr-costas** [comment]
Great! Thank you!

**Comment by Delgan** [comment]
My pleasure! :p
