### ISSUE TITLE
How to set the log level?

### ISSUE THREAD

**Issue by cyberfox1** [Delgan/loguru#138]
It's strange for something that is supposed to be stupidly simple there is no setLevel() function available, as on the plain old logger I get back from getLogger().

The docs show a heavy handed approach of adding a whole new handler just to set the level like:

logger.add(sys.stderr, format="{time} {level} {message}", filter="my_module", level="INFO")

But really?

**Comment by Delgan** [comment]
I you would like to use another level in place of the default `"DEBUG"`, you can just set the `LOGURU_LEVEL` environment variable to the severity level your prefer.

Alternatively, you can just re-add the `stderr` handler with the appropriate level, you don't need to modify the `format` and `filter` attributes:

```python
logger.remove()
logger.add(sys.stderr, level="INFO")
```

**Comment by Delgan** [comment]
The thing to understand is that, contrary to standard `logging`, the Loguru's `logger` is not associated to any level: only handlers are. So, there is no `setLevel()` function because it would not make sense. The handlers are the sole master of the logs severity they accept.

**Comment by Delgan** [comment]
Feel free to re-open this issue if you have others concerns.

**Comment by ab-10** [comment]
Even though I set the `LOGURU_LEVEL=INFO` in `.env` logger still prints debug statements, could someone please suggest what could be going wrong here?

```
from loguru import logger
from dynaconf import settings

# init configs
var = settings.get("var")

logger.info(f"LOGURU_LEVEL: {os.environ['LOGURU_LEVEL']}") >> LOGURU_LEVEL: INFO
logger.debug("This shouldn't appear") >> This shouldn't appear
```

when I run the script as `LOGURU_LEVEL=INFO python -m test_loguru` the debug statement doesn't appear.

I would think this is a dynaconf issue, **but** the `os.environ` reports the correct environment variable for LOGURU_LEVEL.

**Comment by Delgan** [comment]
@ab-10 Try importing `dynaconf` before `loguru` maybe?

Loguru setup logging values at import time using environment variables. If the environment variables have not been configured yet by `dynaconf`, Loguru will use the defaults values (which is `"DEBUG"`  for logging level).

**Comment by ab-10** [comment]
> @ab-10 Try importing `dynaconf` before `loguru` maybe?
> 
> Loguru setups logging values at import time using environment variables. If the environment variables have not been configured yet by `dynaconf`, Loguru will use the default values (which is `"DEBUG"` for logging level).

That makes sense, however could you please advise why does importing loguru after the os environment variable has been set doesn't resolve the issue?

**Comment by Delgan** [comment]
@ab-10 What do you mean? Are you saying that inverting `dynaconf` with `louru` import did not solve the problem?

**Comment by ab-10** [comment]
yes, exactly

**Comment by Delgan** [comment]
@ab-10 According to [the `dynaconf` documentation](https://dynaconf.readthedocs.io/en/latest/guides/usage.html#illustrative-example), it seems environment variables are lazily loaded. The `os.environ` is not populated until `settings.get()` is called. So, if `loguru` is imported before `settings` being used, it will not have access to the configured `LOGURU_LEVEL` value.

**Comment by ab-10** [comment]
Thanks @Delgan, this really looks like a dynaconf issue. I ended up using `conda` for setting the environment variable (in `etc/conda/activate.d/env_vars.sh`) and it works as expected now.

**Comment by YuvalAdler** [comment]
Back to the original issue:
Is there a chance to add API to manipulate handlers for usages liks set_all_handlers_level?
That is, make logger._core.handlers more "public".

**Comment by Delgan** [comment]
@YuvalAdler This is not something I'm planning. To keep things simple, handlers are not exposed publicly. Some possible workarounds are [listed in the documentation](https://loguru.readthedocs.io/en/stable/resources/recipes.html#changing-the-level-of-an-existing-handler).

**Comment by deknowny** [comment]
> @ab-10 According to [the `dynaconf` documentation](https://dynaconf.readthedocs.io/en/latest/guides/usage.html#illustrative-example), it seems environment variables are lazily loaded. The `os.environ` is not populated until `settings.get()` is called. So, if `loguru` is imported before `settings` being used, it will not have access to the configured `LOGURU_LEVEL` value.

Hey! According to `dynaconf`, you can set variables that can be reset via field [__fresh_vars__](https://www.dynaconf.com/configuration/#fresh_vars).

***
Btw, can I just setup your `Dynaconf` dynamically and change logging level?

**Comment by deknowny** [comment]
Oh, `loguru` doesn't use `dynaconf`. Sorry for confusing. Anyway I can't change logging level with `os.environ` (I don't use `dynaconf` here). Is there any way to change level dynamically?

**Comment by deknowny** [comment]
I can't set loguru level dynamically with `dynaconf` or `os.environ` via enviroment variables, it works only when I set variable directly in terminal. I want to set different levels due the "development layer" inside the code but it seems there isn't any way to do this 😕

**Comment by Delgan** [comment]
@deknowny Modifying `os.envrion` or `dynaconf` will only affect the default level at the time the handlers are added. This will have no effect on existing handlers.

If you need to change the level of a handler, you will have to use one another workaround (see link to documentation in my previous post).

**Comment by deknowny** [comment]
I guess filter is the solution. Thanks!

**Comment by braveltd** [comment]
> 

environ*

**Comment by erezsh** [comment]
> ```python
> logger.remove()
> logger.add(sys.stderr, level="INFO")
> ```

@Delgan 

Why not provide a `logger.set_level()` method that just gets the last handler (like remove does), and sets the level there?

Having to remove and add, is a little clunky imho for such a common operation.

**Comment by Delgan** [comment]
@erezsh A function that only acts on the last handler would be incomplete and would not cover all use cases. I don't consider that changing the level at runtime is a common enough use case to justify adding a new function to the API, especially since it would be a special case and there may be many other reasons to change the handler.

You can define a dynamic filter to achieve the same result:

```python
import sys
from loguru import logger

min_level = "INFO"

def my_filter(record):
    return record["level"].no >= logger.level(min_level).no

logger.remove()
logger.add(sys.stderr, filter=my_filter)

logger.debug("Not logged")
min_level = "DEBUG"
logger.debug("Logged")
```

**Comment by glass-ships** [comment]
Sorry to ping on a closed issue, I was just hoping for some clarification on the accepted solutions.

One thing I'm slightly concerned about with the suggestion of "just remove and add a handler"... 

> However, if your work is intended to be used as a library, you usually should not add any handler. This is user responsibility to configure logging according to its preferences, and it’s better not to interfere with that. Indeed, since Loguru is based on a single common logger, handlers added by a library will also receive user logs, which is generally not desirable.

Is this meant in the context of importing and using my python library from within other python code? 
(ie. CLI usage is unaffected?) 
Or do I need to consider not remove-then-add a handler in my case (command line usage only)?

**Comment by glass-ships** [comment]
awesome, thanks so much delgan!!

**Comment by nav9** [comment]
Using `logger.add(sys.stderr, level="INFO")` didn't work for me. It still prints the debug logs. Even tried with `sys.stdout`. If something has changed, do let people know. People tend to reach [this](https://stackoverflow.com/questions/73733368/how-to-set-a-minimal-logging-level-with-loguru) StackOverflow page first.

**Comment by nav9** [comment]
It's important to provide some context as to what those commands do, so here's my code snippet (which I also updated [here](https://stackoverflow.com/a/73734335/453673)):  
```
import sys
from loguru import logger as log
log.remove() #remove the old handler. Else, the old one will work along with the new one you've added below'
log.add(sys.stdout, level="INFO") 
log.debug("debug message")
log.info("info message")
log.warning("warning message")
log.error("error message") 
```

**Comment by polvoazul** [comment]
My two cents:

I really like loguru, especially for small/medium scripts, where i just want to log things instead of print() them. I like the simplicity of just importing the lib and using it without jumping through hoops. I appreciate that we can have multiple handlers and all, but I guess a large share of use cases are like mine: single handler logger where i just want things to look good out of the box.  The handler abstraction itself is a distraction for this use case: I just want to import a lib and start logging stuff.

My two cents: Why not add a set_level in the top level to deal with this simple use case? The function could check if theres only a single default handler, and then perform the remove/add dance. If there are multiple handlers then just error out, as the programmer should then decide.

```
from loguru import logger
logger.set_level("ERROR")
logger.log("Hey")
logger.error("Hey")
```

looks better than 
```
from loguru import logger
logger.remove() # for someone not familiar with the lib, whats going on here?
logger.add(sys.stdout, level="ERROR"))

logger.log("Hey")
logger.error("Hey")
```

**Comment by Delgan** [comment]
@polvoazul  I appreciate your input, but from my point of view, such `set_level()` method wouldn't align with the overall design of the Loguru API. While it may appear more user-friendly, it introduces a special case that makes the relationship between the logger and handlers less straightforward. I don't want to compromise this concept just to save one line of configuration.

I agree that the "`logger.remove()` then `logger.add()`" pattern may not be immediately obvious. You could potentially replace it with `logger.configure()`:

```python
handler = {"sink": sys.stdout, "level": "ERROR"}
logger.configure(handlers=[handler])
```

**Comment by polvoazul** [comment]
Fair enough. I understand that adding a special case is indeed a bold ask (although sometimes pragmatism is valuable enough to warrant it).

Didn't know about logger.configure. This looks much better to my eye than remove/add:
```
import sys
logger.configure(handlers=[{"sink": sys.stdout, "level": "ERROR"}])
```
almost a 1 liner.

Maybe add this twoliner to the docs? I guarantee it will get ctrl-c many times :)

**Comment by avivajpeyi** [comment]
TBH i think im still a bit confused -- im trying to set `loguru`'s level to DEBUG for my pytests.... But i don't see to be getting any `logger.debug('...')` prints. 

I just added in my `conftest.py` (I don't want to add it to my `src`) 
```
import sys
logger.configure(handlers=[{"sink":`` sys.stdout, "level": "DEBUG"}])
```

**Comment by dhdaines** [comment]
> I you would like to use another level in place of the default `"DEBUG"`, you can just set the `LOGURU_LEVEL` environment variable to the severity level your prefer.

Could this *please* be in the documentation, like at the very top of the README?  The very first thing I want to know when debugging somebody else's code is "how to I increase the logging level?"  And I searched for about 10 minutes in the documentation and did not find the answer until I landed on this issue.

**Comment by 2catycm** [comment]
> LOGURU_LEVEL

Setting the log level is common enough that if there is no such function probably consider not use loguru. It is a pity that it seems there is still not a solution that can automatically gets the last handler and set its level. And what's worse, the environment variable solution needs to  restart the program all the time, not compatible to the os.environ['LOGURU_LEVEL'] method.

**Comment by Stefanhg** [comment]
Hello,

I have been looking into a simple logging tool and this was recommended to me and it looks very promising. 
But as others have mentioned it is not a very clean way having to do a `remove `and `add `a "new" handle but I understand that implementation is the reason why this feature is not implemented. But if people doesn't comment about the needs, nothing happens.

I have a few thoughts about the topic: 
1. If you have a thread running that uses the handle you need to change level of, could the data be lost when removing the handle and overriding the pointer to your `logger.bind`? 
2. It is much more clean to do `logger.set_level("INFO")` rather than the shown solutions
3. `logger.configure` does not work well because that means you need the configuration saved somewhere. Could be fixed by being able to pass an already opened logger to the `configure` command and then saving the options in the logger so the tool can pull it's configurations from there.

**My Usecase**:
If you have used `logger.level` to add 5 different levels with a bit more aggressive logging then it is nice being able to in a clean way calm down the logging.

**Comment by Stefanhg** [comment]
On top of my comment yesterday, I am very unsure about how this is supposed to be done in practical. It is such a shame this is a HUGE roadblock in this utility for my case. 

Can anyone help me with figuring out how I am supposed to do this?
I have two classes, each have it's own logging instance with separate logging level. Each class will have a method for setting log level so they independently can be changed. 

```
# Class 1
self.id = logger.add(sys.stdout, level="INFO")
self.log = logger.bind(name="my_utility_class1")
```

```
# Class 2
self.id = logger.add(sys.stdout, level="INFO")
self.log= logger.bind(name="my_utility_class2")
```

Now we change each class's log level
```
class1 = MyUtilityClass1()
class2 = MyUtilityClass2()
logger.remove(class1.id)
class1.id = logger.add(sys.stdout, level="DEBUG")
class1.log = logger.bind(name="my_utility_class1")

logger.remove(class2.id)
class2.id = logger.add(sys.stdout, level="DEBUG")
class2.log = logger.bind(name="my_utility_class2")
```

I haven't tested this since I cannot wrap my head around how this is supposed to work. It does not seem very logical how this is supposed to be approached. Anyone can help me here?

**Comment by Delgan** [comment]
Hey @Stefanhg.

Thanks for the concrete use cases. That's definitely helpful to shape the proper API of Loguru.

The solution of simply using `remove()` before `add()` (or using `configure()`) is mainly useful for adjusting the level of the default handler. For more advanced use cases, such as updating the level in the middle of the application's execution, this approach is probably not the best one (in particular due to multi-threading concerns, as you mentioned).

In such cases, I would suggest using a custom ``filter`` to control the level of the handler:

```python
min_level = logger.level("DEBUG").no

def filter_by_level(record):
    return record["level"].no >= min_level


logger.remove()
logger.add(sys.stderr, filter=filter_by_level, level=0)

logger.debug("Logged")

min_level = logger.level("WARNING").no

logger.debug("Notogged")
```

Regarding your second post, I notice that you add the same sink twice (`sys.stdout`), which is generally an anti-pattern. In such a situation, the sink won't be thread-safe. Additionally, you risk seeing duplicate logs.

If you want to adapt the level of different modules, you can use a dict as a filter or a custom function:

```python
filtering = {
    "module_1": "DEBUG",
    "module_2": "INFO",
}

logger.add(sys.stdout, filter=filtering)
```

This question appears off-topic, though. Please open a new issue and I'll try to help you in more detail.

**Comment by nielmistry** [comment]
+1 to @johann-petrak's point: using this in a jupyter notebook where environment variables are harder to change is pretty annoying. 

If I have a cell at the beginning that can set the global logger level that would make things a lot easier.

**Comment by dlroy88osu** [comment]
I too came here for the same reason... However, after reading the comments and suggestions it seems to be a simple fix... It just didn't seem to be that big of an issue in my use case... and since it is using the filter pattern lets say i am working on 1 file specifically, well now i can add that 1 file to it and set it to debug manually and everything else can stay info or err (etc)... Yeah better docs would have been helpful, but all considered not a bad workaround.

```python
import os
import sys

from loguru import logger as log


def init_logger() -> None:
    log.remove()
    log.add(sys.stderr, level=CFG.get("LOG_LEVEL", "INFO").upper())


@log.catch()
def controller() -> None:
    log.trace("This is a trace message.")
    log.debug("This is a debug message")
    log.info("This is an info message.")
    log.success("This is a success message.")
    log.warning("This is a warning message.")
    log.error("This is an error message.")
    log.critical("This is a critical message.")
    ans = 1 / 0


if __name__ == "__main__":
    os.environ["LOG_LEVEL"] = "error"
    # or load from env whatever

    init_logger()

    controller()

```
