### ISSUE TITLE
 ValueError: Tag "<locals>" does not corespond to any known ansi directive, make sure you did not misspelled it

### ISSUE THREAD

**Issue by licht1stein** [Delgan/loguru#140]
I get this error when deploying app on Heroku, locally all seems fine. Any idea how can I fix this?

``` ValueError: Tag "<locals>" does not corespond to any known ansi directive, make sure you did not misspelled it```

**Comment by Delgan** [comment]
Yep, this errors occurs when the `format` you use while adding an new handler contains tags which are not recognized by Loguru. Tags in the format are used to colorize your logs, for example: `"<green>{date}</green>"`. 

The `"<locals>"` is not a valid tag, you should escape it so that Loguru ignores it: `"\<locals>"`.

See also this paragraph of the documentation: https://loguru.readthedocs.io/en/stable/api/logger.html#color

**Comment by Delgan** [comment]
@licht1stein Did you manage to solve this issue?

**Comment by Delgan** [comment]
I modified the error message so that it is clear if a problem with the color codes is detected in the `format` while `add()` is called.

**Comment by licht1stein** [comment]
> 
> 
> @licht1stein Did you manage to solve this issue?

It hasn't in fact. Also, I'm not adding any new color tags.

**Comment by Delgan** [comment]
This error may happen if you use `opt(colors=True)` (formerly `opt(ansi=True)`), because Loguru will try to convert markup found in logged string to ansi color codes. If a markup is found but does not correspond to any known color (like `<locals>`), then an error is raised. It may also happen depending on the `format` used by your handler. You can try to `.remove()` the default handler, and `.add()` a new one while enforcing `colorize=False`.

I can't help you much without seeing code. :/

**Comment by khanfarhan10** [comment]
Hey @Delgan 

```
logger = logger.opt(colors=True)
logger.info("Logger is enabled<space>")
```

So how do I successfully show 2 just as a string?

Basically I do not want loguru to throw a value error exception (, exception=False) and print the statement as is.


Is this possible in some way using the current implementation?

**Comment by Delgan** [comment]
@khanfarhan10 Ideally, `opt(colors=True)` should be used only locally where you know the message won't contain any markup tag.

However, you can escape the invalid tag as follow:

```python
logger.info("Logger is enabled\<space>")
```
