### ISSUE TITLE
Different colors are output in files and console?

### ISSUE THREAD

**Issue by lateautumn4lin** [Delgan/loguru#153]
Hello

my code as follow:
```
import sys
from loguru import logger

config = {
    "handlers": [
        {
            "sink": "somefile.log",
            "enqueue": True,
            "retention": "10 days"
        },
        {
            "sink": sys.stdout,
            "enqueue": True,
        },
    ],
    "extra": {"user": "someone"}
}
logger.configure(**config)
logger.info(1)
logger.success(1)
logger.error(1)
```

i run it ,but `logger.error(1)`  in file is green,in console is red,can you tell me why?

**Comment by Delgan** [comment]
Hi.

It's actually quite surprising that you see any color in your log file. There exists special characters (called ansi codes) that display colors in the terminal. However, there is no such "magic" characters for text written to a file. So, when logging to a file, Loguru automatically disable the ansi codes.

There is no way to add colors to a text file. If you are seeing colors, this is probably because of the text editor you are using which probably performs syntax highlighting.

**Comment by Delgan** [comment]
@lateautumn4lin Can you confirm this is just text editor problem?

**Comment by Delgan** [comment]
I don't think there is a problem with Loguru. Feel free to ping me if you need more help.
