### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by Funk66** [Delgan/loguru#162]
Loguru could use some type hints. Is that on the roadmap yet?

**Comment by Delgan** [comment]
I actually never used type hints. What benefits do you foresee if those are added?

**Comment by Funk66** [comment]
Type hints may serve as in-code documentation and help with early bug detection, assuming your IDE supports it. Take for example the following snippet:

```python
def circumference(radius: float) -> int:
    return round(2 * radius * 3.14)


radius = input("Radius: ")
result = circumference(radius)
ratio = result.as_integer_ratio()
```
Right off the bat I can see the types of the argument and return value I can expect from this function, which may not be obvious at first if you're not familiar with the `round` method. The interface is self-explanatory without a need for docstrings.
On the other hand, a type checker would warn you about two errors as soon as you write the code:
-  `input` always returns a string, which is not a valid type for the `circumference` function
- `result` does not have the `as_integer_ratio` method because it is not a `float`
This is particularly useful when using third party modules for which you don't want to read the documentation or understand the code.

As for Loguru, having such a simple API, there is not much that can go wrong. But I still see some benefits for things like the type of the `level` argument. What if I accidentally provide a float instead if an integer? I don't want to find out at runtime.

**Comment by Delgan** [comment]
Thanks for the detailed explanations and code sample!

It seems it can indeed be useful. Anyway, as you said it looks better than docstrings to properly define function signatures. I will try to add this to the public methods of `logger`.

**Comment by Delgan** [comment]
So, it was for me the opportunity to discover Python type hints. I implemented types in a separate `.pyi` stub file rather than in-lining them for several reasons listed in the commit message (readability, performances, usability, etc.).

I did my best to annotate Loguru's public interface but there may be problems I overlooked. Please let me know if incorrect warnings are reported by your type checker. I hope this will help tools like IntelliSense auto-completion for example. :+1:
