### ISSUE TITLE
About the filter parameter in the add method

### ISSUE THREAD

**Issue by AndrewAndrea** [Delgan/loguru#164]
Hello, I just learned this library and did not understand the filter parameter, can you give me an example?How do you configure a log file to keep only one log in a class?Hope to get the answer, thank you very much!

**Comment by Delgan** [comment]
Hi @AndrewAndrea. :)

The `filter` is a function which conditionally allows or disallows a log message to be emitted to the sink. When you log a message using `logger.info("A message")` for example, a `dict` (called the "record") containing all contextual information is created. Then, for each added handler, this record is passed to the `filter` function (if any). If the call return `True`, then the message is logged, otherwise it is discarded.

Here is an example to log only `"DEBUG"` messages to a file:

```python
def only_debug(record):
    if record["level"].name == "DEBUG":
        return True
    else:
        return False

logger.add("debug.log", filter=only_debug)
logger.debug("This is message is wrote to the file.")
logger.info("This message is ignored.")
```

Does it seem more understandable to you?

**Comment by AndrewAndrea** [comment]
Hi @Delgan 👍 

Thanks for your reply，it helps me a lot, I can understand very well. 

I looked specifically at the documentation today， in [Replacing Logger objects](https://loguru.readthedocs.io/en/stable/resources/migration.html#replacing-logger-objects) 
```python
# Only write messages from "a" logger
logger.start("a.log", filter=lambda record: record["extra"].get("name") == "a")
# Only write messages from "b" logger
logger.start("b.log", filter=lambda record: record["extra"].get("name") == "b")

logger_a = logger.bind(name="a")
logger_b = logger.bind(name="b")

logger_a.info("Message A")
logger_b.info("Message B")
```
There is a sample code that uses a `lambda` expression to show that different files can log differently via the filter parameter

With your answers and examples, now I can fully understand and solve my problem.  Thank you very much!

I have a suggestion that you can put the example you wrote in the section on `filter` parameters in the documentation to help begginers.  

Thanks again!

**Comment by Delgan** [comment]
You're welcome! Glad I could help. I'm closing this issue, then.

I followed your advice and added a small snippet to the documentation, thanks for the suggestion. :smile:
