### ISSUE TITLE
I would love to `set better_exceptions.MAX_LENGTH = None`

### ISSUE THREAD

**Issue by wviana** [Delgan/loguru#173]
I've found on ExceptionFormatter class that it sets a default to 128. I couln't get a clue about some way to set it.

**Comment by Delgan** [comment]
Well, there is actually no way to modify this parameter, and I did not planned to expose it.

I recently added a snippet in the documentation about [custom exception formatting](https://loguru.readthedocs.io/en/latest/resources/recipes.html#customizing-the-formatting-of-exceptions). Basically, the following solution should allow you to manually configure max line length, using the original [`better_exceptions`](https://github.com/Qix-/better-exceptions) library:

```python
import sys
from loguru import logger
import better_exceptions
better_exceptions.MAX_LENGTH = None

def format(record):
    format_ = "{time} {message}\n"

    if record["exception"] is not None:
        record["extra"]["exc"] = better_exceptions.format_exception(*record["exception"])
        format_ += "{extra[exc]}\n"

    return format_

logger.remove()
logger.add(sys.stderr, format=format)

string = f"A very l{'o' * 1000}ng string..."

try:
    1 / string
except:
    logger.exception("Error")
```

It's a little bit cumbersome, so I may or may not extend the API to facilitate custom exception formatting in the future.

**Comment by daniel347x** [comment]
How is it that something so useful and important - the backtrace/diagnostics that Loguru wraps so well from better_exceptions (and I didn't even know that's how Loguru does it) - only has a years-old thread with like 2 comments discussing how to gain full visibility on these extraordinary backtraces?

Isn't Python used by many many thousands of programmers who presumably don't mind the extra few seconds that it takes to scroll to the right on a very long line if that means it will save hours of debugging time because you can actually see all of the variables and their values in the stack trace, rather than having them cut off "for the convenience" of not having long lines go off the right side of Notepad?

**Comment by lyf2000** [comment]
as in #1252 was said
```py
    for h in logger._core.handlers.values():
        h._exception_formatter._max_length = None
```

worked well
