### ISSUE TITLE
How to properly configure LOG_LEVEL

### ISSUE THREAD

**Issue by mikeerickson** [Delgan/loguru#18]
Hey there

I am trying to figure out how to configure `LOG_LEVEL` for all output (not just `.log` file)

Assuming I have set the `LOG_LEVEL` to `ERROR`, I am expecting only `.error` and `.critical` messages to appear in the console.  When executing this sample, the info written to log file is correct (as I would assume based on `logger.add`) but how I also make sure only .error and .critical is written to console

```
...
logger.add("{0}sample_{1}.log".format(LOG_PATH, ts), rotation="12:00", level="ERROR")

logger.error("Error log...")
logger.debug("Debug log...")
logger.info("Info log...")
logger.warning("Warning log...")
logger.critical("Critical log...")
```

**Comment by Delgan** [comment]
Hey @mikeerickson 

As you see, the `logger` emits messages to the console without you having to configure anything. This is because `loguru` automatically add an handler for convenience while you import it.

This `stderr` handler is added with some default parameters among which is `level="DEBUG"` (you can modify this through [environment variables](https://loguru.readthedocs.io/en/stable/api/logger.html#env)).

If you want to log ton console with an `"ERROR"` level, I would suggest you to `.remove()` the pre-configured handler, and start a new one with the level you prefer.

```python
logger.remove()  # Remove every possibly added handlers, including the default one
logger.add(sys.stderr, level="ERROR")
logger.add("file.log", rotation="12:00", level="ERROR")
```

**Comment by mikeerickson** [comment]
@Delgan Awesome, that did the trick!

Thank you so much for quick response
