### ISSUE TITLE
I want two logs in one line,What should I do?

### ISSUE THREAD

**Issue by Wing-Li-oceanwing** [Delgan/loguru#181]
I call logger.info twice, but it show two lines,i want to in one line ,like :print('%gx%g ' % img.shape[2:], end=''),please help me ,tks!

**Comment by Delgan** [comment]
This is not as easy as `print()` because each logging handler has its own way (possibly dynamic) to format messages.

I don't know what's your use case exactly, but basically, the easiest workaround is to postpone your logging call... :smile:

```python

**Comment by Delgan** [comment]
This is not as easy as `print()` because each logging handler has its own way (possibly dynamic) to format messages.

I don't know what's your use case exactly, but basically, the easiest workaround is to postpone your logging call... :smile:

```python
shape = img.shape[2:]
result = do_something_else()
logger.info("Result for shape {} is: {}", shape, result)
```

If you really need to send a log message without line ending, you can use a custom `format` function and `bind()` a special value to specify the termination character:

```python
def my_format(record):
    end = record["extra"].get("end", "\n")
    return "{time} {message}" + end + "{exception}"

logger.add(sys.stderr, format=my_format)
logger.info("Line ending added as usual.")
logger.bind(end="").info("No line ending.")
```

**Comment by Delgan** [comment]
Is this solution ok for you @Wing-Li-oceanwing?

**Comment by Wing-Li-oceanwing** [comment]
Thank you very much for your answer, but there is no better solution,I close this issue

**Comment by Wing-Li-oceanwing** [comment]
like: 
print('test', end='    ')
print('test2')
print('test3')

out:
test    test2
test3

I want to achieve this effect

**Comment by Delgan** [comment]
Yeah, this is not really possible because each message logged with `logger.info("test")` is formatted to `"[18:10:33][INFO][func:app.py:17] test"` for example, so it makes little sense to log two messages on the same line. One call to `logger.info()` should lead to one logged line with contextual information.

I don't know what's your use case exactly, but I think concatenating the message by yourself and logging it later is the simplest solution.

**Comment by Delgan** [comment]
@Wing-Li-oceanwing Anything else I could do? Can I close this issue otherwise?

**Comment by liwanyin** [comment]
yes, thank you very much!
