### ISSUE TITLE
Make levels comparable

### ISSUE THREAD

**Issue by t-mart** [Delgan/loguru#187]
Hey Delgan!

I'm using Loguru in an application that runs on a cloud platform. This platform ingests stdout and stderr for later viewing.

On this platform, anything written to stderr is considered an error in the logs: red text, error icons, etc. (I don't agree with this, but that's how they chose to do it.)

To play more nicely with this scheme, I decided to create 2 log sinks:
1. One for stdout for any record whose level is `<` "WARNING"
2. One for stderr for any record whose level is `>=` "WARNING

Handling #2 is easy with `add(..., level="WARNING")`. However, #1 is more difficult because `level` only sets a lower bound; It doesn't seem like there's a way to set an upper bound on level.

So, this problem seems to be better handled with a `filter`: take the record in and inspect `record["level"]`. But here, I was annoyed to find that the levels in this dict are [objects that don't support comparison](https://github.com/Delgan/loguru/blob/master/loguru/_recattrs.py#L4). Now, (I think) I'm forced to write out something like:

```python
if record["level"].name in ("WARNING", "ERROR", "CRITICAL"):
    return False
```

This is long-winded and required me to inspect the Loguru source to see all the possible levels. And that's not to mention that Loguru also supports user-defined levels.

Instead, it'd be easier to **provide comparison methods** on Level objects. Something like:

```python
class RecordLevel:
    ...
    def __eq__(self, other):
        if not isinstance(other, RecordLevel):
            return NotImplemented
        return self.no == other.no

    def __lt__(self, other):
        if not isinstance(other, RecordLevel):
            return NotImplemented
        return self.no < other.no

    # fill in others here
```

Also, you'd need to expose the core levels in the public API 😁. (I don't think exposing them in the "type hints API" would be sufficient because we'd need the objects, not the types.)

For what it's worth, [the standard library `logging` module does this too](https://github.com/python/cpython/blob/3.8/Lib/logging/__init__.py#L91) (although, the level objects there are actually just `int`s ...different, but inherently support comparison and are in the public API.)

Then, I could write something like:

```python
if record["level"] >= loguru.WARNING:
    return False
```

Much nicer.

Finally, back to `add(..., level="WARNING")`: With the core levels exposed, I import them. So, I don't have to guess that my string actually matches one of the defined levels or hope that I didn't typo the string. Instead, it'd be `level=loguru.WARNING`. (You could probably keep support for the strings to preserve compatibility, but you also have the choice not to in this pre-v1 state 😉.)

**Comment by Delgan** [comment]
Hi @t-mart. :slightly_smiling_face: 

Yeah, I have thought in the past about making levels comparable. As you, I wanted to create a level-based filter, and the most elegant and natural solution would be to use:

```python
if record["level"] >= some_level:
    ...
```

However, there is a problem: although the result of the comparison is straightforward as to whether one level is greater than another, it is not necessarily obvious when it comes to comparing two levels with the same severity:

```python
>>> foo = logger.level("FOO")
>>> bar = logger.level("BAR")
>>> foo
Level(name='FOO', no=22, color='<blue>', icon='?')
>>> bar
Level(name='BAR', no=22, color='<red>', icon='!')
```
Does `foo == bar`?... It's ambiguous. In my opinion, the answer is no: these are two different levels. They share the same severity, but they do not represent the same level. That's why I think we should not override the comparison operators.

There is an easy workaround: one should explicitly compare the two levels severity. There is no need to use `in`, the canonical way is simply:

```python
if record["level"].no >= logger.level("WARNING").no:
    ...
```

I also thought about adding "constants" like `loguru.WARNING` for levels but preferred to avoid that. First, I think it's more convenient to just type the string representation rather than needing to `import loguru` and use `loguru.WARNING`. Secondly, I quite like the fact that Loguru's api is fully contained in the `logger` object. I don't want to break this characteristic just to add level constants. So, then I could add them to the `logger` class attributes, but that's not particularly attractive neither... :sweat_smile:

That's would be probably best practice, but the benefits are not sufficient in my opinion. It's unusal to mistype a level name, and `.add()` would instantly punish you anyway. Moreover, Loguru's levels are not truly constant as they can be modified. It is therefore preferable to refer to a level using its string identifier which fetches the actual level "dynamically".

**Comment by t-mart** [comment]
Ah, ok.

I'm just finding out that levels are retrievable with `logger.level()`. Ok, that works.

Closing...
