### ISSUE TITLE
Extract log module from frame logic to a different module

### ISSUE THREAD

**Issue by iddan** [Delgan/loguru#194]
I would like to use the logic that receives the module from the frame (https://github.com/Delgan/loguru/blob/397b51f00cd56835fadd611175919408065bd950/loguru/_logger.py#L1748) in a project without using the full loguru module.
Can it be extracted? Will you accept a PR that does that?

**Comment by Delgan** [comment]
Hi @iddan. :wink:

I'm having trouble understanding exactly what your use case would be. How would this function be extracted and used? Do you plan to use something like `from loguru import get_frame_info`?

**Comment by iddan** [comment]
Hey, thank you for the quick reply! I mean something like:
```python
from loguru import get_callee_module

def my_function():
     module = get_callee_module()
     print(module)

my_function()
# Prints __main__
```

**Comment by Delgan** [comment]
Ok, thanks. Well, I prefer not to extend the api, it's part of the "design" to only have `logger` importable, and I don't want to add lower-level function than that. The `Logger` could be refactored so that one use `logger._get_info()`, but that would still remains a private method, so that's not a proper solution.

I agree that this could be useful, though. I think this kind of function would be better suited to a separate library, allowing anyone to retrieve various useful information without all the logging related stuff.

**Comment by iddan** [comment]
Exactly. So how about I create a separate package for this?

**Comment by Delgan** [comment]
Sure, why not? That's the best solution for your use case and that would probably be useful for others. As I try to avoid dependency, I will not make use of such package directly inside Loguru, though.

**Comment by Delgan** [comment]
I'm closing this issue since such function will not be added to Loguru, but if you ever publish a package to ease access of frame info, please share it here! :smile:
