### ISSUE TITLE
Would a custom json format in serialize_record have any value for loguru?

### ISSUE THREAD

**Issue by devspyrosv** [Delgan/loguru#203]
Hello!
There are cases where the extra arguments would fit nicely at the top level of the json dict.

By having the json format hardcoded in 'serialize_record' as 'serializable' it's not possible to change the final json format.

I believe that the 'serializable' variable should be accessible  just like 'format' is when adding a logger.
Would you agree with the above?

**Comment by Delgan** [comment]
Hi! :)

Extending the `serialize` attribute so that it accepts a function is a possibility, but if possible I'd rather avoid that. I prefer arguments being simple `bool` values, it's easier to reason about.

Basically, I think that if someone needs a custom way to handle logging messages, it should be implemented in a custom sink. This is the place where you transform a record to an appropriate representation.

For now, I see two "easy" ways to customize the serialization process: either add extra attributes with `bind()` /  `patch()` so that they are automatically serialized or simply use `json.dumps()` in your own sink. Is your use case not compatible with these solutions?

**Comment by devspyrosv** [comment]
I just thought that having the json format accessible just like the non serializable formatting is, would be powerful. 

Using bind and patch breaks the compatibility with the native logger and since loguru has the ability to be used similarly to it (for simple cases as a drop in replacement) I would prefer not to use them in large projects.

Checking out json.dumps in a custom sink seems right.
Thank you!

**Comment by Delgan** [comment]
> I just thought that having the json format accessible just like the non serializable formatting is, would be powerful.

I do think there are cases where it could be useful. But I also have to consider whether it's worth making the api more complex, compared to existing solutions.

> Using bind and patch breaks the compatibility with the native logger and since loguru has the ability to be used similarly to it (for simple cases as a drop in replacement) I would prefer not to use them in large projects.

I understand. But in this case, it is difficult for me to justify extending the api when there already exists a possible solution. Maybe you can use the `extra` / `patcher` attributes of the `logger.configure()` method? If you need to go back to standard `logging`, that's just one line to remove.


> Checking out json.dumps in a custom sink seems right.

Note though that as Loguru uses some custom types, you will probably need to use a fall-back serializer like `json.dumps(record, default=str)`.

**Comment by devspyrosv** [comment]
Ok! Thank you for the hint about the fall-back serializer!

**Comment by Delgan** [comment]
No problem. :)

If you have any other questions or suggestions, don't hesitate to let me know. :+1:

**Comment by mrkovalchuk** [comment]
Hello!

Can I get you another way for this problem. May be, we could go on another way. 
Watch: We have a Handler class. This class have a `_serialize_record` method. What if we can manual define and give to logger this class? Like this:

```python
class CustomHandlerClass(Handler):
    @staticmethod
    def _serialize_record(text, record):
        """SERIALIZE CODE"""
        return json.dumps(serializable, default=str) + "\n"
...
logger.add(base_handler_cls=CustomHandlerClass)
...
```

**Comment by Delgan** [comment]
Hello @mrkovalchuk. ;)

Again, I prefer not to extend the current API, particularly I would not want to introduce inheritance mechanisms. :grimacing: 

What's wrong with just making your custom `_serialze_record()` method an actual sink?

**Comment by mrkovalchuk** [comment]
@Delgan Thanks for answer!

Sorry, it's my mistake, probably. But I can't understand, how I can define custom `_serialize_record()`? 

```python
logger.add(
    sys.stderr,
    level="INFO",
    format='{level}: {time} [{name}] {message}',
    serialize=True,
)```

It's my regular handler definition. `_serialize_record()` method using in the Handler class (sink such an argument for him initialization). Where this point, what let me "making your custom `_serialze_record()` method an actual sink"?

**Comment by mrkovalchuk** [comment]
It's `patch`. Thanks. 

I reed your previous comments again and find answer. Again thanks. This is not obviously, but working.

**Comment by Delgan** [comment]
I'm not sure of what `patch()` was useful for in your case... :grin: 

What I meant is that, if you do not like the way the default `serialize` option format your logs, you can implement it your own way using a custom sink like this:

```python
def sink_serializer(message):
    record = message.record
    simplified = {
        "level": record["level"].name,
        "message": record["message"],
        "timestamp": record["time"].timestamp()
    }
    serialized = json.dumps(simplified)
    sys.stderr.write(serialized + "\n")

logger.add(sink_serializer, level="INFO", format='{level}: {time} [{name}] {message}')
```

**Comment by mrkovalchuk** [comment]
Thanks a lot!

My trouble with miss understanding sinks types and their different behaviour in a library. It's new for me. Not trivial 😞

**Comment by Delgan** [comment]
Yes, there are many valid possibilities so that the logger can be adjusted according to individual preferences. Main sink types are `str` / `Path` to log to a file, file object like `sys.stderr` or `open("foo.log")` which will be written using their `.write()` method, or a basic function which will be called with the logged message. :wink:

**Comment by Delgan** [comment]
@mrkovalchuk Yes, there are many valid possibilities so that the logger can be adjusted according to individual preferences. Main sink types are `str` / `Path` to log to a file, file object like `sys.stderr` or `open("foo.log")` which will be written using their `.write()` method, or a basic function which will be called with the logged message. A few examples can be found at the end of the [`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) documentation. :wink:

**Comment by Delgan** [comment]
Closing as a workaround has been provided.
