### ISSUE TITLE
level='INFO' no work in cmd

### ISSUE THREAD

**Issue by hou0122** [Delgan/loguru#210]
I try setting logger.add(str, level='INFO') and logger.debug('logging msg').
But cmd still output debug msg that WHY?

**Comment by Delgan** [comment]
I guess this is because of the default handler automatically added for convenience.

Try to call `logger.remove()` before `logger.add()` (it should remove all previously added handlers).

**Comment by hou0122** [comment]
I tried to call logger.remove() before logger.add() but no work.
https://repl.it/@houyanming0122/loguru

**Comment by Delgan** [comment]
It does not work because you use `str` as a sink. The sink is in charge of receiving a formatted log message and emitting it to some predefined endpoint. If you call `logger.add(str)`, each logged message will be passed to the `str` function, but this function does not output anything, that's why nothing happen.

A more appropriate sink would be the `print()` function for example. Note that the sink can also be a file-like object, so it's very common to use `sys.stderr` like this:

```python
import sys
from loguru import logger

logger.remove()
logger.add(sys.stderr, level='INFO', format='<level>{message}</level>', colorize=False)

logger.log('DEBUG', 'DEBUG test')
logger.debug('DEBUG test')

logger.log('ERROR', 'ERROR test')
logger.error('ERROR test')
```
