### ISSUE TITLE
logger in jupyter notebook not working

### ISSUE THREAD

**Issue by metya** [Delgan/loguru#214]
Hello. 

In jupyterlab logger from loguru not working. 
open jupyter and just type:
```python
from loguru import logger
logger.info('hello')
```
and nothing will happen, nothing will appear by default.

and if you want to add some logger with level with `str`, then will be an error, and if with `int`, it will be ok.

**Comment by Delgan** [comment]
Hi.

I never used Jupyter, so I may need more information to reproduce the problem. On my computer, it seems to work well:

![2020-02-11-172259_1920x1080_scrot](https://user-images.githubusercontent.com/4193924/74257397-10c0f100-4cf5-11ea-9d19-963d83fe31e1.png)

Maybe try a clean install in a new virtual environment, and install `jupyter` and `loguru` using `pip` (in case you're using `conda`).

**Comment by metya** [comment]
Hm. A little bit strange. If it affects only me, then I close the issue.

Thanks, I'll try to your suggest.

**Comment by Delgan** [comment]
Well, me not being able to reproduce the problem doesn't imply it affects only you. This may be caused by a different configuration between you and I, but other people with a configuration similar to yours may be facing the same problem.

If the problem remains, do not hesitate to ask me for help so that we can investigate what is wrong. ;)

**Comment by metya** [comment]
Ok, thank you!
