### ISSUE TITLE
Supported way to list all levels?

### ISSUE THREAD

**Issue by gahjelle** [Delgan/loguru#215]
Hi,

first of all: thank you so much for the effort you've put into `loguru`. I've been using it for a year or so, and find it an absolute joy to use. :+1: 

I have a question: Is there a supported way to list all currently defined levels?

I have been sneaking into the private API and used `logger._levels`. However, this came back to bite me slightly with v0.4 changing this to `logger._core.levels`. I'm therefore wondering if there is a better way to get at this list? Or simply a list of names of levels which I can then combine with calls to `logger.level()`?

A bit of background: I have a small wrapper around `loguru` that I use, mainly to be able to change the log level using command-line options. It's nice to normally run applications at either the `WARNING` or `INFO` level, but then from time to time easily switch to lower levels for more information. I also tend to add a few custom levels, like for instance a dedicated `TIME` level where I log the running time of different parts of my code.

Thanks again,

best, Geir Arne

**Comment by Delgan** [comment]
Hey @gahjelle, thanks for the kind words! :smiley: 

There is currently no way to get a list of all registered levels because I did not find any use case for such method. Actually, the standard `logging` module is also missing such function which suggests it's not needed.

You can rely on `logger._core.levels`, it should not change much in the future, and I would make sure to let you know if it were to be modifier, but this uses a private API so that's not recommended indeed.

The thing is that one should somehow "know" beforehand the leve used, so I don't understand how dynamically retrieving a list of levels could be useful. I think the best thing you can do is to manually maintain a list of the levels you've added.

**Comment by gahjelle** [comment]
@Delgan 

Thank you for your answer. I was mainly wondering if there was an official way to get at this. I'm happy to continue to peek behind the curtain and use `logger._core.levels`. As you say, this is also "knowable" information as the standard levels are known and I know which levels I've added.

Best,
Geir Arne

**Comment by gdlx** [comment]
Another user case is to list available log levels for a CLI parameter:
```
Usage: myapp [OPTIONS] COMMAND [ARGS]...

Options:
  -l, --log-level [TRACE|DEBUG|INFO|SUCCESS|WARNING|ERROR|CRITICAL]
```

That I setup using this Click config:
```python
@click.option('-l', '--log-level',
              default='INFO',
              type=click.Choice(
                  list(logger._core.levels.keys()),  # type: ignore
                  case_sensitive=False))
```

You can see I need to add `# type: ignore` to avoid Pylance raising an error for calling a private function.

**Comment by Delgan** [comment]
@gdlx I would advise just to list the levels manually.
