### ISSUE TITLE
Loguru to Papertrail

### ISSUE THREAD

**Issue by liquidgenius** [Delgan/loguru#218]
Thanks for the great module! I am interested in using Loguru to transmit JSON logs to Papertrail aggregation service (or any examples to a similar service). Can you point me to any resources that discuss configuring the Loguru logger to do this?

**Comment by Delgan** [comment]
Hey @liquidgenius. :wink: 

I don't know much about Papertrail, but maybe you could try to use the `SysLogHandler()` as suggested in [this article](https://blog.papertrailapp.com/papertrail-for-python-logs/):

```python
from logging import SysLogHandler
from loguru import logger

syslog = SysLogHandler(address=('logsN.papertrailapp.com', XXXXX))
logger.add(syslog)
```

Otherwise, how would you send logs to Papertrail? You can just use any function as a sink.

**Comment by Delgan** [comment]
@liquidgenius Did you manage to send logs to Papertrail in any way?
