### ISSUE TITLE
Getting the current configuration of the logger

### ISSUE THREAD

**Issue by antoine-gallix** [Delgan/loguru#239]
Hi! First of all thank you for this great package, I'm using it everywhere since I discovered it.

In my projects, if often use custom functions to configure the logger, building configuration from defaults, config files and environment variables. A logger being a global object, as my projects grow more complex, and logger get configured partially from multiple places, I often loose the track of the state of the logger configuration, and wonder why level and formatting keep changing as my program run, so I need to debug that. That's for the context. Now the question/request:

How can I access the current configuration of the logger? I can't find that either in the doc or by exploring objects.

**Comment by Delgan** [comment]
Hey @antoine-gallix, glad to know you like Loguru!

Well, there is basically no way to retrieve the current configuration because I believe the `logger` should be configured in one place, especially to avoid the kind of problem you are facing. 

What would the configuration you would expect to get look like? You can `print(logger)` to see the list of added handlers, but I don't know how helpful this is for your use case.

The "configuration" mainly lies in the [`Core`](https://github.com/Delgan/loguru/blob/e8f7825a187c906e996719510c3b022cec92f68a/loguru/_logger.py#L120) class (it contains handlers, levels, global extra dict, disabled modules, etc.) but of course it's a private attribute of the `logger` and I don't plan to expose it to the public API.

I am sure there are sometimes good reasons to modify the logger from multiple place, but this must be done carefully and I think the user is responsible to do so. In your case, what kind of changes are made by your different modules? Do you for example call `remove()` and then re-`add()` a new handler?

**Comment by antoine-gallix** [comment]
Thank you for the answer.
As one can configure the logger with a dictionary, I was looking for a way to get this dictionary back, in a way that `logger.configure(**logger.get_config())` would be idempotent. I've been looking inside the logger but stupidly I never noticed that the logger itself was printable with all the info needed. If it not as clear as a config dictionary because of anonymous stream objects and numerical log levels, it's enough for the debugging that I was looking for.

Just for your curiosity, I'm developing modules to be deployed as serverless functions, so they configure their logging by themselves. Using a function that overwrite the config (logger.configure()). But I also have tools to test them in simulated local environment, and the tool also setup it's logging. As I use loguru everywhere, that's where the confusion occurs. But I can device solutions for that. Probably by using multiple sinks.

**Comment by Delgan** [comment]
Yes, I agree accessing the config could be interesting in a few cases, but its usefulness seems too rare for it to be worth adding it to the API in my opinion.

Thanks for explaining your use case. ;)
Well, from the way Loguru was designed, modules should not be responsible for configuring the `logger`'s sinks, but I'm not sure this principle applies to your project. If there is no way to disable logger configuration by the module, maybe you can use `deepcopy(logger)` to reduce the risk of conflicts. 

Anyway, if you have any other questions, don't hesitate to ask me.
