### ISSUE TITLE
"[33m[1" instead of colored text

### ISSUE THREAD

**Issue by bataliero** [Delgan/loguru#246]
Hi, I try to integrate loguru to a project containing logging from std library. Unfortunately I got messages prepended with [33m[1 characters when script is invoked by cmd.exe or Windows PowerShell. Interestingly git-bash (mintty.exe) works good and output is colored as expected! Example below:

```
import loguru

old_logger = logging.getLogger()

stdout_handler = logging.StreamHandler(stream=sys.stdout)
old_logger.addHandler(stdout_handler)

loguru.logger.remove(handler_id=0)
for handler in old_logger.handlers:
    loguru.logger.add(handler, format="<level>{message}</level>", colorize=True)

loguru.logger.info("info example")
loguru.logger.warning("warning example")
```

```
loguru==0.4.1
  - colorama [required: >=0.3.4, installed: 0.4.3]
  - win32-setctime [required: >=1.0.0, installed: 1.0.1]

and Windows 10
```
Thanks

**Comment by Delgan** [comment]
Hey @bataliero!

So, it might seems a bit technical, but here is the explanation. On Windows, `sys.stdout` needs to be wrapped using [`colorama`](https://pypi.org/project/colorama/) to convert ansi code to actual colors. If you configure the `logger` using `logger.add(sys.stdout)`, Loguru will detects that you are passing a "stream object" (that is, an object with a `.write()` method) and it will tests the stream to know whether or not it should be internally wrapped. However, if you pass an instance of the standard [`logging.Handler`](https://docs.python.org/3/library/logging.html#logging.Handler), Loguru will not perform any verification nor wrapping as it does not have access to the stream, it will just write logs using [`handler.emit()`](https://docs.python.org/3/library/logging.html#logging.Handler.emit). In such case, it is handler's responsibility to convert possible ansi codes. As you are using `logging.StreamHandler(stream=sys.stdout)`, `sys.stdout` is never wrapped by `colorama`, and hence displays the raw ansi codes instead of the colors. This is working fine with git-bash because it is based on a terminal which natively implements ansi code coloration (like a Linux terminal).

A possible workaround is to call `colorama.init()` at the beginning of your script, this will automatically wrap `sys.stdout` so that it supports ansi codes (the same things Loguru is doing internally). :wink:

**Comment by Delgan** [comment]
@bataliero Did the workaround provided solve you problem?

**Comment by bataliero** [comment]
@Delgan, yes, it did, thanks for the answer!
