### ISSUE TITLE
Different configurations for different modules

### ISSUE THREAD

**Issue by ekallevik** [Delgan/loguru#253]
Hi! 

First of all, thank you for an awesome project! It seems to be really useful for my master thesis but I have some trouble getting the configuration right. 

First and foremost, how can I set up different thresholds for logging for different modules? 

``` python
# main.py
logger.add(sys.stderr, format="{time:HH:mm:ss} {message}",
           level="INFO", filter="main.py")
```

``` python
# preprocessing.xml_loader.py
logger.add(sys.stderr, format="{time:HH:mm:ss} {message}",
           level="CRITICAL", filter="preprocessing.xml_loader.py")
```

The output in the terminal does not seem to respect this setup. I have researched your docs, but could only find a reference to using a dict as an argument, but I could not figure out how.

In addition, I have a related issue. I don´t want to include `YYYY` in the output to the terminal, but I am unable to change the formatting in any way. By setting the environment variables through bash I have been able to change the time formatting, but then the colors disappeared which I really like.

**Comment by Delgan** [comment]
Hey @ekallevik, glad you like Loguru! :smile: 

The `filter` argument is based on the module `__name__` and not the `__file__`. I think that might explain the problem you're facing, because the trailing `.py` in your `filter` seems faulty.

Note that you need to call `logger.add()` in **only one place** (preferably your `main.py` file), otherwise it will result in duplicated logs (because you will be adding a `sys.stderr` sink twice).

```python
level_per_module = {
    "__main__": "INFO",
    "preprocessing.xml_loader": "CRITICAL",
}

logger.add(
    sys.stderr,
    format="{time:HH:mm:ss} {message}",
    level="DEBUG",
    filter=level_per_module,
)
```
Regarding your issue about time formatting: did you call `logger.remove()` before `.add()`? For convenience, a handler is pre-configured and it will write logs to `stderr` automatically once you import `loguru`. That's why you need to `remove()` it first if you want to change the date formatting. As you are configuring your `logger` with `"{time:HH:mm:ss}"`, it should work fine then.

Think that the `logger` object is one global instance to which you attach as many handlers as you want. Each time the `logger` is used, no matter where the log call is emitted from your application, it will be send to all handlers added so far.

**Comment by ekallevik** [comment]
Works like a charm! Both of my original issues are solved, but unfortunately, the output is now in plain gray. I really appreciate the colorized output. Is there someway to get it back? 

My current setup: 

```python
#main.py
class Formatter:

    def __init__(self):
        self.padding = 0
        self.fmt = "{time:HH:mm:ss}  |  {function}:{line}{extra[padding]}  |  {message}\n{" \
                   "exception}"

    def format(self, record):
        length = len("{name}:{function}:{line}".format(**record))
        self.padding = max(self.padding, length)
        record["extra"]["padding"] = " " * (self.padding - length)
        return self.fmt


formatter = Formatter()

level_per_module = {
    "__main__": "INFO",
    "preprocessing.xml_loader": "DEBUG",
}

logger.remove()
logger.add(
    sys.stderr,
    format=formatter.format,
    level="DEBUG",
    filter=level_per_module,
    colorize=False
)
```

**Comment by Delgan** [comment]
Yeah, you have to add colors tags to the log format: [The color markups](https://loguru.readthedocs.io/en/stable/api/logger.html#color)

For example: 

```python
self.fmt = "<green>{time:HH:mm:ss}</>  |  <cyan>{function}:{line}{extra[padding]}</>  |  <level>{message}</>\n{exception}"
```

**Comment by ekallevik** [comment]
Perfect! Thank you so much for your amazing work and great response! 

Keep up the good work and enjoy your weekend :)
