### ISSUE TITLE
Issue with sink filtered to TRACE level only by level name

### ISSUE THREAD

**Issue by davebirch** [Delgan/loguru#254]
Hey there, I seem to be seeing a reproducible issue affecting logging at TRACE level only.

My reproduction case is as follows:

```
def test_loguru_trace_logging_with_filtered_sink():
    logger.remove()
    stream = StringIO()
    logger.add(sink=stream, filter=lambda x: x["level"].name == "TRACE", format="{message}")

    logger.log("TRACE", "test")

    assert stream.getvalue() == "test\n"
```

For any level other than TRACE, this test will pass. Setting up the sink using level="TRACE" rather than the filter also works.

Am aware it's a fairly obscure issue, happy enough to take a poke around if it's low priority.

**Comment by Delgan** [comment]
Hey @davebirch. :)

The `level` argument takes precedence over the`filter` one. That means if the severity of your log message is not high enough, it will not be send to the sink regardless of the value returned by the filter (it's not even called).

The default value of `level` is `"DEBUG"` when you use `logger.add()`, that's why the `"TRACE"` test is only one to fail.

If you prefer all your logs to be checked by the `filter` function, you have to specify `level=0` while adding the handler.

**Comment by davebirch** [comment]
Ahh, that would make sense. Thanks for the heads up :)
