### ISSUE TITLE
Log sinks could be filterable by loguru.Level

### ISSUE THREAD

**Issue by davebirch** [Delgan/loguru#255]
Probably another minor one (but I have a PR ready for this one with some tests and a suggested fix).

I would like to be able to filter a log sink by a loguru.Level object as returned by logger.level().

After some looking into it, it seems that the RecordLevel and loguru.Level are two separate classes, just with similar fields.

It would be nice to be able to do:

`logger.set(sink, filter=lambda r: r["level"] == cached_logger_level`

The obvious way to do this would be an __eq__ method on the RecordLevel (as well as perhaps the same on Level) to allow equality if the available values (or perhaps just the level name?!) match.

**Comment by Delgan** [comment]
Thank you for taking the time to create a PR and add tests.

I agree that it would be more convenient, but in my opinion it's better to explicitly compare the `name` attribute. `Level` and `RecordLevel` are two different things, so they should not be considered equal. 

Ideally, it would be nice to use the same class. However, since it does not make much sense to have a `color` attribute in the `record` context, I created a separate class. The `Level` represents an level operated by the `logger` and existing globally, while the `RecordLevel` is just a snapshot associated with the `record` of the logged message.

Regarding your example and your PR implementing `__eq__`, there are pitfalls. For example:

```python
cached_logger_level = logger.level("TRACE")
logger.add(sink, filter=lambda r: r["level"] == cached_logger_level)
logger.level("TRACE", icon="🚀")  # I don't like the default icon, let's update it
```
Then it will not work as expected, because the `filter` will return `False`. It can't happen if `.name` is used explicitly. The solution would be to implement `__eq__` by only comparing `.name` and `.no` attributes. However, it is also acceptable to think that two levels are different if any of their attributes are not identical. So, it raises ambiguities.

Finally, by comparing level with `==` people will also be tempted to use `>=` and this is a problem because although it's obvious `logger("CRITICAL") > logger("DEBUG")`, it's not clear whether or not `level("FOO", no=10) >= level("BAR", no=10)`.

For all the reasons mentioned here, I think it is better to compare the attributes manually:
* If one wants to filter based on severity, `record["level"].no >= logger.level("CRITICAL").no`
* If one wants to filter based on value, `record["level"].name == "CRITICAL"`

**Comment by Delgan** [comment]
Closing for reasons discussed. I think it's better to be explicit while filtering by level.
