### ISSUE TITLE
Format args and kwargs and the extra parameter

### ISSUE THREAD

**Issue by jbjuin** [Delgan/loguru#257]
Hi, first of all thanks a lot for this nice piece of logging :)

I have a question: is there a way to use the keys in extra to format the message ? 
Or to add the kwargs of the debug/info/etc. to the extra parameter ? 

Let me explain more with code, today one has to do this: 

```python
logger.bind(duration=10).info("my long process duration was: {duration} seconds", duration=10)
```
to have both a nice message and a "real" value to work with for monitoring purpose.

What I'm trying to achieve is having a single logging library for all our internal applications that allow to: log normally, send exceptions to sentry, send "TRACE" levels to influxdb -> grafana and all "TRACK" levels to loki -> grafana. For instance:

```python
logger.exception("Houston we have a problem") # this goes to sentry
logger.debug("we do something") # this stays on the server
logger.track("user {username} started a long process", username="Me") # this is sent to Grafana through loki so username should be sendible in json log (serialize=True)
# later
logger.trace("long process duration was {duration} seconds", duration=10) # this is sent to Grafana through influxdb, duration should be sendible in json log (serialize=True)
```
Is it clear enough ? Am I missing something ?
It's late here and maybe I missed something obvious. If this is the case, sorry !

Anyway thanks a lot for your awesome lib !
Cheers

**Comment by Delgan** [comment]
Well, there is a way to "use the keys in extra to format the message", but you're not gonna like it... :grin:

```python
logger.bind(duration=10).opt(record=True).info("Long process duration was {record[extra][duration]} seconds")
```

It is not possible to modify the message before it is formatted using `*args` at `**kwargs`. Such feature has been discussed, but I haven't figured out how to implement it properly.

The simplest solution is to separate the context from the message, as `structlog` does.
```python
logger.add(sys.stderr, format="[{time:HH:mm:ss}] {message} (context: {extra})")
logger.bind(duration=10).info("End of the long process")
# => "[10:40:28] End of the long process (context: {'duration': 10})"
```
Otherwise, what about f-strings?
```python
duration = 10
logger.bind(duration=duration).info(f"Long process duration was {duration}")
```

**Comment by jbjuin** [comment]
Thanks for your answer !

I would like to have the cleanest and "standard" API for our young data scientist & engineers that will use it... so the extra "bind" may be too much :) 

It's already an effort to use internal libraries & configuration & tools... adding extra complexity is a risk that they miss it and that their code do not integrate well in the whole landscape.

I will have a look at `structlog` then. Thanks for pointing to it ! 
I use loguru everywhere otherwise I promise :)

Again this lib is amazing and how you respond to issues is inspiring... congrats !

**Comment by Delgan** [comment]
Thank you for all those kind words! :smiley: 

Your use case is quite interesting. It can help me to conceptualize a new way of "context logging" that would be more convenient for you and those who requested such feature. :wink:

**Comment by jbjuin** [comment]
I wish I could give more than kind words... we plan to support open source libraries as soon as we can with our company... for now it's a spiritual support.

I looked at `structlog` but custom levels are not easily possible: https://github.com/hynek/structlog/issues/47

In fact thinking again about the API I would like in loguru is a "classic" call:

```python
logger.info("Hello {msg}", msg="loguru !")
```
but that the "msg" kwargs would be available in the "extra" field... maybe as `extra["kwargs"]` or whatever key... I think I found where to do it in your code but I don't want to fork.

Any idea ?

**Comment by Delgan** [comment]
Indeed, it would be trivially possible to populate `extra["kwargs"]` with all arguments used to format the log message. However, I don't want this to be the default behavior. I prefer it to be explicitly configured by the user, if he chooses to do so.

The `logger` has been designed so that `logger.info(msg, *args, **kwargs)` is a shorthand for `msg.format(*args, **kwargs)` that just creates the logged message. Besides that, there is `bind()` which can be used to dynamically update a dict (`record["extra"]`) and provide additional context. They're two different things I'd rather not mix.

Also, if a solution had to be implemented to make the `logger` more convenient for your use case, I would love it to solve #2 at the same time. These are very related issues. This means we not only need a way to somehow add `kwargs` to the `record`, but we also need a way to allow a custom function to modify the message using `kwargs`.

I haven't come up with a solution that I liked yet, but you've gave me another use case to think about. I've got some ideas.

The best I can offer you for now is to monkeypatch the logging methods (but in addition to being hacky, it breaks `opt()`):

```python
import sys
from loguru import logger

def patch(method):
    def patched(message, *args, **kwargs):
        self = logger.opt(depth=1).bind(**kwargs)
        method(self, *args, **kwargs)
    return patched

for log_method in ("trace", "debug", "info"):
    method = getattr(logger.__class__, log_method)
    setattr(logger.__class__, log_method, patch(method))

logger.remove()
logger.add(sys.stderr, format="{extra} | {message}")

logger.info("Foo")
logger.info("Bar {foo}", foo=123)
```

**Comment by jbjuin** [comment]
Hi,
thanks a lot for your proposition. I will try it and see if it match my needs.

I have a different feeling about this:

> The logger has been designed so that logger.info(msg, *args, **kwargs) is a shorthand for msg.format(*args, **kwargs) that just creates the logged message. 

If args and kwargs in this context were just to format the message then why not pass the "formated" string directly... i think avoiding the extra .format is not a very convincing answer. 

For me the message should always be the same (or at least the beginning of the message) to be easily "grepable" when digging in log files... and values may be appended at the end to explain more. 

In fact this "end" of message could be generated: "bla bla bla... / key1=value1, key2=value2"

But I feel that always having structured values somehow is a gain... hence the args & kwargs... that should be available in a structured "container" :)

That was my 2 cents... :)
I will try your monkey patch, thanks again for all your attention !

**Comment by Delgan** [comment]
> If args and kwargs in this context were just to format the message then why not pass the "formated" string directly... i think avoiding the extra .format is not a very convincing answer.

From my observation, this is how many logging libraries handle the arguments during function call, in all languages. The standard `logging` does it too, except that it uses `%` formatting. It's pleasant not to have to type `.format()` every time.

Anyway, arguments formatting a la `stuctlog` has been requested many times. It's certainly worth adding it to `loguru`. I'll try to figure something out.

**Comment by Delgan** [comment]
@jbjuin Please, update `loguru` to `0.5.0`... The `**kwargs` arguments are now automatically added to the `extra` dict, besides being used for formatting. :grin:  

This feature can be disabled using `.opt(capture=False)`.

**Comment by jbjuin** [comment]
Whaaat !! You are a rockstar ! 
Thank you so much !

**Comment by alythobani** [comment]
Hey @Delgan !

Really wholesome seeing the interaction above :) and ditto on really enjoying and appreciating loguru! Thanks for putting so much work into it!!

My own question: As far as I can tell, the `capture=False` option is only available within `logger.opt` but not `logger.add` or anything analogous, right? Is there any way to opt out of `**kwargs` being added to `extra` with a single line of code, instead of needing to manually opt out every time something is logged using kwargs?

Personally I'd find it really useful to be able to treat `extra` solely as a dict of extra values I explicitly want included in the logged message, by including `{extra}` itself in the `format` string. This way I can use `with logger.contextualize(...)` and always have the extra vars logged with no restriction on names.

Meanwhile I often use `kwargs` in a particular log call for readability, e.g.

```py
logger.success(
    "Completed {job_name} in {formatted_duration} ({num_seconds}s)",
    job_name=get_job_name(some_object),
    formatted_duration=format_duration(num_seconds),
    num_seconds=num_seconds
)
```

but wouldn't want those kwargs cluttering up my logs (being logged as part of the `message` and duplicated in the logged `extra` dict), and wouldn't want to have to use `opt(capture=False)` every time I use kwargs either.

**Comment by Delgan** [comment]
Hi @alythobani. I appreciate your nice words, thanks. :)

> My own question: As far as I can tell, the `capture=False` option is only available within `logger.opt` but not `logger.add` or anything analogous, right?

This is correct. Keyword arguments are processed before the log message being passed to any handlers. Therefore, the decision of whether they must be included in the common `record` dict is made "locally" (at the line the message is logged).

> Is there any way to opt out of `**kwargs` being added to `extra` with a single line of code, instead of needing to manually opt out every time something is logged using kwargs?

Well, there exists a recipe explaining how to possibly do that: [Preserving an `opt()` parameter for the whole module](https://loguru.readthedocs.io/en/stable/resources/recipes.html#preserving-an-opt-parameter-for-the-whole-module).

Though, I don't consider this workaround to be very robust. The thing is that `opt()` was really meant to be the exception, not the rule. That is, Loguru is designed to capture the keyword arguments, but for some special case, this can be temporarily disabled thanks to `opt()`. 


> Personally I'd find it really useful to be able to treat `extra` solely as a dict of extra values I explicitly want included in the logged message, by including `{extra}` itself in the `format` string. This way I can use `with logger.contextualize(...)` and always have the extra vars logged with no restriction on names.
>
> Meanwhile I often use `kwargs` in a particular log call for readability

Yes, this is perfectly reasonable, and this was actually the sole purpose of keyword arguments originally. Due to popular demand, they were then augmented to also populate the `extra` dict (a la structured logging). They now have two functions (formatting and capturing), which causes a number of problems and needs to be changed.

It does not really align with what you want, but my idea for the future of Loguru is to stop using keyword arguments for message formatting altogether. They'll be captured as-is in the `record` dict, and later possibly formatted automatically by the handler. Again, this is to encourage structured logging, which is today considered best practice. For example:

```python
logger.success(
    "Job completed",
    job_name=get_job_name(some_object),
    formatted_duration=format_duration(num_seconds),
    num_seconds=num_seconds
)
```
Possible output:
```
[11:11:47] [SUCCESS] Job completed (job_name="job-281", formatted_duration="00:01:30", num_seconds=90)
```
Formatting the message would remain possible using f-string or positional arguments.

Sadly, I don't have a good solution today to the problem you raise. It's a perfectly legitimate request and one that is in line with what Loguru initially put forward, but it's bound to be obsolete.

**Comment by alythobani** [comment]
Hey @Delgan , sorry for the late reply here - been very busy lately but meant to get back to you on this eventually. Really appreciate you giving such a detailed answer!!

No worries that it's not currently possible to globally opt-out of this kwarg behavior. I'll be fine either using `.opt(capture=False)` on a given line, or being okay with the kwarg duplication in logs. Or, intentionally not formatting a given kwarg within the message, so that it's just logged as part of `extra` -- which might be more in line with the structured logging approach you mention anyway.

(I'll maybe avoid the per-module recipe personally, since the benefits maybe wouldn't outweigh the drawbacks of needing an opt-out line for each module, separate from the logging calls themselves)

Thanks again for the detailed answer and for loguru itself :)
