### ISSUE TITLE
Missing Config or is this an issue?

### ISSUE THREAD

**Issue by devsetgo** [Delgan/loguru#261]
Have an issue where Loguru is putting statements that should be filtered out in to the console. I can prevent this with standard logging, but the settings is not be respected by Loguru. This would be a security hole in an application as it would require DEBUG statements removed or possibly leak sensitive data. The level setting _**does work for the logged data,**_ but it does not prevent data from showing on the console.

Please let me know if I am missing something?

I am running Python3.8, uvicorn 0.11.5,  starlette 0.13.4, and loguru 0.4.1

![image](https://user-images.githubusercontent.com/16019894/81615842-53579f80-93b0-11ea-9f23-b665b7ff9258.png)

import logging 
from pathlib import Path

from loguru import logger
from starlette.applications import Starlette

LOGURU_LOGGING_LEVEL = "CRITICAL"

def config_log():
    

    log_path = Path.cwd().joinpath("log").joinpath("app_log.log")
    logger.add(
        log_path,
        level=LOGURU_LOGGING_LEVEL,
        format="{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}",
        enqueue=True,
        backtrace=False,
        rotation="10 MB",
        retention="10 Days",
        compression="zip",
        serialize=False,
    )

    class InterceptHandler(logging.Handler):
        def emit(self, record):

            logger_opt = logger.opt(depth=6, exception=record.exc_info)
            logger_opt.log(record.levelno, record.getMessage())

    logging.basicConfig(
        handlers=[InterceptHandler()], level=LOGURU_LOGGING_LEVEL,
    )

config_log()
logging.debug("logging")
logger.debug("logger")
logging.info("logging")
logger.info("logger")
logging.warning("logging")
logger.warning("logger")
logging.error("logging")
logger.error("logger")
logging.critical("logging")
logger.critical("logger")

app = Starlette()

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=5000, debug=False)

**Comment by Delgan** [comment]
Hi @devsetgo. I think you need to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default handler, automatically added for convenience when you import the `logger`.

If you call `logger.remove()` before `logger.add(...)`, the `DEBUG` logs should disappear. :+1:

**Comment by devsetgo** [comment]
@Delgan yes, that works. Thank you. I also created a gist to document it. Please take a quick look to make sure I didn't state something incorrect. If it is good enough, feel free to add it to your examples.

https://gist.github.com/devsetgo/28c2edaca2d09e267dec46bb2e54b9e2

**Comment by Delgan** [comment]
@devsetgo It seems good, except for the `InterceptHandler()` which uses an "old" snippet. It has been updated [in the Readme](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging).

It's nothing to worry about, it will work. The only drawbacks are that using standard `logging`:
* the messages will not be colored according to their level (because `levelno` is used and not `levelname`).
* if `logging.info()` is used without calling `logging.getLogger()`, the contextual information about the source (like function or lineno) will be inaccurate (because of `depth=6`).

**Comment by devsetgo** [comment]
Appreciate the feedback. I updated the gist.

You might consider adding the intercept as a configuration item. Something like logger.add(intercept=True). Same with propagate. That would make it a single place to manage logging.

**Comment by Delgan** [comment]
As you saw, working with `InterceptHandler()` requires calling `logging.basicConfig()`. I don't want `.add()` to have side-effects on the `logging` configuration.

More generally, I decided that `loguru` should not have to deal with `logging` stuff. These are two libraries that are fundamentally different in the way they operate. It's important that there exists a solution to communicate between each other, but the API doesn't have to adapt beyond that.

I'm not very satisfied with `InterceptHandler()` because I find it too verbose / complicated. But that's the best I could come up.
