### ISSUE TITLE
Expose a colorize function

### ISSUE THREAD

**Issue by DoronCohen** [Delgan/loguru#262]
Hi,

I wanted to ask for a colorize function that will allow to colorize a string with color tags. I am currently using `loguru` as the logger in a CLI application together with `click`. I use `click.echo` to output data to `stdout` and `logger.log` to output logs to `stderr`.

`click` has `click.secho` but colorizing is different there (`click.secho("hello", fg="red")`) and it is a hassle to colorize parts of strings. I wish I could just use `loguru`'s colorizer separately like:

```
from click import echo
from loguru import colorize

echo(colorize("This <b>is</> <e>cool</>"))
```

Thanks

**Comment by Delgan** [comment]
Hi @DoronCohen. 

I don't want to expose a coloring function, because this is not the main purpose of a logging library. The possibility to color messages has been added for convenience, but it should remain a detail.

However, there are many specialized libraries that you may enjoy. At first, `loguru` made use of [`python-ansimarkup`](https://github.com/gvalkov/python-ansimarkup) so the syntax is the same. There is also for example [`pastel`](https://github.com/sdispater/pastel) which is very similar. Last but not least, you should take a look at [`rich`](https://github.com/willmcgugan/rich) which is an amazing library to embellish your terminal.

**Comment by DoronCohen** [comment]
@Delgan thanks for the quick response. These are gold references and they solve my problems perfectly!
