### ISSUE TITLE
Logging function thread safety

### ISSUE THREAD

**Issue by jamespwilliams** [Delgan/loguru#273]
When using `loguru` with multiple threads (ThreadPoolExecutor), my logging starts to randomly cut out. I've noticed that all of the logger's handlers appear to get removed (this can be seen by printing out the `logger` instance). Below is a minimum POC that I can reliably reproduce the issue with:

```python
from loguru import logger
import concurrent.futures

def log(x):
    logger.info(x)
    print(logger)

executor = concurrent.futures.ThreadPoolExecutor(25)
executor.map(log, range(1000))
```

The output from this snippet of code is that the logger prints out the numbers fine for a certain amount of time, before stopping. The output of print(logger) also changes from `<loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>` to `<loguru.logger handlers=[]>`.

I've run into this issue using Python 3.6.8, Loguru version 0.5.0, which I believe is the latest
```
Python 3.6.8 (default, Nov 21 2019, 19:31:34)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import loguru
>>> loguru.__version__
'0.5.0'
```
This is running on a Centos 8 VM, with 1 CPU and 2GB RAM, if that is important. I've tried this on my own machine (OS X, Python 3.8.1) and haven't been able to reproduce.

**Comment by Delgan** [comment]
Hi @jamespwilliams.

I guess this happens because your main thread reach its end before the `ThreadPoolExecutor` finished its work. When the main program exits, Loguru will `stop()` and `remove()` the existing handlers. If this is done while some child threads are still running, they will not be able to use the `logger` properly.

I think you should wait for `.map()` to complete probably by calling [`executor.shutdown()`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown) or by using a context manager.

**Comment by jamespwilliams** [comment]
Ah! Thank you, this works perfectly - fixes both the POC, and the real code I was running.
