### ISSUE TITLE
extras_require misuse ?

### ISSUE THREAD

**Issue by kornicameister** [Delgan/loguru#274]
If we go [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), we ca read that `extras_require` are there to enable optional features of a program by adding some dependencies. It seems that loguru uses that as if it was `tests_require` because all that is now extra does not affect functionality and it is more or less what some of people describe as a "hack". (PS. Not judging, just reading what people write here and there ;-) )

However, given that tox discourages using `tests_require` from setuptools, this issue proposes to move to another standard approach of having `tests-requirements.txt` and:

1. having `tox` to install deps from that file
2. having `tests_require` filled with the content of that file

PS. some parts of that can be achieved with `setup_requires=('setup-meta')` which automatically fils certain parts. But that is actually reeeeeally optional :). You can check out how that performs using that project of mine and running `python setup.py explain`.

**Comment by Delgan** [comment]
Thanks for the comment. From what I read in the linked document, `extras_require` does indeed seem to be misused. I probably implemented the "dev dependencies" this way by copying what I found in other repositories or on Stackoverflow. 

However, even if it is not perfect, it is a solution that suits me because it is above all very simple. I personally prefer this solution rather than having to add a new file on which two others will depend differently.

**Comment by kornicameister** [comment]
Well, that's fine by me :). I was playing around a bit here and indeed it went like that. If you prefer it to keep that way, I have nothing against it :+1:
