### ISSUE TITLE
log trace

### ISSUE THREAD

**Issue by benjyz** [Delgan/loguru#28]
there is only debug available not trace? 

see also https://bugs.python.org/issue31732

**Comment by Delgan** [comment]
Hi @benjyz.

As evoked [in the features presentation](https://github.com/Delgan/loguru#customizable-levels), Loguru provides two additional levels (compared to the standard library): [`trace()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.trace) and [`success()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.success).

So you can use `logger.trace("Your message")` and it should work (but don't forget to set the handler level adequately otherwise logs will ne be displayed).

You can also add custom levels or modify existing ones using the [`.level()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.level) method.
