### ISSUE TITLE
How to remove default sink of a bind-logger?

### ISSUE THREAD

**Issue by WestXu** [Delgan/loguru#280]
Say I want every instance of Worker has its own logger-file and stderr output, with a customized format. Here is what the code looks like.

```python
class Worker:
    def __init__(self, name):
        self.name =  str(name)

        for sink in (sys.stderr, f'{self.name}_log.log'):
            logger.add(
                sink,
                format="{time} | {level} | {extra[name]}: {message}",
                filter=(
                    lambda record: record["extra"].get("name") == self.name
                ),
            )

        self.logger = logger.bind(name=self.name)

    def do_something(self):
        self._do()

        self.logger.info('Did something')


if __name__ == "__main__":
    logger.info('Start working!!!')
    Worker('A').do_something()
    Worker('B').do_something()
    logger.info("Let's call it a day!")

```

The problem is I get duplicated stderr for each message. Well I know I can logger.remove(), but that will  affect log outside of this class.

So can I remove the default sink only of the bind-logger, without affecting the root logger?

**Comment by Delgan** [comment]
Hi.

It seems that what you need is to replace the default handler with a new handler that logs everything not coming from a worker. For example, you could add this at the beginning of your main block:

```python
logger.remove()
logger.add(sys.stderr, filter=lambda record: "name" not in record["extra"])
```

Actually, the use of `bind()` has no influence on the handlers used. All `logger` share the same set of handlers, the `logger` is just a basic object to transfer messages. That's why you have to use `filter`, because each logged message is otherwise sent to all handlers added so far.

The default logger doesn't have a `filter`, that's why it will receive all messages and you see duplicate logs from the worker.

An alternative is to explicitly create a new `logger ` which will use a set of independent handlers, by using `copy.deepcopy(logger)`. There's this paragraph in the documentation that may be of interest to you: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers).

**Comment by WestXu** [comment]
Wow that's fast. The remove-and-add-filter way is exactly what I need! Thanks a lot. Best customer service of all GH repos! 🎉

**Comment by Delgan** [comment]
Ha ha, thanks! :grin: 

I'm closing this issue, then. If you have any other question, don't hesitate to ask me. :+1:
