### ISSUE TITLE
Execution freezes on `Handler._stop()` 

### ISSUE THREAD

**Issue by herzog0** [Delgan/loguru#282]
Hello again!
I'm trying to setup a telegram Bot account as a sink for errors that might occur in my program. 
This is the code for now:
```python
import os
import time

from telepot.exception import TelegramError
from functools import partialmethod
from loguru import logger
import telepot
import sys

TRACE = 5
DEBUG = 10
INFO = 20
ON = 21
SUCCESS = 25
WARNING = 30
ERROR = 40
CRITICAL = 50


class Singleton(type):
    _instances = {}
    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]


class TelegramSink(metaclass=Singleton):

    def __init__(self):
        self.token = os.environ.get("telegram_token", None)
        self.chat_id = os.environ.get("telegram_chat_id", None)
        self.bot = telepot.Bot(token=self.token)
        self.telegram_sink_id = None

    def ensure_setup(self):
        try:
            self.send_message("Ensuring telegram setup...")
        except TelegramError:
            logger.error("Telegram failed to setup...")
            self.bot = None
            return

    def destroy_sink(self, *args):
        logger.warning(f"Destroying telegram sink {self.telegram_sink_id}")
        #############
        # Freezing here!
        #############
        logger.remove(self.telegram_sink_id)
        logger.warning("DESTROYED")

    def send_message(self, message):
        self.bot.sendMessage(chat_id=self.chat_id, text=message, parse_mode="markdown")

    def telegram_sink(self, message):
        try:
            self.send_message(message)
        except TelegramError:
            self.destroy_sink()

    @staticmethod
    def telegram_format():
        return "*{time}*\n" \
               "*{function}*\n" \
               "*({module}:{line})*\n" \
               "*{level}*\n" \
               "{message}\n" \
               "{exception}"

    @staticmethod
    def filter(record):
        return record["level"].no == 22


@logger.catch
def setup_loggers():
    logger.level(name="TELEGRAM", no=22, color="<m>", icon="")
    logger.__class__.telegram = partialmethod(logger.__class__.log, "TELEGRAM")

    TelegramSink().ensure_setup()
    if TelegramSink().bot:
        telegram_sink_id = logger.add(sink=TelegramSink().telegram_sink,
                                      format=TelegramSink.telegram_format(),
                                      filter=TelegramSink.filter)
        logger.info(f"Adding {telegram_sink_id} as telegram's sink id")
        TelegramSink().telegram_sink_id = telegram_sink_id
    
    logger.telegram("This I'm receiving in my telegram chat")

    # Now we change the chat_id to something non-existent
    # forcing telepot to throw an error
    TelegramSink().chat_id = "65341534"

    logger.telegram("Now the execution gets blocked")


if __name__ == '__main__':
    setup_loggers()

```

As you can see in `TelegramSink().telegram_sink()`, if sending a message goes wrong (my chat_id got mistaken somehow, or my internet went down) I call  a `destroy()` method, responsible for removing the sink so the rest of the code can continue without trying to log to my telegram account (because this is not essencial, just a nice feature). The problem is that the execution gets blocked right on the call `logger.remove(self.telegram_sink_id)`. Debugging a little I've managed to see that the line in which the execution gets blocked is here:
```python
# _handler.py

class Handler:
.....
    def stop(self):
        with self._lock <------ here
        ......
```

Do you have any clues on why this is happening? I've tested with other sinks and everything works fine, I believe that this may have to do with the fact that I'm removing the sink within the sink, but it's pure guess, as I don't know the inner mechanisms of the module.

Thank you.

**Comment by Delgan** [comment]
Hi again. :)

> I believe that this may have to do with the fact that I'm removing the sink within the sink, but it's pure guess, as I don't know the inner mechanisms of the module.

You figured out the problem perfectly. Handlers are designed to be thread-safe so they use `Lock` extensively. This is important to protect both `log()` and `stop()` as we don't want a potentially complex handler to be closed while it is being used by another thread (think for example about file sinks). By using the `logger` methods from within a sink, it creates a deadlock causing your program to freeze.

Unfortunately I don't think there is any possible solution. Using a `RLock` is not enough (may still generate an infinite loop) and would cause other kind of problems (deadlock with multiprocessing). The only solution is to be careful not to use the `logger` inside a sink.

Concerning your problem, the easiest workaround is to somehow disable your `TelegramSink` when an error occurs. For example, it surely possible to use add `destroyed` attribute and update `filter()` so it returns `False` if `self.destroyed == True`. This does not solve the problem of how to call `remove()`, though. I think there's no choice but to call it manually from time to time outside the sink. You could possibly `patch()` the `logger` so that invalid handlers are removed by the next logging call (`patch()` is not protected by a lock), but it doesn't look good.

**Comment by herzog0** [comment]
Fixed just as you said. 
Before I assigned the `bot.sendMessage()` method to something dummy, but a flag in the filter is certainly much better.  
Thank you!
