### ISSUE TITLE
Using enqueue=True hangs gunicorn workers indefinately

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [Delgan/loguru#284]
I've been scratching my head for a while why my dockerized app build does not start up and hangs indefinately. I was able to extract a minimal working example that illustrates the issue:

```
import loguru
from flask import Flask


def any_sink(message):
    print(message)

loguru.logger.add(any_sink, enqueue=True)

app = Flask(__name__)

@app.route('/version', methods=['GET'])
def test_endpoint():
    return "KM"

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8081)
```

Now running the code with 
```gunicorn --worker-class=gevent --worker-connections=1000 --workers=1 --bind 0.0.0.0:8081 test:app```
for some reason causes the worker to never report back, compared to just running this module via a Flask dev server.

Not sure if the issue is on gunicorn side or not, but setting the enqueue parameter to False makes all the workers start up without any issues.

I do need that parameter, due to the fact that I'm using the subprocessing library to spawn a new process and a downstream library is not threadsafe - it buffers logs and they get overwritten before being sent. The enqueue parameter resolved the issue, but hangs with gunicorn. 

OS: Ubuntu
Versions:

gunicorn (version 20.0.4)
gevent 20.6.0
loguru 0.5.0 
Flask 1.1.1

**Comment by Delgan** [comment]
Thanks for the reproducible example. It helps me **a lot** to investigate this kind of problem.

I seem to have managed to get around the problem by moving the `logger.add()` inside the `__main__` block:

```python
if __name__ == '__main__':
    loguru.logger.add(any_sink, enqueue=True)
    app.run(host='0.0.0.0', port=8081)
```

If this is called  from outside the block, then the function will be repeated every time a child process is spawned. The problem is that you now have to explicitly pass the `logger` to the child processes (so that it inherits the handler). There is a code recipe about that you may find interesting: [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument).

That doesn't explain why your program was hanging, though. Unfortunately, I have no idea. Maybe it has something to do with the use of `gevent`? Someone had reported a similar problem which happens when [`patch_thread()`](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_thread) is used: #258.

Also, this article about `gunicorn` and `loguru` is certainly worth reading: [Unify Python logging for a Gunicorn/Uvicorn/FastAPI application](https://pawamoy.github.io/posts/unify-logging-for-a-gunicorn-uvicorn-app/).

I will continue helping you if you have any ideas about this problem, but I don't know `flask` / `gunicorn` very well.

**Comment by Delgan** [comment]
@BartlomiejLewandowski Did you find time to investigate this problem further?

**Comment by Delgan** [comment]
Please reopen this issue if you still have the problem and can help me investigate it. ;)

**Comment by a410202049** [comment]
I'm facing the same issue.

**Comment by Delgan** [comment]
@a410202049 Are you able to provide a minimal reproducible example? What about the workaround I suggested, does it work?

**Comment by zhuzihao-hz** [comment]
Hi👋 , I encountered the same problem. I also use enqueue=True in logger.

```bash
gunicorn --worker-class=gevent --workers=4 --bind 0.0.0.0:8091 app:app
```

I tried `gevent`, `gthread`, `eventlet`, only `gevent` hangs with `enqueue=True` while starting up.
Sorry, I'm not familiar with gunicorn, but some docs I found suggested using `gevent` to handle high concurrency.

Is there a solution to this problem?

This is my environment:

- Debian 12 (docker image)
- Python 3.12
- gunicorn 23.0.0
- Flask 3.1.0
- loguru 0.7.3


> I've been scratching my head for a while why my dockerized app build does not start up and hangs indefinately. I was able to extract a minimal working example that illustrates the issue:
> 
> ```
> import loguru
> from flask import Flask
> 
> 
> def any_sink(message):
>     print(message)
> 
> loguru.logger.add(any_sink, enqueue=True)
> 
> app = Flask(__name__)
> 
> @app.route('/version', methods=['GET'])
> def test_endpoint():
>     return "KM"
> 
> if __name__ == '__main__':
>     app.run(host='0.0.0.0', port=8081)
> ```
> 
> Now running the code with `gunicorn --worker-class=gevent --worker-connections=1000 --workers=1 --bind 0.0.0.0:8081 test:app` for some reason causes the worker to never report back, compared to just running this module via a Flask dev server.
> 
> Not sure if the issue is on gunicorn side or not, but setting the enqueue parameter to False makes all the workers start up without any issues.
> 
> I do need that parameter, due to the fact that I'm using the subprocessing library to spawn a new process and a downstream library is not threadsafe - it buffers logs and they get overwritten before being sent. The enqueue parameter resolved the issue, but hangs with gunicorn.
> 
> OS: Ubuntu Versions:
> 
> gunicorn (version 20.0.4) gevent 20.6.0 loguru 0.5.0 Flask 1.1.1

**Comment by Delgan** [comment]
Hi @zhuzihao-hz, sorry for the late answer.

Because Gunicorn spawns multiple subprocesses, inter-process communication using `enqueue=True` isn't straightforward. Ideally, the `logger` should be passed to the child process, but FastAPI does not provide an API to do this, as far as I know.

The recommended workaround for now is to rely on a `SocketHandler()` as explained in the documentation: [Transmitting log messages across network, processes or Gunicorn workers](https://loguru.readthedocs.io/en/latest/resources/recipes.html#transmitting-log-messages-across-network-processes-or-gunicorn-workers).

In a coming release, Loguru will provide a method to setup such handler automatically.
