### ISSUE TITLE
Are f-strings supported?

### ISSUE THREAD

**Issue by chbndrhnns** [Delgan/loguru#289]
I see in the docs that `.format()` is supported for injecting variables into log messages. How about f-strings?

**Comment by Delgan** [comment]
Hi @chbndrhnns.

F-strings should work perfectly fine. They are handled by Python itself, from the `logger` point of view there is no difference between f-strings and regular strings, because formatting occurs beforehand.

```python
answer = 42

# Both are entirely equivalent
logger.debug(f"The answer is {answer}")
logger.debug("The answer is 42")
```

If neither `*args` nor ``*kwargs`` are passed to the logging function, then `message.format(*args, **kwargs)` not called and `message` (possibly being a f-string) is logged directly.

**Comment by chbndrhnns** [comment]
Thanks! I am asking because the default logging package also kind of supports it but posts like [these](https://stackoverflow.com/a/54368086/6112272) suggest that there might be a performance penalty when doing so

**Comment by Delgan** [comment]
Indeed, there's a slight performance penalty if you want to format a message while it will not be logged due to handler's level. In such case, you are wasting time formatting a message which is not going to be used. If you pass the object to be formatted to `*args` or `**kwargs` instead of using f-strings, the formatting of the message is delayed and isn't performed if there's no need.

```python
import time
from loguru import logger

class MyClass:
    def __format__(self, spec):
        time.sleep(1)
        return "MyClass()"

instance = MyClass()

# The "TRACE" level is lower than "DEBUG", no message displayed hence no formatting
logger.trace("My instance: {}", instance)

# The formatting occurs before checking log level although the log message will be thrown away
logger.trace(f"My instance: {instance}")
```
In most cases, you don't have to worry about that and can use the f-strings without any problem. :wink:

**Comment by chbndrhnns** [comment]
Thanks so much for the verbose explanation!

**Comment by AdamGold** [comment]
@Delgan I am getting `KeyError` when trying to use f-strings (loguru out of the box, no extra configuration):
```python
logger.info(f"Updating existing webhook {existing_webhook}")
```

Error:
```bash
  File "/.venvs/prototype-integrations-manager/lib/python3.11/site-packages/loguru/_logger.py", line 1977, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "/.venvs/prototype-integrations-manager/lib/python3.11/site-packages/loguru/_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
```

**Comment by Delgan** [comment]
@AdamGold It's not possible to combine f-strings with keyword arguments, because Loguru will try to call `message.format(*args, **kwargs)` which in your case results in `"{'name': 'a'}".format(type=b)` hence the error due to `{}` in the message.

It's something I will handle eventually. For now, the workaround is to use `bind()`:

```python
logger.bind(type="b").info(f"Updating existing {a}")
```

**Comment by yuanlongliao** [comment]
@Delgan Has the exception issue been fixed?
