### ISSUE TITLE
Reenable colored logging output after calling remove() and add() - tqdm

### ISSUE THREAD

**Issue by chwba** [Delgan/loguru#290]
I followed: https://loguru.readthedocs.io/en/stable/resources/recipes.html#interoperability-with-tqdm-iterations and it worked fine. Now after tqdm bar is closed I am trying to reactivate colored output, so i tried:
`logger = logger.opt(colors=True)`
But that didnt do the trick.

**Comment by Delgan** [comment]
Hi.

This is because when one calls `logger.add(lambda msg: tqdm.write(msg, end=""))`, the `sink` being a function, Loguru can't guess whether or not the output supports colors. By default, Loguru assumes the sinks doesn't support colors. If you are sure your terminal support colors (`sys.stdout.isatty()` returns `True`), you can call `logger.add()` with the `colorize=True` parameter. Alternatively, you can call `logger.remove()` and then `logger.add(sys.stderr)`.

**Comment by chwba** [comment]
Aaah, colorize not colors, thanks man!

**Comment by Delgan** [comment]
The `colors` option is used with `logger.opt()`:

```python
logger.opt(colors=True).info("Colored <red>message</red>")
```

Such message will only be colored on added handlers supporting colors, that is either auto-detected tty sinks or handlers explicitly configured with `colorize=True`. :+1:

**Comment by Delgan** [comment]
Closing since it's resolved. ;)
