### ISSUE TITLE
Allow multiple sinks to be used

### ISSUE THREAD

**Issue by volfco** [Delgan/loguru#3]
I would love if multiple sinks could be used, and not just the one. For me, I'd like to be able to print to stdout/stderr as is the default, while also sending the messages to a custom sink. 

I would image it would be easiest to allow `logger.start` to accept a list that would be called in order.

**Comment by volfco** [comment]
Yeah, that's a bit confusing. I would think `logger.sink` would be most descriptive.

**Comment by samuelhwilliams** [comment]
Yep, I think the `start` method is a bit confusing, too. Maybe `logger.add_sink` would be a more descriptive alternative?

**Comment by Delgan** [comment]
> Yeah, that's a bit confusing. I would think `logger.sink` would be most descriptive.

@volfco That would collide with the `sink` argument itself.



> Yep, I think the `start` method is a bit confusing, too. Maybe `logger.add_sink` would be a more descriptive alternative?

@samuelhwilliams  Thanks for confirming that the method name is confusing, I will change it as soon as possible then!

I prefer not to repeat "sink" in method name, it should be a simple verb.
Once you know Loguru, you know that `.add()` is for adding a sink, there is little point to affix "sink" again. The issue is when you discover Loguru, you see `logger.start()` and may be confusing by thinking that this has to do with starting the logger, while it's about the sink.

So I could go with replacing `start()` / `stop()` by `add()` / `remove()` maybe.

**Comment by Delgan** [comment]
I released a new version `0.2.2` which deprecate `start()` and ` stop()` in favor of `add()` and `remove()`.

I hope this will be less confusing. Thanks for having reporting this. 😉
