### ISSUE TITLE
about log file name

### ISSUE THREAD

**Issue by Yancongyu** [Delgan/loguru#300]
i use like this 
![image](https://user-images.githubusercontent.com/28824230/88497707-b7732280-cff3-11ea-8fb4-f5c3b9a6d4d0.png)
but the log file name like this 
![image](https://user-images.githubusercontent.com/28824230/88497739-cf4aa680-cff3-11ea-843a-1ed04e638778.png)
 how can i fix this?

**Comment by Delgan** [comment]
Hi.

You're using f-strings, the call to `time.strftime("%Y-%m-%d")` is made **only once**: at the moment your handler is added. So, when you call `logger.add()`, the filename already looks like `"file_2020_07_21.log"`, it is not dynamically generated and Loguru does not have access to the time format. When a rotation occurs, to prevent the new file to conflict with the old one (as their names would be the same), Loguru renames it by appending the full date.

You should use a format specified instead of calling `strftime()`, and Loguru will automatically format the date during the rotation. See also [the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#time) about time formatting.

```python
logger.add("file_{time:%Y_%m_%d}.log", rotation="03:00")  # Using "old" directives
logger.add("file_{time:YYYY_MM_DD}.log", rotation="03:00")  # Using Loguru directives
```

**Comment by Yancongyu** [comment]
thx a lot.it is helpful
