### ISSUE TITLE
I want to get the color Raw string, example "[33m[1", what i shuld do? thanks 

### ISSUE THREAD

**Issue by yxxhero** [Delgan/loguru#301]
I want to get the color Raw string, example "[33m[1", what i shuld do? thanks

**Comment by Delgan** [comment]
In what context do you wish to retrieve and use them?

You can use [`colorama`](https://pypi.org/project/colorama/):

```python
>>> from colorama import Fore
>>> Fore.RED = "\x1b[31m"
```

**Comment by yxxhero** [comment]
thanks for your reply! I want get raw color string when I logger.info, because The web page will render it.  sorry, my english is poor!

**Comment by Delgan** [comment]
What type of sink (`sys.stderr`, `"file.log"`, `some_function()`, ...) are you when you call `.add()`?

If you use `colorize=True`, Loguru will systematically use [ansi escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) in the string. That is what you need, I guess.

Here is an example:

```python
def sink(message):
    print(message.encode("utf8"))

logger.add(sink, colorize=True)

logger.info("Test")
# b'\x1b[32m2020-07-28 08:07:21.759\x1b[0m | \x1b[1mINFO    \x1b[0m | \x1b[36m__main__\x1b[0m:\x1b[36m<module>\x1b[0m:\x1b[36m1\x1b[0m - \x1b[1m!\x1b[0m\n'
```

It's up to you to create an appropriate function in charge of handling the raw ansi codes. Because if you just call `print(message)` for example, the code will be automatically transformed to colors by the console.

> sorry, my english is poor!

No problem, I hope my indications are understandable. If not, do not hesitate to ask me for clarification.

**Comment by yxxhero** [comment]
Thanks! It's that I need! thank you very much!  Thank you very much for replying me out of your busy schedule.

**Comment by Delgan** [comment]
I'm glad that solved your issue. :+1: 

No problem, I try to help users as soon as I can. :)

I'm closing this ticket as I answered your question, feel free to ask me if you need more help.

**Comment by yxxhero** [comment]
```shell
>>> def sink(msg):
...     print(msg.encode("utf8"))
...     
... 
>>> from loguru import logger
>>> logger.add(sink, colorize=True)
1
>>> logger.info("123")
2020-07-28 15:01:11.793 | INFO     | __main__:<module>:1 - 123
b'\x1b[32m2020-07-28 15:01:11.793\x1b[0m | \x1b[1mINFO    \x1b[0m | \x1b[36m__main__\x1b[0m:\x1b[36m<module>\x1b[0m:\x1b[36m1\x1b[0m - \x1b[1m123\x1b[0m\n'
```

The sink output two times

**Comment by Delgan** [comment]
You need to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default sink (which logs to `sys.stderr` by default when the `logger` is imported, hence the duplicated logs).

```python
from loguru import logger

logger.remove()  # Remove all handlers added so far

logger.add(sink, colorize=True)
```

**Comment by yxxhero** [comment]
> You need first to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default sink (which logs to `sys.stderr` by default when the `logger` is imported, hence the duplicated logs).
> 
> ```python
> from loguru import logger
> 
> logger.remove()  # Remove all handlers added so far
> 
> logger.add(sink, colorize=True)
> ```

ok

**Comment by yxxhero** [comment]
```python
def sink(message):
    print(message.encode("utf8").decode("utf-8").rstrip("\n"))
```
above is useful for me. thank for you reply. @Delgan

**Comment by Delgan** [comment]
@yxxhero I think uyou don't need to encode and then decode your message. Also, the `print()` function automatically adds `"\n"` while the logging `message` also ends with a `"\n"`, that's why I guess you're using `rstrip()` but you can simply use `end=""`.

Your function is basically equivalent to:

```python
def sink(message):
    print(message, end="")
```

I guess you're using Windows, that why using suck `sink` function the ansi codes will not be converted (on Linux, the output will be colored on the terminal).

**Comment by yxxhero** [comment]
I will try it! thanks On 07/28/2020 18:26, Delgan wrote: @yxxhero I think uyou don't need to encode and then decode your message. Also, the print() function automatically adds "\n" while the logging message also ends with a "\n", that's why I guess you're using rstrip() but you can simply use end="". Your function is basically equivalent to: def sink(message):
    print(message, end="") I guess you're using Windows, that why using suck sink function the ansi codes will not be converted (on Linux, the output will be colored on the terminal). — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yxxhero** [comment]
```python
def sink(message):
    print(message, end="")
```
It's ok! Thanks very much! I hope I can also contribute to this project.
