### ISSUE TITLE
Ensuring sys.exit(1) when log level is sufficiently high

### ISSUE THREAD

**Issue by ujjwal-ai** [Delgan/loguru#306]
Thanks for this work.

I am porting an existing codebase to loguru.  I would like to ensure that whenever logger.error or logger.critical are called, sys.exit(1) is automatically invoked.  Can you kindly help me about how to write a handler for it ? It would be a great help.

**Comment by Delgan** [comment]
Well, I probably wouldn't advise doing that, because I feels its not the job of a logging function to manage the shutdown of a program. That being said, it can be done very easily with a custom sink:

```python
import sys
from loguru import logger

logger.add(lambda _: sys.exit(1), level="ERROR")
```

Rather than calling `logger.error()` and expecting the program to end, another possibility is to simply raise an exception and use [`logger.catch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch) to log it before terminating the program:

```python
with logger.catch(onerror=lambda _: sys.exit(1)):
    your_program()
```

**Comment by ujjwal-ai** [comment]
Yeah. Thanks a lot. Fortunately in my case shutdown like this is okay.
