### ISSUE TITLE
Multiple log files?

### ISSUE THREAD

**Issue by ShashankaNataraj** [Delgan/loguru#333]
Hi, Im new to loguru.

Im trying to have debug logs in debug.log
info logs in info.log
and error logs in errors.log

How do I accomplish this in loguru?

**Comment by Delgan** [comment]
Hi. You can use a custom `filter` function like this:

```python
from loguru import logger

logger.add("debug.log", filter=lambda record: record["level"].name == "DEBUG")
logger.add("info.log", filter=lambda record: record["level"].name == "INFO")
logger.add("error.log", filter=lambda record: record["level"].name == "ERROR")
```

See also this part of the documentation: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers)

Note that I'm not sure that logging should be used this way. In my opinion, it is better to log messages to the same file and filter them afterwards if needed. Otherwise, you have to be careful not to miss any levels.

**Comment by ShashankaNataraj** [comment]
@Delgan Thank you!
