### ISSUE TITLE
Change level of handler...

### ISSUE THREAD

**Issue by shaunc** [Delgan/loguru#335]
The documentation states:
> Once a handler has been added, it is actually not possible to update it. This is a deliberate choice in order to keep the Loguru’s API minimal. 

Which, all things being equal, is a fine reason. However... my use case is that I have two packages -- (say) -- producer and consumer. In test cases for consumer, I would like to write a test fixture that includes changing the log level for producer package. However, I don't want to expose the details of how the handler is set up in producer (nor change it/moneypatch it to export callable filters).

It seems to me that re-configuring log level while otherwise keeping handlers opaque is not so uncommon and contributes to package modularity. Does that make sense?

**EDIT** -- one way to implement without adding ad hoc to api surface would be to be able to push and pop (otherwise immutable) handlers. If I could push a new handler for given name(s), then later pop them to restore previous handler state, that would suffice. Of course, someone might just want to push/pop a *modification* (like a new filter :))... but, given the predilection expressed in the documentation, thought push/pop might be minimal and yet enough to cover not only this case but the whole slippery slope of handler reconfiguration...

**Comment by Delgan** [comment]
Hi @shaunc. Let's see if we can find a solution. :)

There's one thing that concerns me: it seems that you're configuring the `logger` handlers from inside your `producer` and `consumer` packages, right? Also, it seems according to the test case you described that they can be used as libraries (the `consumer` requires the `producer`). However, it is generally not recommended to add any handler from within a library (see [Configuring Logging for a Library](https://docs.python.org/3/howto/logging.html#library-config) in the standard `logging` docs). Could this be the source of the configuration difficulties you're facing?

Would that be possible in your packages to add an option preventing them from adding handlers (for the tests to configure it appropriately)?

**Comment by shaunc** [comment]
Hmm... so producer is a library, but in production consumer calls it as prefect tasks which are running in separate processes, so it has to configure logging itself. Exceptionally during testing consumer calls producer directly. I guess I allow producer to add more optional configuration for handlers. I was trying to do my best to avoid having producer being aware of how it was being run, but maybe mine is a special case.

In general I need to put some thought into how to configure logging for "the application" when the application is spread out over potentially many processes. Any tips/links to best practices would be appreciated.

**Comment by Delgan** [comment]
I think you're right to consider each component of your application separately. It's perfectly logical that everyone configures their handlers independently. That's why I was talking about adding an option. I guess that would make it easier to manage the configuration in the rare cases where your component needs to be used directly by another one.

It depends on how your different processes are launched. For example, configuring the `logger` inside a `if __name__ == "__main__"` block or inside a `__main__.py` file would prevent handlers to be added if the `producer` is used as a library.

**Comment by shaunc** [comment]
So it comes down to my adding surface area to my API vs you adding you yours. :) I guess you could argue either way, but, seeing as how (rightly) popular loguru is, adding reconfiguration for handlers for the "rare cases" would help more other people out, arguably reducing total API surface area more.  (Ok -- so maybe I'm biased ;))

If I could perhaps ask for the state of a handler and get a kw dict back that I could then update if if I wanted to change a handler by remove/add...

**Comment by Delgan** [comment]
The thing about mutating the handlers is that if I allow the `level` to me modified, why not allow it also for `filter` and `format` arguments? Then, what about all others parameters? Why couldn't they be updated too? However, how to manage special cases such as `enqueue` and `rotation`? This is the slippery slope you described I want to avoid. 

Another challenge is about identifying the handlers. If we imagine a function like `logger.update(handler_id, **kwargs)` then you need the `handler_id` returned by `.add()`. How would your `consumer` access the id of the handler added by the `producer`? Even if we implemented "named handlers" and a possibility to `.push()` / `.pop()` them, that means your `consumer` needs to know which name was used by `producer`, so it's not perfectly decoupled, right?

I may consider adding a `logger.configuration()` method which would return the current list of handlers. You're right it could help a few people, actually it has been asked at least twice: #239 and #251.
However, I'm reluctant to do that because it looks to me like an anti-pattern. Loguru is not designed to make added handlers dynamically adjustable. As we discussed, the proper solution would be in my opinion to better differentiate library / application usages en hence permit the `logger` to be configured in only one place.
The `.configuration()` solution would permit users to identify the handlers by themselves and modify them as they wish. Still I'm worried that's pointing the user in the wrong direction.

**Comment by Delgan** [comment]
I'm closing this issue because, as discussed, I don't plan to make handlers mutable nor configuration directly accessible. It's better  handled by the user, in my opinion.

**Comment by shaunc** [comment]
ok -- ... well there is a work-around...

Thanks for considering.
