### ISSUE TITLE
Filter third party modules

### ISSUE THREAD

**Issue by Xeizzeth** [Delgan/loguru#346]
It is possible to write a filter like this:
```
def formatter(record):
    if not record["exception"] and not record["name"].startswith("mymodule."):
        return ""
```
But is there a better way to filter out logging from modules that not belong to your package?

**Comment by Delgan** [comment]
You can specify a `filter` function while adding a new handler. If you don't want the message to be logged because it comes from another module, you should make the function return `False`. You can read more about this [in the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#message).

```python
def my_filter(record):
    name = record["name"]
    return name == "mymodule" or name.startswith("mymodule.")

logger.add(sys.stderr, filter=my_filter)
```

However, for convenience, the `filter` argument also accepts a simple string (as do the standard `logging` library), to automatically filter logs based on the module name:

```python
logger.add(sys.stderr, filter="my_module")  # Only messages from "my_module" and its children are loggers
```

For fine tuning, you can finally use a `dict`:

```python
my_filter = {
    "": False,  # By default, disable all
    "my_module": "DEBUG",
    "another_lib": "INFO",
    "my_module.child": "WARNING",
}

logger.add(sys.stderr, format=my_filter)
```

**Comment by Xeizzeth** [comment]
In the last example you supplied "my_filter" dictionary to "format" argument.  
Is it intentional? Or you made a mistake here? Because I presume it should be supplied to "filter" argument.

**Comment by Xeizzeth** [comment]
But it's working fine. Thank you once again.

**Comment by Delgan** [comment]
> In the last example you supplied "my_filter" dictionary to "format" argument.
> Is it intentional? Or you made a mistake here? Because I presume it should be supplied to "filter" argument.

Indeed, it was a typo. ;)

**Comment by Xeizzeth** [comment]
Pity I can't edit your messages :D  
Please edit it, because what if somebody else will look for the solution, and it won't work for them.  
And I'm closing the issue anyway, since it is pretty much answered.

**Comment by Delgan** [comment]
@Xeizzeth You're right. Done. :+1:
