### ISSUE TITLE
OSError: [Errno 116] Stale file handle

### ISSUE THREAD

**Issue by thinkall** [Delgan/loguru#358]
I meet the following error:
```
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(6, 15671, 966170), 'exception': None, 'extra': {}, 'file': (name='update.py', path='./update.py'), 'function': 'crawl', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 117, 'message': '{"info_msg":"end crawl", "function":"crawl_m", "crawled_n":441, "added_n":48}', 'module': 'update', 'name': 'update', 'process': (id=8, name='MainProcess'), 'thread': (id=139686414978088, name='GreenThread-149'), 'time': datetime(2020, 11, 5, 6, 33, 5, 382609, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/loguru/_handler.py", line 176, in emit
    self._sink.write(str_record)
  File "/usr/local/lib/python3.6/site-packages/loguru/_file_sink.py", line 173, in write
    if self._rotation_function is not None and self._rotation_function(message, self._file):
  File "/usr/local/lib/python3.6/site-packages/loguru/_file_sink.py", line 105, in rotation_size
    file.seek(0, 2)
OSError: [Errno 116] Stale file handle
--- End of logging error ---
```

I have the following files:
### init_cfg.py:
```
from loguru import logger

logger.remove(0)
fmt = "{time:YYYY-MM-DD HH:mm:ss ZZ} $ {name} $ {level} $ {message}"
logger.add(os.path.join('./log', 'logs') + '.log', format=fmt, level=LEVEL_LOG,
           backtrace=True, diagnose=False, enqueue=False, rotation="100 MB", retention=10)
```

### run_delete.py:
```
import init_cfg as cfg

def delete():
    cfg.logger.info('deleted')

if __name__ == '__main__':
    delete()
```

### update.py:
```
import init_cfg as cfg
import subprocess

def update():
    # doing jobs
    cfg.logger.info('job done')
    subprocess.run(['python', 'run_delete.py'])
```

### upgrade.py:
```
import init_cfg as cfg
import subprocess

def upgrade():
    # doing jobs
    cfg.logger.info('job done')
    subprocess.run(['python', 'run_delete.py'])
```

### main.py:
```
import init_cfg as cfg
import update as updt
import upgrade as upgd

Class Services(object):
    @timer(1000)
    def crawln(self):
        if delta_day > 5:
            cfg.logger.info(f'{{"function":"crawln", "action_name":"upgrade"}}')
            upgd.upgrade()
        else:
            cfg.logger.info(f'{{"function":"crawln", "action_name":"update"}}')
            updt.update()
```

The **main.py** is the entry file of the whole service, it will call function **crawln** every 1000 seconds, and then upgrade or update will be called.

I import **init_cfg** in all the other files, and want to use the same logger to write all the logs into the same file. At the beginning, all logs are good. After sometime, only the logs in run_delete.py can be logged, other logs all meet the same error as I show in the beginning.

How should I modify my code to avoid this error, please?

**Comment by Delgan** [comment]
Hi.

The `"[Errno 116] Stale file handle"` error can happen if Python try to read or write a file while it has been removed.

From what I see, you are trying to write to the same log file from multiple processes without synchronization. This is likely to cause problems like the one you faced. Indeed, a process will trigger the rotation of the file, but at the same time another process may be writing to the file that is deleted or invalid.

There are several solutions:
* Ensure that each sub-process writes to a different log file by using a unique identifier in `init_cfg.py`
* Use `mutliprocessing` instead of `subprocess` and [configure your handler accordingly](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)
* [Centralize the reception of logs via a dedicated process](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes) combined with `socketserver` or `zmq`
* Send logs to a Linux `syslog` server for synchronization using a [`SysLogHandler`](https://docs.python.org/3/library/logging.handlers.html#sysloghandler)

Let me know if you need more details about the solution you prefer.

**Comment by thinkall** [comment]
Ok, thanks @Delgan . I'll try the solutions and report my results later.

**Comment by thinkall** [comment]
Thanks @Delgan , I tried the first 2 solutions as you mentioned, they both worked after a few days testing.
