### ISSUE TITLE
Set LOGURU_AUTOINIT to False

### ISSUE THREAD

**Issue by Trapov** [Delgan/loguru#36]
I don't mind having an option to auto-init the sinks, but have it set to `True` by default seems off to me. As a novice user of the library i would think that i don't have any sinks set up at the start therefore calling the `.info` method would yield nothing. So wouldn't it be better to set it to `False`?

**Comment by Delgan** [comment]
Hi @Trapov.

I understand your point, and I think you are absolutely right in theory. It can be quite surprising for a logger to emit output while it has not been explicitly configured.

But Loguru is made to be as easy as possible to use. It should provide reasonable defaults which suit the main use cases. I think being able to use a logger without much configuration is a key for convenience.

This is especially true for logging, you import it because you gonna use it, so why bother with adding a `stderr` sink to each of newly created scripts, while this could be done automatically?

This reduces the temptation to use `print()` instead of the logger. In particular, I'm afraid that having to explicitly set an environment variable is a too high entry barrier for the novice user, and not much helpful. I think in most of the cases, a default sink which prints to `stderr` something is enjoyable, so it's an acceptable behavior as long as advanced user can disable it.

**Comment by Delgan** [comment]
I hope my rational made sense to you @Trapov. 😉

**Comment by gargolito** [comment]
Hi @Delgan 
The only way i've been able to disable this behavior is by setting LOGURU_AUTOINIT environment variable to False as documented. I couldn't find a way to do without having to set an environment variable so i'm using os.environ['LOGURU_AUTOINIT'] before initializing loguru but that's kind of yucky tom me. Is this the only way to turn off stderr.

The reason this is an issue is because when I write a script that's going to be a daemon and I want it to have its own log, I end up using twice the disk space: the log file I want to write to _and_ the stderr captured by the init system, in the case of journald for example.

**Comment by Delgan** [comment]
Hello @gargolito. :)

Could you not simply call `logger.remove()` during the startup of your script (before configuring possible handlers)? This will remove the default handler, acting in fact as if `LOGURU_AUTOINIT` was set to `False`.

**Comment by gargolito** [comment]
didn't think of that, thanks @Delgan
