### ISSUE TITLE
Question: when are the records formatted ?

### ISSUE THREAD

**Issue by danielhrisca** [Delgan/loguru#362]
Hello,

I was wondering when the records are formatted. For example if I use file sync will the records be formatted just before closing the file or during the program runtime?

Which of the two will be better for runtime overhead ?

```python
logger.add("file.log", enqueue=True)
# many calls like this
logger.info("costly string conversion of the _info_ object {}", _info_)
```
 or

```python
logger.add("file.log", enqueue=True)
# many calls like this
logger.info(f"costly string conversion of the _info_ object {_info_}")
```

Thank you!

**Comment by Delgan** [comment]
Hi.

Here are the different steps that take place while logging a message:
1. The `logger.info("Foobar: {}", foobar)` method is called.
2. If there is not any handler enabled with `"INFO"` level then the function exits immediately (and hence no formatting occurs).
3. Otherwise, the message is formatted: `("Foobar: {}", foobar)` => `"Foobar: <foobar_converted>"`.
4. The `record` dictionary is constructed and then sent to each handler.
5. If the handler's level is higher than `"INFO"` or if its `filter` function returns `False`, the handler stops there. 
6. Otherwise, the `record` is formatted by the handler according to its `format`: `{"time": datetime(2020, 11, 9, 19, 5, 11), "message": "Foobar: <foobar_converted>", ...}` => `"[19:05:11] Foobar: <foobar_converted>"`.
7. The formatted log message is sent to the sink which will write it to `"file.log"` for example.

In your case, if you use a f-string, the message will be formatted before being passed to the logging function (that is, at step 0). This is a possible missed optimization: if you had passed `_info_` as an argument instead, the formatting would have been postponed to step 3 and thus avoided if it was not necessary. This can happen frequently, for example for `.trace()` and `.debug()` messages, which are usually disabled in production.

However, when a message needs to be formatted, this is done in the main thread and can therefore have a negative impact on performance. I see that you use `enqueue=True`. That means the handler is run in a separate thread which can mitigate its cost. In such case, the main thread is not affected by the duration of the `record` formatting nor the call to `sink()`.

If you need also the message formatting to be threaded, you can defer it thanks to `bind()` and a custom `format` function, for example like this:

```python
def formatter(record):
    if "deferred" in record["extra"]:
        deferred_message = record["message"].format(record["extra"]["deferred"])
        record["extra"]["deferred_message"] = deferred_message
        return "[{time}] {extra[deferred_message]}\n{exception}"

    # Default format if deferred formatting is not needed
    return "[{time}] {message}\n{exception}"

logger.add("file.log", format=formatter, enqueue=True)

logger.info("The formatting happen in {} thread", "main")
logger.bind(deferred=_info_).info("The formatting will happen in the handler background thread {}")
```

Note however that messages are not written "just before closing the file", otherwise their number could grow indefinitely before the end of the program. They are written at the moment the message is logged, either in the main thread (blocking) or in the handler's thread (parallel) if `enqueue=True`.

**Comment by danielhrisca** [comment]
Thank you for the detailed explanation!

I use the `enqueue` argument because I use the logger in a multiprocess application. In my case I know for sure that the messages will end up in the log so I think using f-strings will be the (slightly) better option.

**Comment by Delgan** [comment]
Yeah, using f-string is simpler than having to use `bind()` in combination with a custom `format`. One should then avoid formatting the `_info_` object too often if performance is a concern.

**Comment by danielhrisca** [comment]
Many thanks for the great work on this project!
