### ISSUE TITLE
Base configure seems to override individual level color setting

### ISSUE THREAD

**Issue by staftermath** [Delgan/loguru#366]
`logger.configure` seems to override `logger.level` setting.

```
logger.configure(handlers=[dict(sink=sys.stdout, format="{level} {message}")])
logger.info("<- this is white")  # the INFO level tag is white and regular font
logger.level("INFO", color="<g><bold>")
logger.info("<- this is still white")  # the INFO level tag is still white and regular font
```

Now if we do this:
```
logger.info("<- this is white")
logger.level("INFO", color="<g><bold>")
logger.info("<- this is now green and bold")
```

Is there anyway to set the tag (INFO, WARNING, CRITICAL etc) to be various color while maintain msg color to be white?

**Comment by Delgan** [comment]
Hi @staftermath.

It's not a problem related to `.configure()`, it's a problem related to the `format` of your handler.

The logs you see are white because in fact they are not colored. They take the default color of a message displayed on your console.

The `logger.level("INFO", color="<g><bold>")` does not actually colors the `"INFO"` logs. Instead, it sets the color of the `<level>` tag that can be used by the `format`. See [the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#color) about color markups.

You have to specify the color tags you want to use, otherwise the logs will not contain any colors:

```python
logger.configure(handlers=[dict(sink=sys.stdout, format="<level>{level}</level> {message}")])
```

Note that the tags are automatically removed if your sink does not support colors (like `"file.log") or if the handler is configured with `colorize=Fase`.

**Comment by staftermath** [comment]
> Hi @staftermath.
> 
> It's not a problem related to `.configure()`, it's a problem related to the `format` of your handler.
> 
> The logs you see are white because in fact they are not colored. They take the default color of a message displayed on your console.
> 
> The `logger.level("INFO", color="<g><bold>")` does not actually colors the `"INFO"` logs. Instead, it sets the color of the `<level>` tag that can be used by the `format`. See [the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#color) about color markups.
> 
> You have to specify the color tags you want to use, otherwise the logs will not contain any colors:
> 
> ```python
> logger.configure(handlers=[dict(sink=sys.stdout, format="<level>{level}</level> {message}")])
> ```
> 
> Note that the tags are automatically removed if your sink does not support colors (like `"file.log"`) or if the handler is configured with `colorize=Fase`.

Thanks a lot for the quick reply!
