### ISSUE TITLE
Modifying format without overriding it

### ISSUE THREAD

**Issue by bendem** [Delgan/loguru#367]
I like the default configuration and how easy it is to start with. I'd like to add an extra field added with contextualize without overriding the defaults. I understand I can change the format, but is the format exposed somewhere?

What I have:
```shell
LOGURU_FORMAT='{time} | {level}:{extra[dataset]} | {message}' ./fetch.py
2020-11-17T14:20:12.135284+0100 | INFO:info-travaux | writing to "/tmp/info-travaux-ksck05w1.jsonl"
2020-11-17T14:20:12.135590+0100 | DEBUG:info-travaux | fetching page
2020-11-17T14:20:24.402297+0100 | INFO:info-travaux | total: 49
```

What I would like:
```shell
LOGURU_LEVEL_FORMAT='{level}:{extra[dataset]}' ./fetch.py
2020-11-17 14:28:47.044 | INFO:info-travaux     | __main__:fetch_dataset:70 - writing to "/tmp/info-travaux-qtfdh4aa.jsonl"
2020-11-17 14:28:47.044 | DEBUG:info-travaux    | __main__:paginate:53 - fetching page
2020-11-17 14:29:11.504 | INFO:info-travaux     | __main__:fetch_dataset:79 - total: 49
```

Also, I tried to use '{time!UTC}' in the format and it spit out some stacktrace so I'm guessing it's invalid. Is there a way to get UTC time using the default format?

**Comment by bendem** [comment]
Ok, I found the reason for `!UTC` to work it has to be in the format string so `{time:!UTC}` works.

**Comment by Delgan** [comment]
Hi. ;)

The default format is not easily retrievable. You need to copy it from the source code: https://github.com/Delgan/loguru/blob/1b41299643fbab269f89878226211a24bdb3e6b0/loguru/_defaults.py#L31-L37

It's not possible to configure only part of the `format`. You have to somehow store it entirely.

```bash
export LOGURU_DEFAULT_FORMAT="<g>{time:YYYY-MM-DD HH:mm:ss.SSS}</> | <lvl>{level: <8}</> | <c>{name}</>:<c>{function}</>:<c>{line}</> - <lvl>{message}</lvl>"
export LOGURU_NEW_FORMAT="<g>{time:YYYY-MM-DD HH:mm:ss.SSS}</> | <lvl>{level: <8}{level}:{extra[dataset]}</> | <c>{name}</>:<c>{function}</>:<c>{line}</> - <lvl>{message}</lvl>"
LOGURU_FORMAT=$LOGURU_NEW_FORMAT ./fetch.py
```

You can add it to `/etc/profile` or `~/.bash_profile` so you don't have to `export` the same variables all the time.

**Comment by bendem** [comment]
Alright, I'll settle on a simpler format then.
Now I'm having problem with the fact that the extra variable isn't always set. Is there some format to only add it when it's available?

**Comment by Delgan** [comment]
Well, you need to add a default value with `logger.configure(extra={"dataset": ""})`. It can't be done through environment variables unfortunately.

**Comment by bendem** [comment]
Alright, I'll use that solution for now. Would you consider that use case interesting enough to change that behaviour so that the logs aren't broken when someone tries to include extra data that isn't set?

**Comment by Delgan** [comment]
It's something I've been thinking about. Indeed, it seems much more convenient. However, this is a case where in the end I think it is better to be explicit. If there is a typo e.g. `logger.bind(datasett=foobar)` it is better to have an error message than to silently ignore it. 

In addition, it would be technically a bit complicated, because Python does not provide a way to call `format()` with a default value for missing attributes.

If your log format needs be setup dynamically, it is however possible to create a function in `patch()` or `format` to automatically replace missing values instead of passing it explicitly to `configure(extra=...)`.

**Comment by cryzed** [comment]
I was also looking for this, or something related to this. Basically I have a function with a certain context, let's say some URL, and I want to attach this URL to all logged messages in this function. Putting the URL repeatedly into all logged messages didn't seem optimal, so I was looking into `logger.bind()` to attach this "context" to a function-local logger instance.

That works, but unfortunately it doesn't show up in the default `FORMAT`. I then would have to copy loguru's default `FORMAT` (which isn't great either, because I'd prefer to just have the default `FORMAT` even if there are changes made to it in the future) and modify it to display a string from the `extra` dict. Then I have another problem, because the logger instance isn't bound everywhere with that URL, just in that function.

So now I'm at the step where I would just configure a default value globally using `logger.configure()`. However, now most log messages look off, because there's an "empty" place in the format string where the URL is missing. I was also thinking about a custom callable sink, but then I lose the nice default `FORMAT` and have to take care of writing to the actual sink myself.

Is there no easy way to do this nicely, without having to copy and modify the default `FORMAT` by hand (or import it from a private module and edit it programatically) and without disfiguring all my other log messages? It would be nice if there was some way to specify an "optional" variable `context` in the default `FORMAT` that one could just `logger.bind()` to for a given function -- which wouldn't appear otherwise.

Maybe it's obvious and I'm just missing how to do it properly?

**Comment by cryzed** [comment]
I ended up doing something like this:

```python
def get_logger_format() -> str:
    before, after = loguru._defaults.LOGURU_FORMAT.split("{message}")
    format_ = "".join([before, "{extra[context]}{message}", after])

    def context_patcher(record: loguru.Record) -> None:
        context = record["extra"].setdefault("context", "")
        if context:
            record["extra"]["context"] = f"[{context}] "

    logger.configure(patcher=context_patcher)
    return format_

logger.remove()
logger.add(sys.stderr, format=get_logger_format())
context_logger = logger.bind(context="My context")
context_logger.info("Hello World")
```

**Comment by Delgan** [comment]
Hi @cryzed.

You have to copy the format used internally, I don't plan to expose it publicly.

Just for reference, it's also possible using `inspect`:

```python
import inspect

format_ = inspect.signature(logger.add).parameters["format"].default
```

Maybe you could use a dynamic `format` instead of patching the `logger`?

```python
def formatter(record):
    if "context" in record["extra"]:
        return "{level} {extra[context]} {message}\n{exception}"
    else:
        return "{level} {message}\n{exception}"

logger.add(sys.stderr, format=formatter)
```

**Comment by cryzed** [comment]
@Delgan thanks for you reply. And yes, using a format callable instead is much better -- I missed that that was possible, thank you.

**Comment by Delgan** [comment]
@cryzed It keeps the API minimal if I don't have to expose such constants (to which it would be necessary to add levels like `loguru.DEBUG` and others). More specifically, in the case of the default format, I don't think it is made to be dynamically modified. Especially since it can be defined via an environment variable. If one needs to customize the logging format, it is better to define it explicitly.

**Comment by cryzed** [comment]
@Delgan I just noticed that when I use a callable for `format`, no tracebacks are shown for `logger.exception()` calls, even when I explicitly set `traceback=True` and `diagnose=True`. When I do not set a callable for `format`, but any string instead, the tracebacks are shown as expected. Am I missing something or is this a bug?

**Comment by Delgan** [comment]
I'm closing this issue as it seems the question is answered. Feel free to re-open it otherwise. ;)
