### ISSUE TITLE
Logger from config file?

### ISSUE THREAD

**Issue by LucaBonfiglioli** [Delgan/loguru#374]
Hello, I started using loguru not too long ago, so I might be missing some crucial information. 

I am looking for a way to replace `logging.fileConfig` with `Logger.configure`, but I have read in the docs that the `Logger.configure` method does not accept `config.ini` files, so I guess that the user has to explicitly define a custom configuration schema and factory that handles the creation of `Logger` objects from configuration files.

Is there any way to avoid that?

**Comment by Delgan** [comment]
Hi. ;)

Indeed, it is only possible to configure the `logger` using a Python `dict`. Loguru does not provide any other built-in solution.

This is a deliberate choice due to the possible complexity of the configuration (e.g. using a function as a format would be invalid in `.ini`). You can either load it from a `.json`, an `.ini` or a Python module but you have to decide by yourself if and how to handle special cases.

**Comment by LucaBonfiglioli** [comment]
I understand, thank you very much for your reply.

**Comment by Delgan** [comment]
For anyone coming across this issue, note that there exists the `loguru-config` library to configure the logger from a file: https://github.com/erezinman/loguru-config.
