### ISSUE TITLE
logger.parse example with default pattern?

### ISSUE THREAD

**Issue by charlesincharge** [Delgan/loguru#377]
Would it be possible to adapt the README.md `logger.parse` example to use the default logger format?

The current pattern
```python
pattern = r"(?P<time>.*) - (?P<level>[0-9]+) - (?P<message>.*)"  # Regex with named groups
```
doesn't match the default log structure, e.g.:
```
2019-04-07 11:08:44.198 | DEBUG    | __main__:bar:30 - Entering 'foo' (args=(2, 4), kwargs={'c': 8})
2019-04-07 11:08:44.198 | INFO     | __main__:foo:26 - Inside the function
2019-04-07 11:08:44.198 | DEBUG    | __main__:bar:30 - Exiting 'foo' (result=64)
```

I'm not great with regexes, so if there's also a straightforward way to convert from Python string formats to patterns, that would also help.

**Comment by Delgan** [comment]
You're right, it's not very intuitive. The problem is that the default format is quite complex. I'm afraid it's too cumbersome to introduce it in the README.

You could use this pattern for example:

```python
pattern = r"(?P<time>.*) \| (?P<level>.*) \| (?P<context>.*?) - (?P<message>.*)"
```

At some point I thought about automatically inferring the format to parse the logs but this is actually very complicated, so I gave up on the idea.

**Comment by charlesincharge** [comment]
Thanks @Delgan !

That would be really nice, but yeah makes sense that that would be tough.
