### ISSUE TITLE
How to configure existing logger handle

### ISSUE THREAD

**Issue by ma-sadeghi** [Delgan/loguru#412]
Currently, when I want to configure loguru, I delete the current handle, and add a new one:
```python
from loguru import logger

logger.remove()
logger.add(lambda msg: tqdm.write(msg, end=""),
           level=loglevel,
           format=fmt,
           colorize=True)
```
Is this the correct way? I suspect there should be a way to just configure the existing handle, rather than deleting it and creating a new one with desired settings.

**Comment by Delgan** [comment]
This is the correct way. :smile: 

It is not possible to modify a handler once added. If you don't need the default handler, you have to remove it first (or set the environment variable `"LOGURU_AUTOINIT"` to `"NO"`).

It also possible to use [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) instead of `remove()` and `add()` (it performs a "clean" configuration and remove existing handlers):

```python
tqdm_handler = dict(sink=lambda msg: tqdm.write(msg, end=""), level=loglevel, format=fmt, colorize=True)
logger.configure(handlers=[tqdm_handler])
```

**Comment by Delgan** [comment]
I'm closing this issue, but don not hesitate if you need anything else.
