### ISSUE TITLE
stderr from error and above

### ISSUE THREAD

**Issue by mihaimyh** [Delgan/loguru#422]
Hi,

First of all I would like to congratulate for this awesome library, made my logging experience with Python really simple.

I am not sure if I am using the correct way to setup a logger, what I would like to do is to log to stderr from error level above (error, critical, etc).

My current implementation logs error messages to stdout:

```
def setup_logger():
    logger.remove()
    logger.add('/tmp/ssh.log', format="{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}", level='DEBUG',
               enqueue=True, retention="14 days")
    logger.add(sys.stdout, colorize=True, format="{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}", level='INFO',
               enqueue=True)
```

Is there a way do to this?

**Comment by Delgan** [comment]
Hey @mihaimyh, thanks for the kind words! :smile: 

I'm not sure to understand what you're looking for. Can you simply add an `stderr` handler with `level="ERROR"`?

```python
logger.add(sys.stderr, level="ERROR")
```

The `level` parameter works like a filter: only messages from this severity and above will be logged.

**Comment by mihaimyh** [comment]
Hi @Delgan , but this means that error messages will be logged on stdout also.

**Comment by Delgan** [comment]
Indeed. So you want `"ERROR"` and below to `stdout`, but `"ERROR"` and above to `stderr`?

In this case you may use a function to `filter` logs emitted to `stdout`:

```python
logger.add(sys.stdout, filter=lambda record: record["level"].no < 40, level="INFO", ...)
```

**Comment by mihaimyh** [comment]
Thanks, this is what I was looking for.

**Comment by PyAntony** [comment]
I was about to write something like this after reading the documentation. I just googled it to see if someone is asking the same. This approach is only intuitive if you have read the documentation though. A better approach would be to add a parameter to `add()`, a parameter like `upper_level` (int, str) or/and `levels_alllowed` (list[str], list[int]).

**Comment by Delgan** [comment]
Hi @PyAntony.

Defining the level of an handler as the "minimum threshold" for messages to be emitted is a very popular principle among logging libraries. You can look at it this way: by default we don't want to display debug messages to the user, thus we set the minimal level to "INFO". However, when something goes wrong, debug messages exist to give more detailed information next to the error messages. If both message are separated in two files, context is lost which makes investigating bugs more challenging. It makes little sense to have the fine grained details without a global view of what is happening. 

That's why in my opinion new arguments like `upper_level` or `levels_allowed` should not be added to the `add()` method. I don't think this is a good practice when using Loguru.

If you need multiple logs to appear in multiple files (for example), it's advised to use [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) with a custom `filter` sink function.

**Comment by PyAntony** [comment]
thank you for taking the time to explain this! it totally make sense now.

**Comment by caleb-artifact** [comment]
I feel like your opinion on this issue heavily depends on if you use kubernetes or not.  Kuberentes treats all statements in stderr as errors.  So by default using loguru in kubernetes environments will initially give you a panic attack when you see thousands upon thousands of errors show up all of a sudden.  It would be great to have an easy way to direct all non-error messages to stdout, and all warning and above messages to stderr.  Would greatly reduce the amount of boilerplate code needed for every docker container.

**Comment by Delgan** [comment]
@caleb-artifact Thanks for the additional use case, I didn't know Kubernetes treated `stderr` and `stdout` like that.

Loguru writes all logs to the `stderr` by default so it doesn't interfere with the actual output of the program on `stdout`. It's common practice for logging utilities to print to `stderr`, which is defined by POSIX standards as being intended for "writing diagnostic output" (not limited to errors).

Some projects such as Kubernetes have made a different use of `stderr`, which reduces seamless compatibility with Loguru and others. That is unfortunate, but I don't think I should extend the API to account for all existing usages.

The workaround provided does not require much boilerplate: just a `filter` function. Additionally, I expect Kubernetes to provide an option to not treat `stderr` as errors. "INFO" and "ERROR" messages have different severity levels but they belong to the same cohesive logging output, it makes little sense to split them in my opinion. Finally, I suppose best practice would probably be for users to add an handler specifically dedicated to sending errors to Kubernetes without relying on `stderr`.
