### ISSUE TITLE
Use size-based retention?

### ISSUE THREAD

**Issue by danlkv** [Delgan/loguru#426]
Hi, is it possible to use both size-based rotation _and_ retention? For example, rotate every 100MB, but if total size of all logs is larger than 20GB, delete the older ones.

**Comment by Delgan** [comment]
Hi. ;)

It should be fairly easy using a custom `retention` function:

```python
import os
from loguru import logger

def retention(files):
    stats = [(file, os.stat(file)) for file in files]
    stats.sort(key=lambda s: -s[1].st_mtime)  # Sort files from newest to oldest
    while sum(s[1].st_size for s in stats) > 20*1000**3:
        file, _ = stats.pop()
        os.remove(file)
        
logger.add("file.log", retention=retention)
```

I don't think I can integrate it directly in Loguru though, because I want to make sure it exists a "typed equivalent" so that the parameter can be set programmatically. I mean, `rotation="20 GB"` is equivalent to `rotation=20*1000**3`. However, in the case of `retention`, an `int` is already an accepted parameter type.

**Comment by danlkv** [comment]
Thanks! Incidentally, I saw that other people ask for rotation both time and size based #241. Maybe adding a `rotation_size` and `retention_size` parameters would be a nice solution for both this use case and rotation size+time? If `rotation/retention='20 GB'`, set `rotation/retention_size` to 20GB and continue. If `rotation/retention='3 weeks'` one can still specify `*_size='20 GB'`. 

Adding type-sensitive `*_time` variants might also be nice and symmetric, and set `rotation/retention` behaviour to be this time/size flexible option, but when you want more control, just use `logger.add('file.log', retention_time='1 month', retention_size='20 GB', rotation_time='1day', rotation_size='100MB')`

**Comment by Delgan** [comment]
Thanks for your suggestion. The problem is that it could be confusing: what happens if `rotation="20 GB"` et `rotation_size="100MB"` are both specified?

I prefer to avoid this being even possible by design. More generally, I would like to keep the three simple parameters `rotation`, `retention` and `compression`. When the user needs advanced management (there will always be special cases), he can implements it though a custom function.

**Comment by stevennoyce** [comment]
What if `rotation` and `retention` could both accept either a string or a list of strings? If it were mentioned in the documentation that the first of any listed conditions to be reached will cause the action, then I feel this could be clear and quite simple to use, lowering the burden for a large number of use cases.

`rotation=['1 day', '100MB']` seems fairly clear, especially if the documentation is clear that it will be the condition that is reached first that causes the rotation, and `rotation=['100 MB', '20 GB']` would be strange but likewise clear that the smaller value would take precedence.

I love loguru and personally feel like this would make it even more awesome!

**Comment by Delgan** [comment]
@stevennoyce Sorry, I'm not sold on the idea... :sweat_smile:

I find the use case too uncommon to justify the addition.
