### ISSUE TITLE
How to give a unified id to sign related log

### ISSUE THREAD

**Issue by zhouxiaomao** [Delgan/loguru#43]
hi,I read through the readme and api reference but did not find out how to give a unified id to sign related log .

just like this
![default](https://user-images.githubusercontent.com/8357313/51667087-2edc8600-1ffa-11e9-860f-264787cddf0a.png)

with unified log_id I can parse and get related log generated by a http request or a func.

I have a producer-consumer model. When the consumer get data and start to work, i want to give a 
unified log_id ,and the  consumer will call many functions, i need the all process log have unified log_id.

**Comment by Delgan** [comment]
Hello @zhouxiaomao.

Indeed, the [`.bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) method seems the way to go.

How are you implementing this currently, using standard `logging`?

With Loguru, you could for example assign `self.logger = logger.bind(log_id=123456)` to your Consumer while initializing it.
Alternatively, this can be done in-line like: `logger.bind(log_id=request.id).info("Message")`.

Also, note that if you need to set a default value for everyone, you can use `logger.configure(extra={"log_id": 0})`.

Please, show me some code, maybe I could help you more precisely. 👍

**Comment by zhouxiaomao** [comment]
mycode just like this 

main.py
` with RedisQueue(xxx) as rq:
     data = rq.get()
     if data:
         do_it()
`

**Comment by Delgan** [comment]
Thanks for the code sample. How did you implement this with standard `logging`? Are you using [`LoggerAdaptater`](https://docs.python.org/3/library/logging.html#logging.LoggerAdapter)?

In my opinion, if you want to add context over your functions, you should encapsulate them into a class.

For example:

```python
class Task:

    def __init__(self, log_id):
        self.logger = logger.bind(log_id=log_id)

    def func1(self):
        self.logger.info("1111")

    def func2(self):
        self.logger.info("2222")

    def do_it(self):
        self.logger.info("xxxx")
```

And in `main.py`:

```python
if data:
    task = Task(123)
    task.do_it()
```

This avoids relying on a global state, and this is probably more future-proof (imagine you want to call your function from different places in different threads).

Otherwise, you can use [`.configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) before calling `do_it()`, this should work too.

**Comment by zhouxiaomao** [comment]
I do this with standard logging  through threading.currentThread().__dict__['log_id']， main thread and child thread all have own logger. thread-safe by default, but not multiprocess-safe especially in rotating.

thanks very much for your help.
.configure() maybe works better for me. I'll try that.

Thanks again for your patient explanation and replying.
