### ISSUE TITLE
Using loguru across multiple libraries

### ISSUE THREAD

**Issue by noahwaterfieldprice** [Delgan/loguru#432]
Firstly, thank you for this awesome package - it really makes life 100X easier (and makes logs look 100X cooler 😎). 

I am wondering what is the most "loguruthonic" way of using loguru across multiple libraries that may depend on one another. 

Specifically, lets say I have two libraries: a low level library `library0` and a higher level library `library1` that imports and uses `library0`. The following statements describe the situation:
- Both libraries use loguru to log information about what they are doing. 
- Both libraries need to apply (different) custom formatting/options to the logging.
- The logs in `library0` are not only useful when developing library0 but also for any other libraries that import library0 and use it. Hence, the logger in `library0` is not disabled.
- All logging is to stderr.

My main question is: How can I apply formatting/customisation options to the logger in `library0` without affecting the logger for `library1`? 

One way I can see to do this is to add a sink in `library0` with with `filter="library0"`. However, then you get every message twice, once on the core logger and once on the additional sink. I can get around this by calling `logger.remove(0)` removing the core logger but that also removes it for `library1` (and any other library that may import `library0`). Alternatively, rather than removing the core logger I could just configure it directly with `logger.configure` but again, this configures it for `library1` as well. If I then later reconfigure it in `library1`, this overwrites the configuration from `library0`, as you would expect, given they are the same `logger` instance.  Another option would be to deepcopy the logger in `library0` but to do this I have to remove the core logger sink which then removes it for `library1` as well.

I guess essentially I'm looking for a way to log messages in `library0` to a specific sink with custom formatting whilst avoiding the core logger and having this setup working in the same way whether `library0` is run directly or is imported and run in another package i.e. `library1`, 

Any help on this would be much appreciated!

**Comment by Delgan** [comment]
Hey, thanks for your feedback! Glad to know you enjoy Loguru!  :smiley: 

You're facing a very subtle problem. As you realized, Loguru is not meant to have "per library configuration" due to the use of one global `logger` object. The idea is that the library should not be responsible of managing the logging handlers (where to send logs and how to format them), this task is left to the user of the library.

I'm afraid it will be complicated to reconcile your requirements with Loguru's design.

Personally, I would try to make the logger configuration somehow optional. If `library0` can be used as is, hen I would condition the addition of the handler inside an `if` block. That way, the logs would be propagated to anyone using the library but would not affect the main application configuration, except if `library0` is itself the main application.

```python
from loguru import logger

def my_function():
    logger.info("Do something")

if __name__ == "__main__":
    logger.remove()
    logger.add(sys.stderr, format="[library0][{time}] {message}")
    my_function()
```

Is there an issue with such pattern?

If you really want to use different formats, you have to do it in the calling library by using a dynamic formatter that will adapt to the module. This means you probably need to extend the API of `library0` so it returns the expected format.

```python
def formatter(record):
    if "library0" in record["module"]:
        return library0.log_format()
    else:
        return default_format()

logger.add(sys.stderr, format=formatter)
```

**Comment by noahwaterfieldprice** [comment]
Thanks so much for your quick and detailed reply. It makes a lot of sense that it is the responsibility of `library1` to do the conditional formatting of logs coming from different sources rather than library0 forcing it on all libraries that depend on it. And, if `library0` wants to provide a pretty format to make `library1`'s life easier via some API, then that's just an added bonus.

Anyway, both solutions solve my problem so thanks a lot!
