### ISSUE TITLE
How to enable colours by default?

### ISSUE THREAD

**Issue by jaksiprejak** [Delgan/loguru#433]
What is the correct way to enable colours in log messages by default?

I'm doing it like so:

```python
def get_logger(level='INFO', colours=True):
    import sys
    from loguru import logger

    logger.remove()

    logger.add(
        sys.stderr,
        level=level,
    )

    # rest of logger set up

    if colours:
        logger = logger.opt(colors=True)

    return logger


logger = get_logger()

logger.info('this is <blue>blue</blue>')
```

But this is problematic due to the no-chaining-of-opts limitation. 

Is there a better way?

**Comment by Delgan** [comment]
Hi @jaksiprejak.

The `colors` option is not really intended to be used in a systematic way. It should be used sparingly, especially since it can negatively impact performance.

However, there is an example in the documentation explaining how it is possible to patch the `opt()` method so that it can be chained with `colors=True` by default. Can you tell me if this is what you want?

* [Preserving an `opt()` parameter for the whole module](https://loguru.readthedocs.io/en/stable/resources/recipes.html#preserving-an-opt-parameter-for-the-whole-module)
