### ISSUE TITLE
Logging destructors

### ISSUE THREAD

**Issue by tudorcebere** [Delgan/loguru#434]
Hi! I would like to ask if it's possible to log the status of an object in the destructor.

```
from loguru import logger

class Test:
    def __init__(self, logger):
        self._logger = logger

    def __del__(self):
        self._logger.info("Out of scope")
        print("Hi!")
        
obj = Test(logger)
```

The output of the above script is `Hi!`, but no logging.

**Comment by Delgan** [comment]
Hello. :)

It's due to [removal of existing handlers at program exit](https://github.com/Delgan/loguru/blob/68616485f4f0decb5fced36a16040f5e05e2842f/loguru/__init__.py#L33), which I guess occurs before final garbage collection. 

The simplest solution given the example is to manually call  `del obj`. Of course, I don't know how feasible it is in your actual situation. Alternatively, perhaps you can call [`gc.collect()`](https://docs.python.org/3/library/gc.html#gc.collect) before the end of your program to ensure that `__del__` is called before the final `logger.remove()`.

**Comment by tudorcebere** [comment]
Thank you @Delgan for the fast answer and the awesome library! :)

**Comment by Delgan** [comment]
No problem @tudorcebere. :+1: 

Can I close this ticket then?

**Comment by tudorcebere** [comment]
Yes, both of them are all good, I'll close them.
