### ISSUE TITLE
About the use of loguru in pyqt5

### ISSUE THREAD

**Issue by JunJie-zhang-o** [Delgan/loguru#440]
Recently, when I was using PyQT5, I thought of using the Loguru section for logging because there were no exceptions in PyQT5. However, I found that there were other problems with using the Loguru , which prevented my original program from performing properly。
I always take 1 positional argument but 2were given when decorating a slot function with @logger.catch.（The slot function takes one argument, self）
If possible, I would like to know how to use Loguru to log exceptions in PyQT5.

**Comment by Delgan** [comment]
Hey @JunJie-zhang-o.

I'm assuming you're referring to the problem happening with the following code for example:

```python
import sys
from loguru import logger
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel, QGridLayout, QWidget
from PyQt5.QtWidgets import QPushButton
from PyQt5.QtCore import QSize    

class MainWindow(QMainWindow):
    
    def __init__(self):
        QMainWindow.__init__(self)
        self.setWindowTitle("Test")
        pybutton = QPushButton('Click me', self)
        pybutton.clicked.connect(self.click)
    
    @logger.catch
    def click(self):
        logger.info("Button clicked")
        raise ValueError("Boom")

if __name__ == "__main__":
    logger.info("Starting application")
    app = QtWidgets.QApplication(sys.argv)
    mainWin = MainWindow()
    mainWin.show()
    sys.exit(app.exec_())
```
```bash
2021-05-16 17:08:02.540 | INFO     | __main__:<module>:22 - Starting application
2021-05-16 17:08:03.961 | ERROR    | __main__:<module>:26 - An error has been caught in function '<module>', process 'MainProcess' (466404), thread 'MainThread' (139859457836864):
Traceback (most recent call last):

> File "/home/delgan/Programmation/a.py", line 26, in <module>
    sys.exit(app.exec_())
    │   │    │   └ <built-in method exec_>
    │   │    └ <PyQt5.QtWidgets.QApplication object at 0x7f3391164040>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

TypeError: click() takes 1 positional argument but 2 were given
```

This is interesting. It seems while calling `pybutton.clicked.connect(self.click)`, PyQt5 will look at the signature of `self.click` method and later use it to dynamically decide which arguments should be passed to the slot when button is clicked at runtime.

While using `@logger.catch(wrapped)` the decorated function will look like `def func(*args, **kwargs)`.  Also, it seems [the `clicked` signal](https://doc.qt.io/qt-5/qabstractbutton.html#clicked) may contain the `checked` boolean value. Consequently, PyQt5 will probably try to call `wrapped(self, checked)` which results with an exception as the wrapped function (`click()`) only expect one unique `self` argument.

If `@logger.catch()` would not have altered the signature and returned something like `def func(self)`, then PyQt5 would have correctly inferred the expected argument and would have omit the `checked` parameter.

---

An easy workaround is to add `*` to the `click()` method so that possible additional arguments are ignored.

```python
    @logger.catch
    def click(self, *args):
        logger.info("Button clicked")
        raise ValueError("Boom")
```

Unfortunately, it seems complicated to fix this from Loguru side. It's difficult to exactly copy the signature of a wrapped function (that's why it's common practice to use `(*args, **kwargs)`). However, Loguru is using [`functools.update_wrapper()`](https://docs.python.org/3/library/functools.html) which is supposed to mitigate this problem. By using [`inspect.signature()`](https://docs.python.org/3/library/inspect.html#inspect.signature) it's possibly to correctly infer the expected arguments. I ignore how PyQt5 is retrieving the slot signature, it looks they're using another solution that doesn't interoperate well with decorated functions.

**Comment by JunJie-zhang-o** [comment]
I tried your way, it is very useful, thank you very much.
Expect loguru can become better, more people to bring convenience.

**Comment by Delgan** [comment]
Another possibility is to use the [`pyQtSlot()`](https://www.riverbankcomputing.com/static/Docs/PyQt5/signals_slots.html#the-pyqtslot-decorator) decorator.

```python
    @pyqtSlot()
    @logger.catch
    def click(self):
        logger.info("Button clicked")
        raise ValueError("Boom")
```

This is a limitation of PyQt (probably due to the C implementation), unfortunately I can't improve this much.

**Comment by Delgan** [comment]
Thanks for sharing @zhfkt.

It is indeed possibly to capture errors globally by overriding the [`sys.excepthook`](https://docs.python.org/3/library/sys.html#sys.excepthook) provided by Python.

```python
def logging_excepthook(type_, value, traceback):
    logger.opt(exception=(type_, value, traceback)).error("Unhandled Qt error")

sys.excepthook = logging_excepthook
```
