### ISSUE TITLE
Add easy access to setting the default level of logging

### ISSUE THREAD

**Issue by zackees** [Delgan/loguru#441]
I'm using your library for simple logging of a pypi project. I sprinkle in info, error, fatal as expected. But then I found out that I have to modify global state in a complex way in order to reset the level.

Please make this much easier. Something like log = foo(__name__, level='critical')

**Comment by Delgan** [comment]
I'm not sure what you mean by "default level". Do you mean changing the level of an existing handler?

It should be possible without being too complex by re-adding the handler or using a custom `filter`. See these examples in the documentation: [Changing the level of an existing handler](https://loguru.readthedocs.io/en/stable/resources/recipes.html#changing-the-level-of-an-existing-handler).

**Comment by zackees** [comment]
I just want to change the level of the current debugging instance, either globally, or locally.

Learning how to add a new handler just to change the logging level means that I went ahead and just created my own little simple logging mechanism instead.

**Comment by Delgan** [comment]
So if I understand correctly, you want to be able to easily reduce the log level temporarily, during a debugging session for example?

It is complicated to modify an existing handler afterwards due to Loguru's nature. However, it is possible to change the level dynamically if the handler is designed for it. Here is an example:

```python
if __name__ == "__main__":
    def debugging_filter(record):
        min_level = os.getenv("DEBUGGING_LEVEL", "INFO")
        return record["level"].no >= logger.level(min_level).no
    
    logger.remove(0)  # Remove default handler which has no filter
    logger.add(sys.stderr, filter=debugging_filter)
```

By default, only `"INFO"` and above logs will be emitted. If you need to see all logs, you can activate "debugging mode" by using `os.environ["DEBUGGING_LEVEL"] = "TRACE"`.

**Comment by zackees** [comment]
I want to be able to set the log level to error normally.

I want to be able to set the log level to INFO/DEBUGG with a --verbose flag I handle in my own logic:

if args.verbose:
  set_log_level(INFO)
  
  Something like that. Here is what I'm trying to use it for:
  
  https://github.com/zackees/transcribe-anything

**Comment by Delgan** [comment]
I see, thanks. In this case, you really need to `.remove()` the default handler and re-`add()` a new one with the expected level. It's not much more complicated than that.

```python
logger.remove()  # Remove all handlers added so far
level = "DEBUG" if args.verbose else "INFO"
logger.add(sys.stderr, level=level)
```

The default handler exists in order to simplify the initial development of a script.  Once an advanced configuration is required, it's quite normal to remove it and then add another one. This is the "right" way to do it because handlers are immutable in Loguru.

It's also possible to use [`logger.configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure):

```python
level = "DEBUG" if args.verbose else "INFO"
logger.configure(handlers=[{"sink": sys.stderr, "level": level}])
```

**Comment by zackees** [comment]
what about a logger.set_level which would take the current handler, modify the level and restore it.

**Comment by Delgan** [comment]
This would be possible, but it implies several considerations:

- There may exist several handlers which means we can't just update the "current" handler. It will be necessary to pass some kind of identifier to the function (like the number returned by `add()`).
- If a some point you decide to change the format of the default handler (for example), you will have to use `add()` anyway. So you might as well use the proper solution from the start. The `set_level()` looks like a substitute with less capabilities.
- If the `level` can be changed, some might ask that the `format` (and other arguments) can also be modified. This leads to the design of a new `update()` function and I'm not convinced it's worth it.

So I prefer to stay with the current solution of first removing the existing handler. This is not annoying enough to justify extending the `logger` API, in my opinion.
