### ISSUE TITLE
Intercept celery logging into loguru

### ISSUE THREAD

**Issue by gygabyte017** [Delgan/loguru#442]
Hi,

in my application I am successfully using loguru for logging. However, I'm using some external libraries, which are ignored by loguru and write directly to stdout.

So, I tried this solution: https://loguru.readthedocs.io/en/stable/overview.html#entirely-compatible-with-standard-logging "Want to intercept standard logging messages toward your Loguru sinks?" and it works great for almost all my external libraries.

Sadly it does not seem to work with Celery: messages like `[2021-05-17 15:44:58,686: INFO/MainProcess] Connected to amqp://****` are only written to stdout and not captured by loguru. Is there a way to capture Celery's messages as well?

**Comment by Delgan** [comment]
Hi!

It seems Celery automatically adds a handler from the standard `logging` library. That's why using `logging.basicConfig()` with an `InterceptHandler` does not work (because there exists an already configured handler, the logs are not propagated to the root logger and thus never sent to Loguru).

It looks like you can override the Celery logging configuration using the [`setup_logging`](https://docs.celeryproject.org/en/latest/userguide/signals.html#setup-logging) signal.

```python
from celery.signals import setup_logging

@setup_logging.connect
def setup_logging(*args, **kwargs):
     logging.basicConfig(handlers=[InterceptHandler()], level=0)
```

This is one possible workaround that should help you hopefully.

**Comment by gygabyte017** [comment]
Thank you so much it works great!!

**Comment by SidPatel-TH** [comment]
I followed [this](https://loguru.readthedocs.io/en/stable/overview.html#entirely-compatible-with-standard-logging) to intercept celery logs and forward to logguru logger. It works except the [startup banner](https://docs.celeryq.dev/en/stable/getting-started/next-steps.html#starting-the-worker). Is there a way to propagate the celery startup banner to loguru logs or am I not configuring it correctly?

**Comment by Delgan** [comment]
@SidPatel-TH I suppose the Celery banner is not passed to the standard logger. You would probably need to temporarily capture or redirect the `stdout` / `stderr` streams, possibly using [`contextlib.redirect_stderr()`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stderr) for example.

Note that since Celery itself does not write this banner in the logs, it is probably best not to capture it.
