### ISSUE TITLE
Why it generate after I shut down the programme

### ISSUE THREAD

**Issue by lee920217** [Delgan/loguru#443]
```
import time
from utils import timeparse

t = timeparse.TimeUtils()
class Logger(object):

    def __init__(self):
        pass

    @staticmethod
    def _log(level):
        logger.add(sink='./data/sunstrike/%s%s/%s/%s_%s.log' % (
            t.get_detailed('y'), t.get_detailed('m'), t.get_detailed('d'), level, t.get_detailed('h')),
            level=level.upper(), mode='a+')

    def log_error(self, info):
        self._log('error')
        logger.error({'level': 'error', 'content': info})

    def log_info(self, info):
        self._log('success')
        logger.success({'level': 'success', 'content': info})
```
it only generates log file after a shut down my programme, how could I generate it immediately

**Comment by Delgan** [comment]
You should call `logger.add()` only once. If you call `logger.add()` each time you want to log a message, this will initialize a new file continuously.

You can configured the `logger` inside your `__init__()` method and then using `logger.error()` or `logger.success()` will suffice.

Also, these functions are expecting a `str` message as argument. There is no need to pass a `dict` with the `level` key because the level is already part of the method name.

```python
import time
from utils import timeparse

t = timeparse.TimeUtils()
class Logger(object):

    def __init__(self):
        logger.add(sink='./data/sunstrike/%s%s/%s/%s_%s.log' % (
            t.get_detailed('y'), t.get_detailed('m'), t.get_detailed('d'), level, t.get_detailed('h')),
            level=level.upper(), mode='a+')

    def log_error(self, info):
        logger.error(info)

    def log_info(self, info):
        logger.success(info)

```

**Comment by lee920217** [comment]
> You should call `logger.add()` only once. If you call `logger.add()` each time you want to log a message, this will initialize a new file continuously.
> 
> You can configure the `logger` inside your `__init__()` method and then using `logger.error()` or `logger.success()` will suffice.
> 
> Also, these functions are expecting a `str` message as argument. There is no need to pass a `dict` with the `level` key because the level is already part of the method name.
> 
> ```python
> import time
> from utils import timeparse
> 
> t = timeparse.TimeUtils()
> class Logger(object):
> 
>     def __init__(self):
>         logger.add(sink='./data/sunstrike/%s%s/%s/%s_%s.log' % (
>             t.get_detailed('y'), t.get_detailed('m'), t.get_detailed('d'), level, t.get_detailed('h')),
>             level=level.upper(), mode='a+')
> 
>     def log_error(self, info):
>         logger.error(info)
> 
>     def log_info(self, info):
>         logger.success(info)
> ```

Hi Delgan:

Thanks for your reply.
I wanna build a keep-live programme and monitor is there an error exist. Then, I want the programme to generate the error_log when an error exists.  I use this way above, do you have any idea for solving this problem.

And I want to use the file structure like /yearmonth/date/{level}_hours.log, so rotation may not satisfy my requirements.
Do you have any example for this?

kr

Jiaqi

**Comment by Delgan** [comment]
> I wanna build a keep-live programme and monitor is there an error exist. Then, I want the programme to generate the error_log when an error exists. I use this way above, do you have any idea for solving this problem.

What should the `error_log` file contain? Do you need all logs since the beginning of your program? What should be the level of the logs contained in the file?

> And I want to use the file structure like /yearmonth/date/{level}_hours.log, so rotation may not satisfy my requirements.
Do you have any example for this?

Indeed, I did not notice that the `level` was part of the filename sorry. Maybe you can just add a boolean to your class and call `logger.add()` only once when the first `"ERROR"` message is logged?

**Comment by Delgan** [comment]
Closing as this seems resolved. Feel free to re-open it if you need further help.
