### ISSUE TITLE
how to avoid repeated log message when loguru is imported in multiple scripts

### ISSUE THREAD

**Issue by leolle** [Delgan/loguru#452]
I import loguru in multiple scripts and config like this,
```
from loguru import logger
import datetime
today = datetime.datetime.now().strftime("%Y-%m-%d")
logger.add("log/file_%s.log"%today, rotation="1 day")    # Once the file is too old, it's rotated

```
 now the log file record messages repeatedly like this:
```
2021-05-26 18:20:58.272 | DEBUG    | __main__:run_process:54 - 1. read prepared data
2021-05-26 18:20:58.272 | DEBUG    | __main__:run_process:54 - 1. read prepared data
2021-05-26 18:21:02.411 | DEBUG    | __main__:run_process:68 - 2. core process
2021-05-26 18:21:02.411 | DEBUG    | __main__:run_process:68 - 2. core process

```

**Comment by Delgan** [comment]
The `logger` object is global, its handlers are shared across all your modules. Consequently, when you call `logger.add()` in one module, it's also added for others modules.

Is the name of your file (`"log/file_%s.log"%today`) the same in all of your modules? Than, you should add it only once. Otherwise, that means you configured two handlers logging to the same file.

If you want to use one different file per module, you can add handlers twice and use `filter="mymodule"` so that logs coming from other modules are ignored.

**Comment by leolle** [comment]
thank you, the problem is solved.
