### ISSUE TITLE
Transforming the logged message to insert colour tags

### ISSUE THREAD

**Issue by eddyashton** [Delgan/loguru#457]
I'm trying to do something which may just not be possible in loguru, and trying to understand if I'm missing a solution/workaround, or if its simply not possible.

My app logs a bunch of HTTP requests, with some colour codes already embedded in those strings to distinguish status codes, HTTP method, etc.

So in the terminal output we see lines like:
![image](https://user-images.githubusercontent.com/6000239/120332763-f5f9fd80-c2e6-11eb-9d88-ade0a9ed1835.png)
and
![image](https://user-images.githubusercontent.com/6000239/120332816-027e5600-c2e7-11eb-9c6d-58ff8d3744a7.png)

These have colour codes in the logged message, ie we called something like `logger.info('<blue>POST</> <green>/gov/proposals...</>')`. This is correctly converted to an ANSI colour code before being displayed in the terminal.

What I'm now trying to do is separately highlight all of these (auto-generated) long hex IDs, by finding them with a regex and replacing them with a colour-tag-enclosed variant. For instance in the lines above, we'd replace `75ad00...` with `<red>75ad00...</>`. I did this with a custom callable `format`, which can do this transformation on `record["message"]`. This almost works - it gives me highlighted hex IDs, but loses all of the existing colouring _within_ `record["message"]`!

So the results are like this, losing the original colours of other parts of the line:
![image](https://user-images.githubusercontent.com/6000239/120335061-13c86200-c2e9-11eb-9111-76ab879d51fd.png)
and
![image](https://user-images.githubusercontent.com/6000239/120335112-1d51ca00-c2e9-11eb-967d-8883940acfc9.png)

After poking around a little, I've realised that `record["message"]` has already been `Colorizer`d by the time it reaches the formatter. I can add additional colour tags _around_ `record["message"]` in the final, formatted string (and these are processed correctly), but the `record["message"]` that I can see and transform has already been stripped of its existing colour tags. I don't see the string `<blue>POST</> <green>/gov/...`, just `POST /gov/...`. As far as I can tell, this is also true if I tried to rewrite the `message` in a callable patcher - the colourisation + stripping happens first:

https://github.com/Delgan/loguru/blob/68616485f4f0decb5fced36a16040f5e05e2842f/loguru/_logger.py#L1943-L1962

Hopefully that's all clear. In case it helps, here's the PR showing exactly the change I thought would work:

https://github.com/microsoft/CCF/pull/2633/commits/af6e5661884de95f4e3086fe4577e41b0ea8692b

My questions are:
- Is this possible with an existing option that I've not seen?
- Do you have an alternative pattern for intercepting every logging call and rewriting the `message`, while the colour codes are still intact? (We have a lot of logging call sites which may contain one of these IDs, so I'd prefer to do this rewrite inside the logger rather than at every call site)
- If neither of the above, is it possible to add `colored_message` to the `record`, so it can be patched/inspected like anything else?

And thanks for the great library!

**Comment by Delgan** [comment]
Hi @eddyashton.

Thanks for the detailed report. I am impressed with how far you dug into Loguru API. I'm sorry you didn't find a solution. Unfortunately, it is currently not possible to access the message containing the color tags. They have been removed due to another special case in the past (when messages are transmitted over the network and the receiver is not aware of `colors=True/False`, so by default the colors are removed).

I will definitely consider a way to access these values in the next version. This is an interesting use case that I hadn't thought of.

In the meantime, the only solution I see is to apply the color change in the sink instead of the formatter. One would have to detect and add ansi escape codes instead of using markup. It should work fine but obviously it's less convenient.

Also, just a note about the `formatter` in the commit you shared. The thing is that Loguru does not expect the returned string to be already formatted. Because Loguru will call `returned_format.format(**record)` it may cause subtle errors if the `returned_format` contains braces for example. Also, when Loguru will colorize le message, it will look for `<xxx>` tags. The `{function}` may be equal to `<module>` if the `logger` is used at the root level of the script, thus it will raise an exception because `<module>` is not a valid color tag.

If you want to modify the `message` in a custom `format` function, you can add it to the `extra` dict and return the string to be formatted like this:

```python
def formatter(record):
    # Highlight entity IDs in this message, then format-escape any braces in this (since we're about to call .format() on this string)
    record["extra"]["highlighted_message"] = entity_id_highlight(record["message"])
    return "<green>{time:HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{extra[highlighted_message]}</level>\n{exception}"
```

**Comment by eddyashton** [comment]
Thanks for the detailed response!

 I think we'll do this as a post-processing step in the sink, rather than in the formatter.

And thanks for the pointers on returning a format string, that explains the `\n{exception}` comment from the docs (I'd tried that, and got `None`s at the start of all of the lines because I was `.format`ing myself, but _returning_ the format-string fixes that.

Thanks for your help!
