### ISSUE TITLE
[QUESTION] Getting colored logs to work with Gooey

### ISSUE THREAD

**Issue by chwba** [Delgan/loguru#459]
https://github.com/chriskiehl/Gooey - If colorize is on or with loguru default configuration we get black output with rich_text_controls enabled - see https://github.com/chriskiehl/Gooey/blob/master/docs/Using-Richtext-Controls.md

If we manually configure colors like below, then we get colors in Gooeys output, how could I apply this custom configuration to get per level coloring back? Or do you have an idea, how we could patch loguru to make the default coloring work?

```python
from colored import fore, style
k_time = fore.GREEN + style.BOLD + "{time:YYYY-MM-DD HH:mm:ss.SSS} " + style.RESET
k_sep = fore.RED + style.BOLD + " | " + style.RESET
k_sep_pre_msg = fore.RED + style.BOLD + " - " + style.RESET
k_level = "<lvl>{level: <8}</lvl>"
k_name_line_func = fore.CYAN + style.BOLD + "{name}:{function}:{line}" + style.RESET
k_msg = fore.BLACK + "<lvl>{message}</lvl>" + style.RESET
log_format = k_time + k_sep + k_level + k_sep + k_name_line_func + k_sep_pre_msg + k_msg
# log_format = "<g>{time:YYYY-MM-DD HH:mm:ss.SSS}</> | <lvl>{level: <8}</> | <c>{name}</>:<c>{function}</>:<c>{line}</> - <lvl>{message}</lvl>"

log.add(sys.stderr, diagnose=True, backtrace=True, colorize=False, enqueue=True, format=log_format)
```
![image](https://user-images.githubusercontent.com/22568014/121056362-6a88dc80-c7be-11eb-9108-ec6e89c9413c.png)

PS: Is it correct to enable `enqueue` here? I put it because I had found, Gooey uses a subprocess to run the application, see here: https://github.com/chriskiehl/Gooey/blob/2e8eaeefa29a280c725e66a54ca61e73534bd516/gooey/gui/processor.py

PS2: I had already peaked at `new_level = logger.level("SNAKY", no=38, color="<yellow>", icon="🐍")` but the colorization doesn't work this way as I would need to have a per level format as in `k_level = fore.BLACK + style.BOLD + "<lvl>{level: <8}</lvl>" + style.RESET`

**Comment by Delgan** [comment]
Hey @chwba.

Currently, the level of your messages is not colorized because you specified `colorize=False`, so color tags like `<lvl>` are stripped from the format. Did you try with `colorize=True`? 

Alternatively, you probably can replace the Loguru color system by using a dynamic `format` function. That way, you will be able to stylize message using `fore` and `style` depending on the level value. Example:

```python
colors = {
    "INFO": fore.BLACK,
    "ERROR": fore.RED
}
def formatter(record):
    color = colors.get(record["level"].name, fore.WHITE)
    k_level = color + "{level: <8}" + style.RESET
    ...
    return k_time + k_sep + k_level + k_sep + k_name_line_func + k_sep_pre_msg + k_msg
```

About the `enqueue` argument: `subprocess` is different from `multiprocessing`. If your application is not run across several processes, then you probably don't need `enqueue=False`.

**Comment by chwba** [comment]
Thanks for another quick and helpful reply. How must I apply the format function to loguru in order to patch it properly?

**Comment by Delgan** [comment]
You can use the `formatter` in place of `log_format` as a parameter while you `add()` your handler:

```python
logger.add(sys.stderr, diagnose=True, backtrace=True, colorize=False, enqueue=True, format=formatter)
```

However, I guess I understood why you're not seeing the level colors... Loguru tries to be smart and will wrap the `stderr` stream with `colorama` if it detects you're using Windows. This is required, because Windows console does not support ansi colors by default. In this case, Loguru will strip ansi codes and will color the message using WinAPI calls.

Goey probably does not need that workaround and needs the ansi codes. You can try to disable automatic wrapping, by using a sink which isn't `stderr` like this:

```python
def sink(message):
    sys.stderr.write(message)

log.add(sink, diagnose=True, backtrace=True, colorize=True, enqueue=True, format=log_format)
```

**Comment by chwba** [comment]
The workaround with the custom sink doesn't work but the formatter one is just what I was looking for, thanks!
