### ISSUE TITLE
Dispatch different level messages to different log files

### ISSUE THREAD

**Issue by ArtyomW** [Delgan/loguru#46]
i should say that i faced logging task in the very first time, and i could be completely ignorant about whole concept of "severity levels" idea, so I beg your pardon for silliness of this question

code sample:
```python
from loguru import logger

LOG_FOLDER = '//var/log/will_crash/'

logger.add(LOG_FOLDER + 'info.log', level="INFO")
logger.add(LOG_FOLDER + 'error.log', level="ERROR")
logger.add(LOG_FOLDER + 'traceback.log', level="TRACE", backtrace=True)

def will_crash(var):
    # this should go to info.log
    logger.info('Here we go!')
    try:
        raise Exception
    except Exception:
        # this should go to error.log
        logger.error('crashed with var= ', var)

        # this should go to traceback.log
        logger.exception('Exception traceback  ↓ ↓ ↓')

var = 'foo'
will_crash(var)

```
console output seems perfect
```
2019-01-29 18:16:25.829 | INFO     | __main__:will_crash:13 - Here we go!
2019-01-29 18:16:25.830 | ERROR    | __main__:will_crash:18 - crashed with var = foo
2019-01-29 18:16:25.830 | ERROR    | __main__:will_crash:21 - Exception traceback  ↓ ↓ ↓
Traceback (most recent call last):

  File "/home/developer/Projects/test/test_logger_3.py", line 24, in <module>
    will_crash(var)
    │          └ 'foo'
    └ <function will_crash at 0x7f5a1f85fea0>

> File "/home/developer/Projects/test/test_logger_3.py", line 15, in will_crash
    raise Exception
          └ <class 'Exception'>

Exception
```

but then..

info.log 
```
2019-01-29 18:35:52.030 | INFO     | __main__:will_crash:13 - Here we go!
2019-01-29 18:35:52.030 | ERROR    | __main__:will_crash:18 - crashed with var = foo
2019-01-29 18:35:52.031 | ERROR    | __main__:will_crash:21 - Exception traceback  ↓ ↓ ↓
Traceback (most recent call last):

  File "/home/developer/Projects/test/test_logger_3.py", line 24, in <module>
    will_crash(var)
    │          └ 'foo'
    └ <function will_crash at 0x7f6c9b4cbea0>

> File "/home/developer/Projects/test/test_logger_3.py", line 15, in will_crash
    raise Exception
          └ <class 'Exception'>

Exception
```

i'm aware why traceback.log and error.log get same output, they got the same level: 'ERROR' 
but why info.log got 'ERROR' level messages, isn't it completely wrong?

I mean, why levels aren't separated but stacked upon each other
if i'll always got full traceback in my info.log i'll not be able to read anything helpful

And if answer would be "because that's exactly how levels supposed to work!", how i could reach "channels"-like behaviour 

when logger.%level_name%('message') dispatch log to file which linked here 
-> logger.add(LOG_FOLDER + '%level_name%.log', level="%LEVEL_NAME%")

P.S. i read readme and docs several times, but still can't get this done

**Comment by Delgan** [comment]
Hello @ArtyomW. Please, ask as many questions as you want, there is no such thing as a silly question! 🙂 

The concept of severity is in the core of many logging libraries. If you're not familiar with logging in Python, maybe you should take a quick look at [the official documentation](https://docs.python.org/3/howto/logging.html) (or search for another good introduction to logging on some blog online).

Basically, levels are used to manage granularity of your logs. Messages are not partitioned based on their severity, the severity is used to filter out the less important ones. So, if you add an handler with a severity of "INFO", every message which is logged with at least an "INFO" severity will be handled, but "DEBUG" and "TRACE" messages will be ignored.

Imagine an end user running your application. You don't want to bother him with "DEBUG" messages. However, if something goes wrong, you may want him to know. And if something went wrong, as a developer you may be interested by the "DEBUG" logs. Thus, you can configure your logger so that "INFO" and higher messages go to `stdout` (for the user), and so that "DEBUG" and higher messages go to `"debug_file.log"` (for the developer). If there is an "ERROR" message, both your user and the developer will be warned.

If you want some "channels" to select which log message go to which handler, you should use the `filter` parameter. For example, to log "INFO" and only "INFO" messages to the `"info.log"` file:

```python
logger.add(LOG_FOLDER + 'info.log', filter=lambda record: record["level"].name == "INFO")
```

This can also be combined with the [`.bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) method, for example:

```python
logger.add("special.log", filter=lambda record: "special" in record["extra"])
special_logger = logger.bind(special=True)
logger.info("Don't go to special.log")
special_logger.info("Go to special.log")
```

Hope that's help you. Ohterwise, ask me for more details. :wink:

**Comment by ArtyomW** [comment]
Thank you! @Delgan :blush:
Binding and filtering is work like a charm, that's exactly what i've needed!

```python
from loguru import logger

LOG_FOLDER = '//var/log/'

#all logger.info('message') goes strictly to info.log
info_filter = lambda record: record["level"].name == "INFO"
logger.add(LOG_FOLDER + 'info.log', filter=info_filter)

#all logger.error('message') goes strictly to error.log, traceback is not shown due to the second condition
error_filter = lambda record: record["level"].name == "ERROR" and not "traceback" in record["extra"]
logger.add(LOG_FOLDER + 'error.log', filter=error_filter)

#here we make traceback separate from all other 'ERROR' level messages, goes strictly to traceback.log
traceback_filter = lambda record: "traceback" in record["extra"] and record["level"].name == "ERROR"
logger.add(LOG_FOLDER + 'traceback.log', filter=traceback_filter)
traceback_logger = logger.bind(traceback=True)

def will_crash(var):
    # this should go to info.log
    logger.info('Here we go!')
    try:
        raise Exception
    except Exception:
        # this should go to error.log
        logger.error(f'crashed with var = {var}')

        # this should go to traceback.log
        traceback_logger.exception('current Exception traceback  ↓ ↓ ↓')

var = 'foo'
will_crash(var)

```
info.log                                                                                      
`2019-01-30 12:48:37.514 | INFO     | __main__:will_crash:22 - Here we go!
`
error.log
`2019-01-30 12:48:37.514 | ERROR    | __main__:will_crash:27 - crashed with var = foo
`
traceback.log
```
2019-01-30 12:48:37.514 | ERROR    | __main__:will_crash:30 - current Exception traceback  ↓ ↓ ↓
Traceback (most recent call last):

  File "/home/developer/Projects/test/test_logger_3.py", line 33, in <module>
    will_crash(var)
    │          └ 'foo'
    └ <function will_crash at 0x7fd6816e7158>

> File "/home/developer/Projects/test/test_logger_3.py", line 24, in will_crash
    raise Exception
          └ <class 'Exception'>

Exception
```


and now i'm realized how to use this technique with decorator

```python
@traceback_logger.catch
def will_crash_but_still_log(var):
    raise Exception
```

Thank you for explanation, imho you should update readme with 'filter=labmda' snippet, it's gave you unlimited power :sunglasses: and worth to be mentioned

**Comment by Delgan** [comment]
Glad you figured out how to configure Loguru as you wish. 👍 

> Thank you for explanation, imho you should update readme with 'filter=labmda' snippet, it's gave you unlimited power 😎 and worth to be mentioned

Thanks for the suggestion, you are right, I will add a note about this technique then!

**Comment by ishritam** [comment]
Hey @Delgan ,
I tried using the script and the logs are now saved as per their levels, but can you let me know why my logs are getting duplicated.

`2021-01-26 at 15:15:49 | INFO | Parameters taken from config file successfully!`
`2021-01-26 at 15:15:49 | INFO | Parameters taken from config file successfully!`
`2021-01-26 at 15:16:10 | INFO | Parquet output has been made for pjrData.txt`
`2021-01-26 at 15:16:10 | INFO | Parquet output has been made for pjrData.txt`
