### ISSUE TITLE
How to make coloured logs in loguru

### ISSUE THREAD

**Issue by iamharikrishnank** [Delgan/loguru#464]

**Comment by ThibaultLemaire** [comment]
From [the docs](https://loguru.readthedocs.io/en/stable/overview.html#pretty-logging-with-colors):

> Loguru automatically adds colors to your logs if your terminal is compatible. You can define your favorite style by using markup tags in the sink format.

**Comment by iamharikrishnank** [comment]
But I am writing to a file not on terminal

**Comment by ThibaultLemaire** [comment]
Then colors will depend on the program you use to read that file

**Comment by Delgan** [comment]
As @ThibaultLemaire pointed out, Loguru tries to enable or disable colors based on the sink type. Files can't display colors, because text colorization is a feature provided usually by your terminal. The colors are displayed using special [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code). You can force them to be written to your file by specifying `colorize=True` when adding your file sink. However, this is not very portable because most text editor won't convert them to actual colors as a terminal does.
