### ISSUE TITLE
Pytest and caplog doesn't work if InterceptHandler exists

### ISSUE THREAD

**Issue by davidolrik** [Delgan/loguru#474]
I would like route all logs through loguru and configure them as I see fit, and for that I have created an `InterceptHandler` as descriped [here](https://loguru.readthedocs.io/en/stable/overview.html?highlight=intercepthandler#entirely-compatible-with-standard-logging).
I also want to test the output of some of my logs via the caplog trick described [here](https://loguru.readthedocs.io/en/stable/resources/migration.html?highlight=pytest#making-things-work-with-pytest-and-caplog).

It seems that I can't have both at the same time, as it creates a hanging loop.

Is there another way to test the contents of the logs when using an `InterceptHandler` ?

**Comment by Delgan** [comment]
Hi @davidolrik.

Do you have a snippet to share so that I can try to reproduce the issue and investigate it?

**Comment by kxjko** [comment]
Hi @Delgan 
I had a similar problem. I have this code:
```python
# -*- coding: utf-8 -*-
import logging

from loguru import logger


class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(
            level, record.getMessage())


def print_log():
    logging.basicConfig(handlers=[InterceptHandler()], level=logging.NOTSET)

    logging.debug('debug!')
    logging.info('info!')
    logging.warning('warning!')
    logging.error('error!')


if __name__ == '__main__':
    print_log()

```
When I run this script, it works fine. The log will be printed correctly, like this:
![image](https://user-images.githubusercontent.com/38339940/129000423-63646df0-5acd-4ddb-afdb-f085827befb9.png)


But, when I use pytest, no log will be printed. These is the pytest code:
```python
def test_log():
    print_log()
```
And these is the result:
![image](https://user-images.githubusercontent.com/38339940/129001287-db0c1fb8-93bf-49b9-8b66-fa91081c8f95.png)

**Comment by Delgan** [comment]
@kxjko This might be because `pytest` automatically capture the output and won't display it by default.
See this StackOverflow question: [How can I see normal print output created during pytest run?](https://stackoverflow.com/questions/14405063/how-can-i-see-normal-print-output-created-during-pytest-run).

Can you try to run Pytest with the `-s` option please?

**Comment by kxjko** [comment]
@Delgan Tank you for replying to me.  When use `-s`, it only print `logger.debug`, but not print `logging.debug`. This is my question. Some libs I used use `logging` to print log, but nothing will be printed when I use `pytest` to test them.
```python
logging.basicConfig(handlers=[InterceptHandler()], level=logging.NOTSET)
logger.debug('logger.debug')
logging.debug('debug!')
logging.info('info!')
logging.warning('warning!')
logging.error('error!')
```
![image](https://user-images.githubusercontent.com/38339940/129295463-80a28506-25bf-40ef-b091-3f61647057c1.png)

**Comment by Delgan** [comment]
Hey @kxjko, it looks that `pytest` adds it own handlers to the root logger before executing the `test_log()` function. The problem is that [`logging.basicConfig()`](https://docs.python.org/3/library/logging.html#logging.basicConfig) won't do anything if there already exists handlers attached to the root logger.

You can try to use the `force=True` parameter or alternatively, manually configure the root logger like this in place of `basicConfig()`:

```python
logging.getLogger().addHandler(InterceptHandler())
logging.getLogger().setLevel(logging.NOTSET)
```

**Comment by kxjko** [comment]
Hello @Delgan , did you mean that?
![image](https://user-images.githubusercontent.com/38339940/129501071-ffa7f490-99bc-4d79-8c39-be0aea2fc3fc.png)
It seems to show the same result. The `logging` log also won't be printed.

**Comment by kxjko** [comment]
@Delgan It wroks ! Thank you !

**Comment by mehd-io** [comment]
@Delgan the question from @kxjko doesn't actually related to the initial issue point it by @davidolrik. I run into the same hanging loop issue when using an `InterceptHandler` and the `caplog` fixture provided in the doc :/ . Here are some snippets to reproduce it : 

`conftest.py`
```python
import logging
import pytest
from _pytest.logging import caplog as _caplog
from loguru import logger

@pytest.fixture
def caplog(_caplog):
    class PropogateHandler(logging.Handler):
        def emit(self, record):
            logging.getLogger(record.name).handle(record)

    handler_id = logger.add(PropogateHandler(), format="{message} {extra}")
    yield _caplog
    logger.remove(handler_id)
```

`logging_setup.py`
```python
"""Configure handlers and formats for application loggers."""
import logging
import os
import sys

from loguru import logger

LOG_LEVEL = logging.getLevelName(os.environ.get("LOG_LEVEL", "DEBUG"))
JSON_LOGS = True if os.environ.get("JSON_LOGS", "0") == "1" else False


class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())


def init_logging():
    # intercept everything at the root logger
    logging.root.handlers = [InterceptHandler()]
    logging.root.setLevel(LOG_LEVEL)

    # remove every other logger's handlers
    # and propagate to root logger
    for name in logging.root.manager.loggerDict.keys():
        logging.getLogger(name).handlers = []
        logging.getLogger(name).propagate = True

    # configure loguru
    logger.configure(handlers=[{"sink": sys.stdout, "serialize": JSON_LOGS, "backtrace": False, "diagnose": False}])

```

and the test file  `test_caplog.py` : 
```python
from loguru import logger

from logging_setup import init_logging

init_logging()


def some_func():
    logger.info("Oh no!")

def test_some_func_logs_warning(caplog):
    some_func()
    assert "Oh no!" in caplog.text
```

When running `pytest test_caplog` its hangging.

**Comment by Delgan** [comment]
Thanks for the reproducible example, @mehd-io! It's all clear now.

Basically, Loguru's handlers are made thread-safe by using a `Lock` to protect concurrent access of sinks. While processing a log message, the handler first acquires the `Lock` and release it once the message is logged. If another message tries to be logged at the same time, it won't be handled and will wait until the `Lock` is released.

You're facing a dead-lock due to recursive call of `logger.log()`. It is very similar to the following scenario:

```python
from loguru import logger

def my_custom_sink(message):
    logger.debug("Processing the message...")
    print(message, end="")

logger.add(my_custom_sink)

logger.info("Hanging...")
```

The program is hanging because the `debug()` call is waiting for the `Lock` acquired by `info()` to be released, which never happens because `my_custom_sink()` can't terminate.

In your case, an `InterceptHandler()` is attached to the standard root `logger`. Every message logged using the standard `logging` library will also be processed by Loguru added handlers. That's fine, but there's also a `PropagateHandler()` which causes every Loguru message to be propagated to standard `logging`.

Consequently, when `logger.info()` is used, the `Lock` of the `PropagateHandler()` is acquired, then the log message is sent to the logger returned by `logging.getLogger(record.name)` which itself call the `emit()` function of the `InterceptHandler()`. The latter will tries to call `logger.log()` but will hang forever because the `Lock` is still not released.

If this wasn't hanging you would face infinite recursion anyway. 

I never realized it, but `InterceptHandler` and `PropagateHandler` don't mix well.

The solution is to find a trick so that the `InterceptHandler` does not process the messages generated by the `PropagateHandler`. I can suggest the following updated handlers:

```python
class PropogateHandler(logging.Handler):
        def emit(self, record):
            record.from_loguru = True
            logging.getLogger(record.name).handle(record)

class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Ignore messages from PropagateHandler to avoid hanging
        if getattr(record, "from_loguru", False):
            return

        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())
```

I'm not entirely satisfied with this solution, but this is the best I've found so far.

**Comment by mehd-io** [comment]
Thx @Delgan for such prompt and detailed answer :) Will try this!

**Comment by mehd-io** [comment]
I confirm that the workaround works 🎉 , thanks @Delgan for the awesome support & library 🙌

**Comment by davidolrik** [comment]
@mehd-io Thanks for providing an example 💪🏽 - I've been totally swamped and didn't have time to do it my self. 

@Delgan Thanks for the workaround! ✨❤️✨

**Comment by phillipuniverse** [comment]
@Delgan I also ran into the deadlock issue with `InterceptHandler` and adding `caplog` compatibility with `PropagateHandler`.

I confirmed that [your workaround](https://github.com/Delgan/loguru/issues/474#issuecomment-926705136) does work correctly. Although as you said, it's not very satisfying because you have to modify the `InterceptHandler` (non-test code) to make it work with something that only exists in test code. Also, you end up with double-logging in your log test output.

I did some additional digging and found what I think is a better solution which completely avoids the deadlock problem:

```python
@pytest.fixture
def caplog(_caplog: LogCaptureFixture):
    """
    Emitting logs from loguru's logger.log means that they will not show up in caplog which only works with Python standard logging. This adds the same `LogCaptureHandler` being used by caplog to hook into loguru
    """

    handler_id = logger.add(_caplog.handler, format="{message}")
    yield _caplog
    logger.remove(handler_id)
```

IMO this is a more sustainable solution than the previous workaround. If you agree then it might be worth updating the caplog documentation to use this method instead of the `PropagateHandler` method. I can open a PR to update those docs.

Thanks!

**Comment by Delgan** [comment]
Hey @phillipuniverse, sorry for the late feedback.

I just tested your proposed workaround and it indeed works like a charm! I wasn't aware we could access `caplog.handler` this way. This looks like a very suitable solution. If your offer for a PR still stands, it is very welcome (otherwise I would do it myself, no problem)! :grin:

For reference, the initial implementation using `PropagateHandler` came from #59.

**Comment by phillipuniverse** [comment]
@Delgan done in #572!
