### ISSUE TITLE
Write logs in batch when under heavy load?

### ISSUE THREAD

**Issue by NLebedev** [Delgan/loguru#476]
Hello,

First of all, thanks for such an amazing work you've done with this project.

My team and I have ran into the following problem:
Our app can be under extremely heavy load sometimes and we've found that writing log messages to file is one of the bottlenecks of our application.
We are using asyncio and have `enqueue` flag set to `True`. 
During peak times we need to log a lot of events (it can be as high as 1-2k messages within a second). When this happens, we encounter high CPU usage which impacts our application performance. The CPU usage is not affected as much when we stop writing messages during these peak times.

We were wondering, could it be possible to write messages to a file in a batch, let's say every second? This way we would only put maximum one task to asyncio event loop each second and possibly avoid some costly calls to file I/O.

Also, if you have any other possible suggestions on how to improve performance in this situation, that would be great. 

Thanks in advance for your help!

**Comment by Delgan** [comment]
Hi.

I suppose using `asyncio` doesn't matter much, since `enqueue=True` forces messages to be logged from a background thread (in which there is no event loop).

There is currently no built-in way to write messages in a batch. You'll have to implement your own handler like the following for example:

```python
class BatchedFileHandler:

    def __init__(self, filepath, mode="a"):
        self.file = open(filepath, mode=mode)
        self.batch = []

    def write(self, message):
        self.batch.append(message)
        if len(self.batch) > 100:
            self.file.write("".join(self.batch))
            self.batch.clear()

handler = BatchedFileHandler("test.log")
logger.add(handler, enqueue=True)
```

This should work well with the downside that you'll need to implement others file-sink features by yourself (like rotation or compression).

Maybe another possibility is to make use of standard [`MemoryHandler`](https://docs.python.org/3/library/logging.handlers.html#memoryhandler) (since Loguru supports standard handlers). I've seen a few comments suggesting to use it for batched logging, but I didn't investigate it further.

**Comment by ydf0509** [comment]
> Hello,
> 
> First of all, thanks for such an amazing work you've done with this project.
> 
> My team and I have ran into the following problem:
> Our app can be under extremely heavy load sometimes and we've found that writing log messages to file is one of the bottlenecks of our application.
> We are using asyncio and have `enqueue` flag set to `True`.
> During peak times we need to log a lot of events (it can be as high as 1-2k messages within a second). When this happens, we encounter high CPU usage which impacts our application performance. The CPU usage is not affected as much when we stop writing messages during these peak times.
> 
> We were wondering, could it be possible to write messages to a file in a batch, let's say every second? This way we would only put maximum one task to asyncio event loop each second and possibly avoid some costly calls to file I/O.
> 
> Also, if you have any other possible suggestions on how to improve performance in this situation, that would be great.
> 
> Thanks in advance for your help!

nb_log batch write file log,fast 400% than loguru when write log.   pip install nb_log

**Comment by Delgan** [comment]
Closing this issue as I think I answered the initial question. Feel free to re-open otherwise.
