### ISSUE TITLE
Something error in loguru stub file

### ISSUE THREAD

**Issue by yanyongyu** [Delgan/loguru#480]
`loguru.Logger` is imported as `_Logger`, `Logger` class cannot accessed from `loguru` top level module actually.

This will cause static type checking failed or `ImportError` like `"loguru.Logger" is incompatible with "loguru._logger.Logger"`

https://github.com/Delgan/loguru/blob/5e754dd4239f4703eec007c4efaefbbfe272132b/loguru/__init__.pyi#L226

https://github.com/Delgan/loguru/blob/5e754dd4239f4703eec007c4efaefbbfe272132b/loguru/__init__.py#L11

**Comment by Delgan** [comment]
Hi @yanyongyu.

The concrete `_Logger` is not meant to be imported nor used for type hinting.

You have to use postponed evaluation like a specific `__future__` import:

```python
from __future__ import annotations

def some_function(logger: loguru.Logger):
    pass
```

Alternatively, one can use a string and it works just fine:

```python
def some_function(logger: "loguru.Logger"):
    pass
```

**Comment by yanyongyu** [comment]
Thanks for your answer, but, in some case like `sphinx` it will check postponed annotation and import it (i dont known why), so i get an`ImportError` when i use `logger: "loguru.Logger"`. API Document fail to build.

Error occurred in latest `sphinx 4.1.x`

**Comment by Delgan** [comment]
That's unfortunate. :grimacing: 

I tested it very briefly but wasn't able to reproduce the error. The documentation was built correctly using Sphinx 4.1.2. Can you please share an example repository that makes it easy to reproduce the issue?

Unfortunately, the problem seems to come more from Sphinx than from Loguru. Usuing postponed annotation combined with a stub file should be valid.

**Comment by yanyongyu** [comment]
I create an example repo for this -> [link](https://github.com/yanyongyu/loguru-issue480)

Following step will cause the error:

1. Define a variable with type: `"loguru.Logger"`
2. Build the api doc using `sphinx.ext.autodoc` for the module contains the variable

Code:

https://github.com/yanyongyu/loguru-issue480/blob/9fb80ee3442928922116278dc136201454eb2771/example/__init__.py#L3-L4

Dependency:

- `sphinx: 4.1.2`
- `loguru: 0.5.3`

Error Detail:

```
reading sources... [ 33%] example

Exception occurred:
  File "<string>", line 1, in <module>
AttributeError: module 'loguru' has no attribute 'Logger'
The full traceback has been saved in /tmp/sphinx-err-fkba50q4.log, if you want to report the issue to the developers.
```

Full building log by github action:

https://github.com/yanyongyu/loguru-issue480/runs/3177938743

**Comment by yanyongyu** [comment]
In my opinion, stub file is used to describe a module with type hints but without runtime logic. All vars, functions and classes etc in the stub file are "module exports", as mentioned in official document `PEP484` and `mypy` stub file guide. They should be "importable" from the module directly.

**Comment by yanyongyu** [comment]
> I tested it very briefly but wasn't able to reproduce the error. The documentation was built correctly using Sphinx 4.1.2. Can you please share an example repository that makes it easy to reproduce the issue?

loguru docs can be built with `sphinx` because of using direct import from source file:

https://github.com/Delgan/loguru/blob/5e754dd4239f4703eec007c4efaefbbfe272132b/docs/api.rst#L14

**Comment by Delgan** [comment]
Thank a lot for taking the time to create a repository demonstrating the error!

I noticed that if the type hint is part of a function signature instead of being a global variable, building docs works fine. Can we consider that this is a Sphinx bug?

About stub files, I think it is acceptable to use them as I do. I understand the point of having access to the type at runtime, but in the case of Loguru, I prefer to avoid that. The user doesn't have to instantiate a `logger` himself so I don't want to expose the `Logger` class. Also, there are [other types](https://loguru.readthedocs.io/en/stable/api/type_hints.html) like `Message` that can be used for annotation but don't actually exist. I don't want to complicate the runtime API with extra classes. Actually, there exists a workaround [in `mypy` documentation](https://mypy.readthedocs.io/en/latest/runtime_troubles.html#using-types-defined-in-stubs-but-not-at-runtime) about not importable types.

**Comment by yanyongyu** [comment]
Thanks for answerring! It may be a `sphinx autodoc` bug, i will check the code in autodoc.

I known `import Logger as _Logger` means you dont want to export the `Logger` class, but, my IDE will auto suggest it when typing `loguru.`  because it exists in the stub file.

It may be a confusion. Or rename the class in stub file like `_Logger`?

**Comment by yanyongyu** [comment]
About `Sphinx autodoc`:

`autodoc` do not check the annotation in module level function:
https://github.com/sphinx-doc/sphinx/blob/f59026865a8c658acbc6d5690c146f4be0851854/sphinx/ext/autodoc/__init__.py#L1313-L1318

but checks the annotation for module level data using `typing.get_type_hints`:
https://github.com/sphinx-doc/sphinx/blob/f59026865a8c658acbc6d5690c146f4be0851854/sphinx/ext/autodoc/__init__.py#L1981-L2005

and i find a monkey patch:

## Solution

```python
from typing import TYPE_CHECKING

import loguru

if TYPE_CHECKING:
	from loguru import Logger

my_logger: "Logger" = loguru.logger
```

both `static type checking` and `sphinx autodoc` report 0 errors!

**Comment by Delgan** [comment]
Congratulations on your success in understanding and finding a solution to the problem.

Based on your investigations, I added the following to Sphinx [`get_type_hints()`](https://github.com/sphinx-doc/sphinx/blob/f59026865a8c658acbc6d5690c146f4be0851854/sphinx/util/typing.py#L76) function:

```python
except AttributeError:
    return safe_getattr(obj, '__annotations__', {})
```

It seems to build the docs just fine. Do you think it's relevant to propose such addition to Sphinx developers?

I also noticed that VSCode suggest `loguru.Logger` which is confusing. Unfortunately, I don't think we can find a solution. I guess the IDE isn't powerful enough to make the difference between "runtime context" and "type hints" (before or after `:` while declaring a variable). Renaming `Logger` to `_Logger` would prevent users to use the type for annotating their functions, so I can't do that.

**Comment by yanyongyu** [comment]
Add `safe_getattr` when `AttributeError` to `get_type_hints` could be fine. I will make a pull request to sphinx and close this later.
