### ISSUE TITLE
Update Relase & C Implementation

### ISSUE THREAD

**Issue by amitbcp** [Delgan/loguru#484]
Thank @Delgan for this amazing project.

Can we please create a new release as there has been many commits since last year in the main branch & some PRs as well ?

Also, the README mentions about C implementation. Is it still on the cards or dropped ?

**Comment by Delgan** [comment]
Hello!

I didn't realize that almost a year had passed since the last release...Time flies.
However, as you can see [in the changelog](https://github.com/Delgan/loguru/blob/master/CHANGELOG.rst#unreleased), there have not yet been any notable changes that deserve a release in my opinion.
There are some pending improvements and bugfixes (potentially breaking) that I would like to implement first for the 0.6.0 release.
I can't give you a release date though.

About the C implementation, it's still planned, but again I don't know when. This is comment I left recently: https://github.com/Delgan/loguru/issues/479#issuecomment-886221676

**Comment by amitbcp** [comment]
Thanks @Delgan  !
Sorry I didn't check the change log earlier and just saw the commit history : https://github.com/Delgan/loguru/commits/master

It made me wonder should I clone and build a local 0.5.4 version or continue using the public released version. As there were some minor fixes and cleanup. I will leave the call on that for you . 
Thanks again !!
