### ISSUE TITLE
Add functionality is not working

### ISSUE THREAD

**Issue by amitbcp** [Delgan/loguru#485]
Hi,
This is the most weird thing happening. The code snippet is :

```
import sys
from loguru import logger


# logger.remove()
logger.add(sys.stdout, format="{time} {level} {message}", filter="my_module", level="INFO")
logger.info("Logging 'DEBUG' messages too")
```

When I uncomment ```logger.remove``` and run this from my terminal, I don't get any output on my terminal. 

While with the default I get the output. Also adding any customisation via add is not resulting in any change

**Comment by Delgan** [comment]
Hi.

This is probably because of the `filter` parameter. It selects messages to be logged based on the `name` attribute of the created [`record`](https://loguru.readthedocs.io/en/stable/api/logger.html#record). The `name` value is retrieved using the `__name__` value of the module calling the logging function. In you case, the  `__name__` is equals to [`__main__`](https://docs.python.org/3/library/__main__.html) because it's the top-level module when you're running your script. Consequently, logs are filtered out and nothing is printed on `sys.stdout`.

**Comment by amitbcp** [comment]
Ahh, now it makes sense and I am able to play around it. Thanks
