### ISSUE TITLE
Logging of default levels from built in logging

### ISSUE THREAD

**Issue by BLooperZ** [Delgan/loguru#490]
Hi, and thank you for making this library.

I have noticed some issue with logging with builtin log levels directly.
logging of default builtin levels result in level name missing:

example:
```python
>>> from loguru import logger
>>> import logging
>>> logger.log(logging.INFO, 'something')
2021-08-22 11:09:57.518 | Level 20 | __main__:<module>:1 - something
```

can be mitigated by example (I guess there are also other ways to do this):
```python
>>> logger.log(logging.getLevelName(logging.INFO), 'something')
2021-08-22 11:10:24.015 | INFO     | __main__:<module>:1 - something
```

I think it makes sense to have the name resolving inside the log function.
allowing this library and builtin logging module integrate more seamlessly.

(e.g function may accept logger and level, and it will work with both with the same output)
example:
```python
def log_something(logger, level=logging.INFO):
    logger.log(level, 'something')
```
could work with both standard library logging and loguru logger

Thanks again

**Comment by Delgan** [comment]
Hi.

I'm quoting a comment I left on another issue (https://github.com/Delgan/loguru/issues/209#issuecomment-581570613):

> The way the levels work is indeed slightly different between `logging` and `loguru`. Using `loguru`, the he severity level is not mapped against any level name, bu this is made on purpose.
>
> A level is basically a `namedtuple`:
> 
> ```python
> Level(name='INFO', no=20, color='<bold>', icon='ℹ️')
> ```
> 
> I think what should be used to identify a level is its **name**, not its **number**. It's perfectly valid to create a custom level while another one exist with the same `no`, this shall not create any conflict (which would be the case if the `no` was also mapped to the level).

Basically, multiple levels can share the same severity. The `logging.INFO` is just the `20` integer. While logging a message using an integer, Loguru won't be able to reliably find the corresponding level because there might be several candidates with `no=20`.

That's why if you want the level to correctly appear in the logs, you must use its identifier, which is its name.
