### ISSUE TITLE
Can I create a completely separate logger?

### ISSUE THREAD

**Issue by ciresnave** [Delgan/loguru#505]
I see from the docs that it is recommended to deep copy logger to create a new logger.  I was wondering if, instead of that, there was a way I could generate a completely new logger from scratch?  For example, I see in the __init__.py that logger is an instance of Logger.  Would creating a new instance of Logger create a whole new logger?  Some of the logs I will be creating will contain confidential information so completely separate loggers right from the start seems like it would lessen the chances of data leakage from one to another.  Thoughts?

**Comment by ciresnave** [comment]
One of my other concerns with doing a deep copy of logger is that the docs recommend removing handlers from logger before doing the deep copy.  Since what I'm working on is a module I plan to distribute to others, I don't want to remove handlers from logger that may have been put in place by code that wasn't part of my module.  Does that make sense?  Another possible way around that might be to store a copy of all current handlers, remove them from logger, do a deep copy, and then restore the original handlers to logger.  Is that possible?

**Comment by Delgan** [comment]
Hi.

As you understood, currently the only way to create a separate logger is to deep-copy the `logger` object. I advise against importing and instantiating a `Logger` manually because it's not part of the public API and may change. Although you can just copy/paste what you saw in `__init__.py` and it should work.

Usually an easy workaround is to copy the `logger` before adding any handler. Then you can copy it again anytime you need a new independent logger. Unfortunately this won't work in your case as you plan to distribute your project as a library. It's not really possible to remove and restore a set of existing handlers.

In any case, that would have not been very convenient nor straightforward. Considering your request has been has been asked several times, I'm planning to add a `new()` method in the next Loguru version.

You could also imagine using a `filter` but again it probably be very suitable for your library, because the end-user is supposed to be responsible for the added handlers. 

Note that using an separate `logger` means the user won't be able to easily "mix" their logs with yours.

**Comment by ciresnave** [comment]
Thank you for the fast response.  You confirmed my suspicions.  For now I will improvise my own `.add()` function with the plan to rewrite it to use your `.add()` method when the next version is released.  Thank you for your work on loguru.

**Comment by zhangchunsheng** [comment]
Can't change sys.stdout in different file.
