### ISSUE TITLE
Show the class name from where the record was written in log record

### ISSUE THREAD

**Issue by JakeCowton** [Delgan/loguru#523]
Currently we have access to `record.module` and `record.function` in the logging data, but for cases where you have multiple classes in the same module and each class has a common function name, its difficult to filter logs based on `common_function_name` for a specific class.

Is it possible for this to be added as a data point that can be logged in a similar way to `module` and `function`?

**Comment by Delgan** [comment]
Hi.

This would be an interesting feature unfortunately this is complicated because Python internals do not provide such information. Basically, Loguru makes use of frames to retrieve contextual information and it knows nothing about the current class.

The easiest solution is to combine [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) with a custom `format` handler as explained in https://github.com/Delgan/loguru/issues/430#issuecomment-822790352:

```python
class Hello:
    def __init__(self):
        self.logger = logger.bind(classname=self.__class__.__name__)

    def world(self):
        self.logger.info("hello world")

fmt = "<g>{time}</> | <lvl>{level}</> | <c>{extra[classname]}:{function}:{line}</> - {message}"
logger.remove()  # Remove default handler
logger.add(sys.stderr, format=fmt)

Hello().world()
```

**Comment by AtomScott** [comment]
Just a thought, but would providing a mixin for such cases be useful?

For example, 
```Python
class LoggerMixin:
    def __init__(self):
        self.logger = logger.bind(classname=self.__class__.__name__)
```

This could be used in `Hello` class like so,

```Python
class Hello(LoggerMixin):
    def __init__(self):
        super().__init__()

    def world(self):
        self.logger.info("hello world")

fmt = "{extra[classname]}:{function}:{line} - {message}"
logger.remove()  # Remove default handler
logger.add(sys.stderr, format=fmt)

Hello().world();

#output
Hello:world:47 - hello world
```

You could change the line
```Python
self.logger = logger.bind(classname=self.__class__.__name__)
```
to
```Python
self.logger = logger.bind(classname=self.__class__.__name__+':')
```
and remove the ':' from fmt (after `{extra[classname]}`) accordingly, so that it is possible to log functions with the same logger without the leading ':'.

**Comment by Delgan** [comment]
@AtomScott That looks like a helpful solution. However this is not something I plan to integrate into Loguru, but it can certainly serve as an example to users. :+1: 

Regarding the initial issue, as it seems solved, I'm closing the ticket. :)
