### ISSUE TITLE
Provide access to a list of existent handlers

### ISSUE THREAD

**Issue by GMavgo** [Delgan/loguru#526]
To use the logger in mutliple modules/functions, it would be helpful if one could check which handlers already exist.

**Comment by Delgan** [comment]
Hi.

I prefer not to expose handlers publicly, because they aren't meant to be modified by the user, and because it make the API simpler. See also https://github.com/Delgan/loguru/issues/251.

I do not fully understand how accessing the handlers list in our case would be useful. Do you have a more concrete example please? Maybe it's possible to find a solution to your problem using existing functions.

**Comment by GMavgo** [comment]
I think my main use case is to adapt the logging level, potentially with different logging levels for different modules. The only way that I know (may be outdated) is to remove the existent handler and to add a new handler. But there is also no easy way to check which logging level actually is currently used.

**Comment by Delgan** [comment]
You can also use a custom `filter` to adjust the minimal log level at runtime: [Changing the level of an existing handler](https://loguru.readthedocs.io/en/stable/resources/recipes.html#changing-the-level-of-an-existing-handler).

Sorry but I don't plan to provide access to the list of existing handlers. I'm closing this ticket consequently.

**Comment by GMavgo** [comment]
But the only way to get rid of the default debug-level logging is to delete the default handler, right?

**Comment by Delgan** [comment]
You can either `.remove()` it or disable it by setting the `LOGURU_AUTOINIT=NO` environment variable.

**Comment by GMavgo** [comment]
Thanks!
