### ISSUE TITLE
No logging after remove() followed by readme example add

### ISSUE THREAD

**Issue by thomasaarholt** [Delgan/loguru#530]
Loguru looks great, but I seem to be unable to log after removing? My intention was to add a logger with my own `format`.
```python
>>> from loguru import logger
>>> logger.error("hello")
2021-10-19 12:49:48.495 | ERROR    | __main__:<module>:1 - hello
>>> import sys
>>> logger.remove()
>>> logger.add(sys.stderr, format="{time} {level} {message}", filter="my_module", level="INFO")
# also tried 
# logger.add(sys.stderr, format="{time} {level} {message}", level="INFO")
>>> logger.error("hello")
# no output
```
What am I missing here?

**Comment by Delgan** [comment]
Hi @thomasaarholt.

As @Kusefiru pointed out, this is because of the `filter` option. It meant only logs from the given module will be logged, while the other ones will be discarded. In this case, it only allows logs from the module named `"my_module"`. The module' name is retrieved using the `__name__` value, which is different from `my_module` in the Python interactive terminal.

```python
>>> __name__
'__main__'
```
