### ISSUE TITLE
Adding an "example" folder that shows the recommended use?

### ISSUE THREAD

**Issue by jerabaul29** [Delgan/loguru#536]
Many thanks for a very nice library :) .

I was thinking about the following: would it be possible to get an ```example``` folder to show recommended use?

The reason for asking about this is that, even reading the readme and a couple of online posts, I am still a bit confused / unsure about things like:

- what is the recommended way to set it up in a library
- how does a library user should turn the library logging on / off / redirect it etc
- how should logging of "nested library dependencies" be used and set up.

If there could be an example, with a "dummy" library (and possibly some slightly nested things), and illustrations of how to turn it on and off, that would be easier for me to make my mind about how I should set things up :) .

**Comment by Delgan** [comment]
Hi @jerabaul29, thanks for the suggestion!

There exists a [Code snippets and recipes for `loguru`](https://loguru.readthedocs.io/en/stable/resources/recipes.html) page on the documentation that looks close to your idea. In my opinion it's more convenient to put the examples on the same page, as long as it is not too cumbersome.

Surely it could be updated with added explanation regarding the questions you have.

---

> * what is the recommended way to set it up in a library

Basically you don't want your library logs to show up in the middle of the user logs. Thus you should call [`logger.disable("your_lib")`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.disable) from within your `__init__.py` file. If the user wish to access the logs of your library, he can simply call [`logger.enable("your_lib")`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.enable).

You should also avoid adding new handlers on your own, because this is user responsibility to configure logging, and it's better not to interfere with that.

> * how does a library user should turn the library logging on / off / redirect it etc

He can do it though normal usage of Loguru. The `logger` object is the same for your user and your library. If the user is using Loguru, as already said he is responsible for configuring the handlers. It should work transparently as long as `logger.disable("your_lib")` has been called and no library handler added.

If the user isn't using Loguru, he'll probably need to call `logger.enable("your_lib")` himself and possibly connect an [`PropagateHandler`](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging) if he wish to use standard `logging` library.

> * how should logging of "nested library dependencies" be used and set up.

Except if I'm missing something, it should not be different from what was previously discussed. The `logger` of a nested library is the same as the `logger` of the user. User may enable or disable it at its convenience.

**Comment by jerabaul29** [comment]
Many thanks for your detailed answer :) . I was aware of the page you link to in the loguru documentation :) .

I think that I am just not familiar enough with logging and logging best practices to easily see / understand what you mean. So for me it is a bit confusing, probably not because of the loguru part, but because of the logging best practice in general. I guess then that what I ask for is rather a "logging guidelines with examples", more than some loguru documentation. I guess this can be classified as "out of topic", but if you are willing to help on this, I think offering an example (possibly in a separate repository + a couple of blog posts that you link to from loguru doc / readme) would be very helpful.

For me, seeing something that is "a bunch of modules and files that live in a number of folders in a repo" would be much easier to understand than the "pages of explanations" I find so far, because I find the "pages of explanations" to make quite a few assumptions about what the user already knows from before.

Only my 2 cents though of course with all of this discussion :) .

**Comment by Delgan** [comment]
As discussed, I did not consider the added complexity of an example folder to be worthwhile, but I have described the recommended structure in the documentation: [Configuring Loguru to be used by a library or an application](https://loguru.readthedocs.io/en/latest/resources/recipes.html#configuring-loguru-to-be-used-by-a-library-or-an-application). 

That seems like a relatively clear alternative I think. Hopefully it helps to better understand Loguru configuration best practices. If there remains any ambiguity, improvement suggestions are welcome. :+1:
