### ISSUE TITLE
How can I priorize one sink over another? Avoiding race conditions

### ISSUE THREAD

**Issue by Sendery** [Delgan/loguru#544]
I do have serveral sinks for a logger wich is include in a class:
.- One writes to stdout
.- Other publish via http post
.- Other sinks write to a json file in a custom format

The issue that I'm experimenting is that is taking to long get the response to the publish sink so when it arrives the code has evolve and the data in the json file isnt ready yet.

How can i rearrange the sinks so the last one is the publish (api) sink? This way the data will be ready even if the post reponse hasnt arrive yet.

Thank you very much for all your work, is a delight work with loguru.

**Comment by Sendery** [comment]
It seems that the API receiver that I did have for the logger wasnt enoght fast and generate race conditions accesing my database.
Thank you anyway

**Comment by Delgan** [comment]
Sorry for not answering sooner, @Sendery.

To answer your question: sinks are process in the order in which they were added. If you want a sink to be called before the others, you must `add()` it first.

I'm not sure to fully understand how your sinks relate to each others, though. Ideally, they should be independent so that the processing time does not matter. Note that you could also use `enqueue=True` if you want the sink not to block until the API response.
