### ISSUE TITLE
How to enable icons?

### ISSUE THREAD

**Issue by Brumo21** [Delgan/loguru#546]
Its not obvious how to use icons in your log messages, it is used in the examples to create a new level but never shown in use.

**Comment by Delgan** [comment]
This is because the icon aren't included in the default logging format (not all terminals support emojis so it's turned off by default).

You need to [`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) a new handler and specify a custom `format` which must contain [the `{level.icon}` field](https://loguru.readthedocs.io/en/stable/api/logger.html#record):

```
>>> logger.remove()  # Remove default handler
>>> logger.add(sys.stderr, format="[{time}][{level.icon}] {message}")
>>> logger.debug("This is a test")
[2021-12-07T20:20:39.089015+0100][🐞] This is a test
```

You can also customize the default format (so that you don't have to re-add a new handler each time) [by setting the `"LOGURU_FORMAT"` environment variable](https://loguru.readthedocs.io/en/stable/api/logger.html#env).
