### ISSUE TITLE
[Questions] logging 

### ISSUE THREAD

**Issue by asimniazi63** [Delgan/loguru#549]
1. How to write instead of appending logs in file on each new run ?
2. Can we get log between some time interval i.e. if I want logs for last two hours or so?

**Comment by Delgan** [comment]
Hi.

> How to write instead of appending logs in file on each new run ?

You can specify how the file should be opened using the `mode` parameter (just as the builtin `open()` function):

```python
logger.add("file.log", mode="w")
```

> Can we get log between some time interval i.e. if I want logs for last two hours or so?

Not really (except if you implement your own file-sink) because it would required erasing the beginning of the file before each write which would be slow. However, you can combine `rotation` with `retention` to only keep recent logs:

```python
logger.add("file.log", mode="w", rotation="2 hours", retention=1)
```

**Comment by Delgan** [comment]
Closing as this seems resolved. Feel free to re-open otherwise.
