### ISSUE TITLE
Where should I use "disable"?

### ISSUE THREAD

**Issue by AsafMah** [Delgan/loguru#559]
If I’m making a library, I don’t want the logs to be on by default.
The documentation recommends using the 'disable' method to disable logging in my package.

That’s great, but the question is where in my files should I call it?

In the start of every file I use loguru in?
Just once in the __init__.py? Or will it not be enough if the user will just import from an inner module

And should it be on the top level or somewhere else?

I’m not sure how to use it correctly

Thanks

**Comment by Delgan** [comment]
Hi.

You should put this in and only in the top `__init__.py` file of your library. It will be executed in all cases, even if your user only import a sub-package of your library. That's why you do not need to call `logger.disable()` from anywhere else. It needs to be called anytime your user import your library, so you can place it in your file and call it unconditionally.

I'll try to give more examples and clarify the documentations as discussed in #536.

**Comment by qiuxiaomu** [comment]
Hi @Delgan What if I only want to disable the logging for sub-modules? Do I do `logger.disable(grandpa.daddy.boy)` as indicated by my project structure?

**Comment by Delgan** [comment]
@qiuxiaomu Sorry, I missed your comment. :(

I'm not aware of the "project structure" you're referring to, but `logger.disable("grandpa.daddy.boy")` would indeed disable all logs coming from `"grandpa.daddy.boy"` module and its children (including indirect ones), while preserving all other logs.
