### ISSUE TITLE
how to rotate file on every run?

### ISSUE THREAD

**Issue by vseveryn** [Delgan/loguru#561]
hello, I ended up with such code ```rotation=EveryRunRotator()```

```
class EveryRunRotator:
    def __init__(self):
        self.rotate = True

    def __call__(self, *args, **kwargs):
        if self.rotate:
            self.rotate = False
            return True
        return False
```

**Comment by Delgan** [comment]
Hi, what do you mean by "every run" ?

If you want a new file to be created each time your script is launched, you can timestamp your file name:

```python
logger.add("file_{time}.log")
```

The `{time}` will be automatically replaced with current date, thus giving a unique name to the file each time the handler is configured.

**Comment by vseveryn** [comment]
I want to have the latest logs in `file.log` name without timestamp

**Comment by Delgan** [comment]
The rotation is not triggered when the script if stopped and the file closed. The rotation process occurs before writing a log message based on time or file size.

You can create your own `rename_file()` function and call it before configuring the `logger`:

```python
import os
from datetime import datetime
from loguru import logger

def rename_file(filepath):
    date = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    root, ext = os.path.splitext(filepath)
    newpath = f"{root}.{date}{ext}"
    os.rename(filepath, newpath)

if os.path.exists("file.log"):
    rename_file("file.log")

logger.add("file.log")
```

**Comment by tjdodson** [comment]
> The rotation is not triggered when the script if stopped and the file closed. The rotation process occurs before writing a log message based on time or file size.
> 
> You can create your own `rename_file()` function and call it before configuring the `logger`:
> 
> ```python
> import os
> from datetime import datetime
> from loguru import logger
> 
> def rename_file(filepath):
>     date = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
>     root, ext = os.path.splitext(filepath)
>     newpath = f"{root}.{date}{ext}"
>     os.rename(filepath, newpath)
> 
> if os.path.exists("file.log"):
>     rename_file("file.log")
> 
> logger.add("file.log")
> ```

Wow that went over my head. I am a new loguru user and have been using the ecs_logging format to ship logs to ES using filebeat. I want to do something similar in an application of mine that just simply runs in an infinite while loop (a four year long temporary solution full of band aids and duct tape). I used to handle logging by having logic at the top of the loop that runs something like this:
```python
import logging
import datetime

today = datetime.date.today()
file_path = f"path/to/logs_{today.strftime("%Y-%m-%d")}.log"
logging.basicConfig(filename=file_path, level=logging.INFO)

while True:
    if datetime.date.today() > today:
        file_path = f"path/to/logs_{today.strftime("%Y-%m-%d")}.log"
        logging.basicConfig(filename=file_path, level=logging.INFO)
    # insert basic application logic here
```

obviously this is hot garbage particularly since if I want to log something in another module I have to pass it explicitly, otherwise I get a 

```python
NameError: name 'logging' is not defined
```

What is the pythonic and loguru method for setting things like this up? Here is my current setup that I want to start implementing into all my applications (2022 New Years resolution stop using print to debug)

```python
import sys
import logging
from loguru import logger
import ecs_logging

logfile = "logfile.json"
logger.remove(0)
logger.start(sys.stdout, colorize=True, format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> <level>{level}</level> From {module}.{function}: <level>{message}</level>")
handler = logging.FileHandler(logfile) # it would be nice if I could do something like logging.FileHandler("file_{time}.json"), but that isn't your concern since the handler is created by logging not loguru
handler.setFormatter(ecs_logging.StdlibFormatter())
logger.add(handler, format="{message}") # Can I just omit the file path when creating handler and add it here with "file_{time}.json"? Also how would I format it to be "%Y-%m-%d"?
```

now replace all print statements with logger.WhateverAppropriate and add @logger.catch decorators to all my modules (love that feature). Anyways I am a big fan of the development work here, and I try to do the appropriate level of research before asking for help, but if you can offer any assistance on how to approach this correctly then I would greatly appreciate it. In the meantime, putting the file on a size rotation and pushing to Elastic is plenty good enough. Just would be nice to parse the logs by date in case I want to archive them into separate files somewhere.

It would be nice to get a setup where I can import a conf and then just start logging automatically preferably after just defining a specific log path. That would make maintenance of my logging across all projects much simpler over time.

**Comment by Delgan** [comment]
Hey @tjdodson, sorry for the late answer. Excellent new year resolution anyway. :)

Usually using Loguru you only need to configure logging once, at the entry point of your script. From the modules where you want to replace `print()` with `logger`, you are ready-to-go simply with `from loguru import logger`.

I do not know how logs are sent to Elasticsearch. Do you need a specific handler to do so?

Otherwise, you should be able to replace `FileHandler` with a path handled by Loguru. However, in this case you also need to implement a replacement for `ecs_logging.StdlibFormatter()` using existing [record attributes](https://loguru.readthedocs.io/en/stable/api/logger.html#record).

Here is an example:

```python
# main.py
import json
from loguru import logger

def ecs_formatter(record):
    data = {
        "@timestamp": record["time"].isoformat(),
        "log.level": record["level"].name,
        "message": record["message"],
        "log.logger": record["name"],
    }
    # The formatter is not supposed to format the message, it must return a string to be formatted.
    # For this reason, the JSON message compatible with Elasticsearch is added to the 'extra' dict
    # and will be formatted internally by Loguru.
    record["extra"]["esc_formatted"] = json.dumps(data)
    return "{extra[esc_formatted]}\n"

def configure_logger():
    logger.remove()
    logger.add(sys.stdout, colorize=True, format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> <level>{level}</level> From {module}.{function}: <level>{message}</level>")
    logger.add("file_{time:YYYY-MM-DD}.log", format=esc_formatter, rotation="daily")

if __name__ == __main__:
    configure_logger():
    while True:
        ...  # Logic application
```

I couldn't test this snippet though, so let me know if anything needs clarification. ;)

**Comment by tjdodson** [comment]
@Delgan sorry to play a game of telephone, I got caught up in working on something else and didn't realize how long it had been since I saw your reply. Let's say I had the following file structure:
```shell
.
├── main.py
├── POC
│   └── EDA.ipynb
├── sql
│   ├── ElasticSearch
│   ├── BigQuery
│   └── pseudo_code.py
└── tools
    └── dfs.py
```

where `main.py` was essentially as you have prescribed. Would I be able to do something like the following:

```python
# tools/dfs.py

import os
import pandas as pd

logger.info("Hey nice to see you!")

@logger.catch
def pull_ES(client):
    try:
        assert client.status.health() == "green"
    except:
        logger.warning("ES is not exactly in the best help probably best not to bombard it with requests")

    # Rest of pull code
```

**Comment by Delgan** [comment]
No problem @tjdodson. :+1: 

The example you provided should work fine. Calling `dfs.pull_ES(client)` will use the imported `logger` object. When a message is logged using this `logger`, it will be propagated to the configured handlers in `main.py`. 

Note that the `logger.catch()` in your example will never be used as there is a `try / except` block in your function anyway. ;)
