### ISSUE TITLE
Log file rotation not rotating file

### ISSUE THREAD

**Issue by turner-prize** [Delgan/loguru#58]
I have a log configured as per the below:

logger.add("path/to/log.log", 
                   format="{time:DD/MM/YY HH:mm:ss} - {message}", 
                   level="CustomLogLevel",
                   filter=lamba record: record['level']="CustomLogLevel",
                   rotation="1 week")

The script which the above logger is linked to runs once per hour, for about 30 seconds. All works fine except the rotation, it's been configured since the 6th of Feb and hasn't created a new file yet, just keeps appending to the file which was initially created. Is this configured wrong on my end?

Edit:
Just read the contributions page! 
using:
Python 3.7.2
Loguru 0.2.5
Windows Server 2016
Using both VS Code and terminal.

**Comment by turner-prize** [comment]
Think I might have solved this one myself. I guess I wanted retention rather than rotation?

As per the docstrings in _logger.py;

      Parameters
        ----------
        rotation : |str|, |int|, |time|, |timedelta| or |function|_, optional
            A condition indicating whenever the current logged file should be closed and a new one
            started.

My file is opened and closed each time the file is run, I believe the above refers to a file being open for an extended period of time (in my case, a week) before the rotation will close and start a new one? In which case it won't apply to my situation?

**Comment by Delgan** [comment]
Hi @turner-prize.

As you understood, `rotation` is mainly used for applications running continuously. If it started since `1 week` (as for your example), then the log file will be closed and a new one created.

The `retention` parameter is used to remove old log files. However, this only makes sense if you start a new log file each time you launch your application, that is if you use `logger.add("file_{time}.log")` for example.
That way, instead of creating `"file_2019-02-18_12-00-00.log"`, `"file_2019-02-18_13-00-00.log"`, `"file_2019-02-18_14-00-00.log"`... indefinitely, this only keeps the most recent ones.

There is currently no way to rotate your log file based on the time it was created, supposing you open and close the same file each time you run your application.
Maybe I could change the behavior of the `rotation` argument, so it no longer uses the time the application is launched, but rather the time the file was first created. 🤔

**Comment by turner-prize** [comment]
Ah that makes sense. I should have read the docs a bit closer! I might just add a function before the logger config to check how old the log is, and rename it with an appended date if over a week old, which will do the job.

Love the library by the way!

**Comment by Delgan** [comment]
You could also pass your function to the `rotation`, argument. Something like this should work I think (not tested):

```python
def should_rotate(message, file):
    filepath = os.path.abspath(file.name)
    creation = os.path.getmtime(filepath)
    now = message.record["time"].timestamp()
    maxtime = 7 * 24 * 60 * 60  # 1 week in seconds
    return now - creation > maxtime
```



> Love the library by the way!

Thanks!

**Comment by Delgan** [comment]
I'm reopening this issue as I think I may implement the workaround directly into Loguru.

It makes more sense to have the `rotation` argument based on the file date creation rather that the application started time.

**Comment by JonasR-** [comment]
I am testing loguru currently and was confused that the rotation behaves like this. I appreciate that you will implement the rotation based on creation date

**Comment by YJinHai** [comment]
> I'm reopening this issue as I think I may implement the workaround directly into Loguru.
> 
> It makes more sense to have the `rotation` argument based on the file date creation rather that the application started time.

I think so, too. Thank you

**Comment by YJinHai** [comment]
> 您也可以将函数传递给`rotation`参数。我认为这样的事情应该有效（未经测试）：
> 
> ```python
> def  should_rotate（消息，文件）：
>     filepath = os.path.abspath（file .name）
>     creation = os.path.getmtime（filepath）
>     now = message.record [ “ time ” ] .timestamp（）
>     MAXTIME =  7  *  24  *  60  *  60   ＃ 1周秒
>     返回现在-创建> MAXTIME
> 
> logger.add（ “ file.log ”，旋转= should_rotate）
> ```
> 
> > 顺便爱上图书馆！
> 
> 谢谢！



> You could also pass your function to the `rotation`, argument. Something like this should work I think (not tested):
> 
> ```python
> def should_rotate(message, file):
>     filepath = os.path.abspath(file.name)
>     creation = os.path.getmtime(filepath)
>     now = message.record["time"].timestamp()
>     maxtime = 7 * 24 * 60 * 60  # 1 week in seconds
>     return now - creation > maxtime
> 
> logger.add("file.log", rotation=should_rotate)
> ```
> 
> > Love the library by the way!
> 
> Thanks!
I found a small error here. os.path.getmtime (path) returns the most recent file modification time
os.path.getctime (path) returns the file path creation time, which should be changed from getmtime to getctime

**Comment by Delgan** [comment]
Ok, I finally find the time to update the `rotation` behavior based on your suggestion! This should be effective once the `v0.3.0` is published.

As @YJinHai correctly noticed, the first snipped I provided was wrong because based on the `mtime` attribute (which corresponds to the time of the last modification, not the time of the file creation).

Actually, there is no standard cross-platform way to retrieve the creation time of a file. Python doesn't provide such utility and it's not easily accessible on Linux systems. See [this question on SO](https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python/39501288).

Consequently, I had to implement a different policy on each platform:
* Use [`st_ctime`](https://docs.python.org/3/library/os.html#os.stat_result.st_ctime) on Windows
* Use [`st_birthtime`](https://docs.python.org/3/library/os.html#os.stat_result.st_birthtime) if available (on Mac OS generally)
* Manually assign and retrieve a custom [extended file attribute](https://en.wikipedia.org/wiki/Extended_file_attributes) if [`setxattr()`](https://docs.python.org/3/library/os.html#os.setxattr) and [`getxattr()`](https://docs.python.org/3/library/os.html#os.getxattr) are supported (on most Linux filesystems), fallback to [`st_mtime`](https://docs.python.org/3/library/os.html#os.stat_result.st_mtime) otherwise

This should work in most cases.
