### ISSUE TITLE
Request: convenient parser from log format

### ISSUE THREAD

**Issue by theunkn0wn1** [Delgan/loguru#588]
This library has a "convenient parser" that accepts a regex pattern.

It would be even more convenient if it could parse it's own log files if feed the format used to generate them

**Comment by Delgan** [comment]
This is indeed something I though about but this seems too complex to be handled properly. There are many edge cases than can't be guessed just from the logging `format`, especially due to custom attributes. I do agree that would be much more convenient but I will leave regex be handled by the user.

I'm thinking I could maybe create a basic proof of concept and add it as an example in the documentation, though.

**Comment by Delgan** [comment]
Closing for now as I have no idea how to implement it anyway.

**Comment by theunkn0wn1** [comment]
I think for this the answer is just don't.
TBH, i ultimately worked around this by serializing the data and making good use of loguru's tracing features.

For others that may stumble across this later:
If you need to post-process the logs, use `serialize=True` in the sink and write jsonlines.
Downstream tooling like Splunk can easily parse serialized json records.
For added value, make use of Loguru's tracing features (e.g. `with logger.contextualize(extra_key = ...):` to attach data to the log records.
