### ISSUE TITLE
The log level corresponding to the log level number is not displayed

### ISSUE THREAD

**Issue by jackgithubtest** [Delgan/loguru#599]
When I used numbers to replace the log level output, I did not output the corresponding log level in the console after the input number, but output the level % number. However, I read the source code part specifically to do this department processing, do you have any special purpose?
```
def _get_num_level(level):
    level_dict = {
        "CRITICAL": 50,
        "FATAL": 50,
        "ERROR": 40,
        "WARNING": 30,
        "WARN": 30,
        "INFO": 20,
        "DEBUG": 10,
        "NOTSET": 0,
    }
    return level_dict[level.upper()]
logger.log(_get_num_level(level=level), 'aaa')
```
The actual output is:
```
2022-02-22 15:30:41.834 | Level 20 | __main__:do_log:95 - aaa
```
I want the result to be:
```
2022-02-22 15:41:48.150 | INFO     | __main__:do_log:95 - aaa
```

**Comment by Delgan** [comment]
Hi @jackgithubtest.

The logging level is identified by its name, not by its severity number. Multiple levels can use the same severity number. Consequently, it's not possible for Loguru to unambiguously identify a level just by knowing its level of severity.

When `.log()` is used with an integer, Loguru interprets it as an anonymous level that has no registered name, and therefore displays `"Level X"` instead. If you call `.log()` using a known level name, it should work.

**Comment by jackgithubtest** [comment]
Hi @Delgan
Thank you very much for your reply. I have noticed that the problem may be that I am too poisoned by logging. I see that Loguru is compatible with logging, and I use severity number to get the corresponding level in logging

**Comment by Delgan** [comment]
Indeed, this is a case where Loguru has made a different design choice from the standard logging module. In my opinion, a level should be identified by its name and its name only. On the other hand, the standard logging module will try to find an existing level corresponding to the number (and use the most recently configured if there is a conflict). This approach may be more convenient but it may be surprising if an external module defines the same level. That's why I think it's better to use the level name whenever possible.

**Comment by Delgan** [comment]
Closing as the question seems answered.
