### ISSUE TITLE
How to freeze time for tests?

### ISSUE THREAD

**Issue by thurse93** [Delgan/loguru#600]
We use `pytest-freezegun` to freeze time for tests throughout our projects. However it seems that loguru does not reflect this time freeze. We think this is because freezegun cannot patch the datetime objects used by loguru.

A minimal pytest example to reproduce the problem:

```python
import sys
import pytest

from datetime import datetime
from loguru import logger

@pytest.mark.freeze_time("1999-01-22T12:00:00")
def test_time_freeze(capsys):
    now = datetime.now()
    assert str(now.isoformat()) == "1999-01-22T12:00:00"
    logger.remove()
    logger.add(sys.stderr, format="{time} {message}")
    logger.info("this does not freeze time")
    captured_stderr = capsys.readouterr().err
    assert captured_stderr.startswith(now.isoformat())   # This should not fail
````

What is the correct way to freeze the time for loguru?

**Comment by Delgan** [comment]
Thanks for the reproducible example.

A possible workaround is to [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) the `"time"` value of the `record` dict like so (I'm using [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) here): 

```python
logger.configure(patcher=lambda r: r.update(time=now))
```

You can do this at the very beginning of your test, and it will override the real `"time"` value of logged message.

This is pretty fragile, though. It doesn't work well if you use a custom format (e.g. `"{time:YYMMDD HHmmss}"`). Also, the default format is different from the one returned by `isoformat()`, so you may need to modify the `assert` statement:

```python
assert captured_stderr.startswith("1999-01-22 12:00:00")
```

I will see if it is possible to update Loguru so that it works out of the box with Freezegun.
