### ISSUE TITLE
Don't print stack frames from certain libraries

### ISSUE THREAD

**Issue by riyadparvez** [Delgan/loguru#622]
@Delgan Continuing the conversation from this issue since it's loguru issue: https://github.com/Qix-/better-exceptions/issues/118.

Is it possible to not print stack frames from third party library? Ideally with a confiuration ignore=['pandas', 'numpy'] or a function ignore(['pandas', 'numpy'])?

**Comment by Delgan** [comment]
Hi @riyadparvez.

The frames of the external libraries are already dimmed (no color nor spacing), can you confirm that? Otherwise, it would indicate that there is some false negative in the detection algorithm and we could improve that.

You may also try to set `backtrace=False` while adding your handler, it should help not to display undesired frames.

Apart from that, I prefer not to add new options regarding exception formatting as it's already doing too much in my opinion. It's possible to use alternative formatters by defining a custom `format` function: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).

**Comment by jouyang3** [comment]
is there anyway loguru enables ways to ignore certain patterns on tb_frame.f_code.co_name and co_filename? This would help to ignore third party library and at the same time get rid of undesired wrapper function tracebacks (which is what I am looking for right now).

**Comment by Delgan** [comment]
@jouyang3 I prefer to avoid this kind of option. Loguru tries to stick close to the built-in exception formatting. It just enhances it trying to make it more readable. Still, I prefer not to make parts of the stackframe disappear.

Usually, external libraries are not highlighted. If there is a problem here, please feel free to open a ticket with a minimal reproducible example so that it can be fixed. In the meantime, I'm closing this issue.
