### ISSUE TITLE
print logs in JSON format, causing an error

### ISSUE THREAD

**Issue by ipylei** [Delgan/loguru#635]
```
import json

from loguru import logger

logger.add("runtime.log")
logger.add("special.log", filter=lambda record: record["extra"].get("name") == "special")
special_logger = logger.bind(name="special")

dct = {"message": "xxx"}
text = json.dumps(dct, ensure_ascii=False)
logger.info(text, name="special")  # KeyError: '"message"'
special_logger.info(text)  # right
```
logger.info("xxx", name="special") can achieve the effect， but when print json format string by this way will causing an KeyError.

**Comment by Delgan** [comment]
When using the `logger`, Loguru will try to format the message according to provided arguments. The `logger` was initialized intended to be used this way:

```python
value = 42
logger.info("Some message with value: {}", value)
```

Internally, it roughly calls:

```python
message.format(*args, **kwargs)
```

In your case, due to `text` begin a JSON-serialized message, the formatting raises an exception because it wasn't intended to be formatted but Loguru isn't aware of that.

As a workaround, you can use `bind()` to structure your message this way:

```python
logger.bind(name="special").info(text)
```

In future version, the automatic formatting will likely be removed in favor of f-strings.
