### ISSUE TITLE
KeyError on logging

### ISSUE THREAD

**Issue by KonstantinKuklin** [Delgan/loguru#642]
Hi, Im using loguru 0.6.0 with python 3.9.7
```python
from loguru import logger
proxy = {
    'test_key': 'test_value',
}
logger.info("Test_message {}".format(proxy), enqueue=True)
```

brings:
```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    logger.info("Test {}".format(te), enqueue=True)
  File "venv\lib\site-packages\loguru\_logger.py", line 1977, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "venv\lib\site-packages\loguru\_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
KeyError: "'test_key'"
```

without `enqueue` works fine

**Comment by Delgan** [comment]
This is because Loguru tries to format an already formatted message.

When arguments or keyword arguments are passed to the `logger.info()` method, Loguru uses them to create the log message by calling `message.format(*args, **kwargs)`. In your case, the `message` is already formatted because you called `"Test_messge {}".format(proxy)` which results in `"Test_message {'test_key': 'test_value'}"`. However, as you're also passing `enqueue=True`, Loguru will call `.format()` again on this formatted message, resulting in an error because `'test_key'` is not a existing argument.

You should instead use:

```python
logger.info("Test_message {}", proxy)
```

You do not need to call `.format()` yourself as it's already done by Loguru.

I don't know why you need `enqueue=True` because this parameter only applies to `.add()` method while configuring sinks.

**Comment by KonstantinKuklin** [comment]
thank you for the explanation, I used `enqueue=True` in wrong place
