### ISSUE TITLE
enter/exit decorators

### ISSUE THREAD

**Issue by brechmos-stsci** [Delgan/loguru#65]
It would be nice to have a decorator that one could add to a method (in a class or bare) that logs entry and exit from a method.  I suppose you could have one of each, maybe something like:

```
@logger.enter
@logger.exit
def themethod():
    a = 5
```
and the logging would then include a logging statement saying the method the was entered and a logging statement when the method is exited.

The general idea could be something like the answer in https://stackoverflow.com/questions/23435488/how-to-do-logging-at-function-entry-inside-and-exit-in-python

I think it might follow something along the lines of the `logger.catch`.

**Comment by brechmos** [comment]
@Delgan If this type of method interests you, I have it *partially* implemented and could do a PR. I would have a few questions about getting the right method name in the log message, though.

**Comment by Delgan** [comment]
Hello @brechmos, thanks for your suggestion. :)

This is a feature I have considered in the past. I decided not to implement it because I was not convinced that this was the proper way to use logging. I'm not saying it's bad practice, but I'm not sure it is not. Basically, this looks too much like using logging instead of an appropriate debugger.

Logging is ideal to record entry and exit points of your application, to log non-deterministic data information, to notify the user about what is hapenning, to have a clue about which part of your code failed, to register unexpected event or unusual behavior.
I'm afraid a decorator to log entry / exit of any function is not fundamentally useful and would be abused.

What would you think of adding such decorator as a snippet in the documentation first?

**Comment by jakane** [comment]
A use case for logging function entry / exit is to log functions / methods that are expensive. I have used this to later scrape the log files and look for changes in performance over time. I have possibly over-used this in the past, but it is impossible to diagnose an issue that grows over time if you are measuring for it in the first place.

**Comment by Delgan** [comment]
@brechmos I added a snippet [in the documentation](https://loguru.readthedocs.io/en/latest/resources/recipes.html#logging-entry-and-exit-of-functions-with-a-decorator). Please, tell me if you have suggestions for improvements.

@jakane That's an interesting use case. However, this confirms the fact that it is not to `loguru` to implement this kind of decorators, because there are just too many possible use cases.

I guess your decorator could look like this:

```python
def wraper(func):
    def wrapped(*args, **kwargs):
        start = time.process_time()
        res = func(*args, **kwargs)
        end = time.process_time()
        logger.debug("Function '{}' executed in {} s", func.__name__, end - start)
        return res
    return wrapped
```

Actually, there is nothing much inherently related to Loguru's logger here. Loguru aims to provide logging functionalities, in my opinion it's not its purpose to provide decorator utilities.

**Comment by brechmos** [comment]
Sorry for the late reply, but I like the example snippet you put in the documentation. 

One person suggested using it as a way to do timing, so maybe include an example like this (?):
```
import functools
import time
from loguru import logger

def logger_wraps(*, entry=True, exit=True, level="DEBUG", timing=False):

    def wrapper(func):
        name = func.__name__

        @functools.wraps(func)
        def wrapped(*args, **kwargs):
            logger_ = logger.opt(depth=1)
            if timing:
                start = time.time()
            if entry:
                logger_.log(level, "Entering '{}' (args={}, kwargs={})", name, args, kwargs)
            result = func(*args, **kwargs)
            if exit:
                if timing:
                    msg = "Exiting '{}' (result={}) Took {:.3f}s".format(name, result, time.time() - start)
                else:
                    msg = "Exiting '{}' (result={})".format(name, result)

                logger_.log(level, msg)
            return result

        return wrapped

    return wrapper


@logger_wraps()
def test(a=6, b=2):
    time.sleep(1)

@logger_wraps(timing=True)
def test_timeit(a=6, b=2):
    time.sleep(1)

if __name__ == '__main__':
    test(b=7)
    test_timeit(b=7)
```
but it does add another dependency (`time`).

Otherwise, all looks great.

**Comment by Delgan** [comment]
> Sorry for the late reply,  but I like the example snippet you put in the documentation.

@brechmos Nothing to worry about, thanks for answering and reviewing the code snippet!

You are right, I should add the "timing decorator" to as an example. I will probably separate it from the existing `logger_wraps` example rather than making a "all-in-one" decorator for the sake of comprehensiveness.

**Comment by Delgan** [comment]
All examples has been added to the [recipes documentation](https://loguru.readthedocs.io/en/latest/resources/recipes.html), thanks! :)
