### ISSUE TITLE
logging something  with '{string}' and add  args or kwargs BUGs

### ISSUE THREAD

**Issue by x931890193** [Delgan/loguru#678]
```python
from loguru import logger
logger.error("{ssss}", 'sss')
````

### KeyError
```bash
Traceback (most recent call last):
  File "/Users/sato/Desktop/rct/scrcpy_ai/buff_detection_srv/logger.py", line 6, in <module>
    logger.error("{ssss}", 'sss')
  File "/Users/sato/.virtualenvs/scrcpy_ai/lib/python3.7/site-packages/loguru/_logger.py", line 1989, in error
    __self._log("ERROR", None, False, __self._options, __message, args, kwargs)
  File "/Users/sato/.virtualenvs/scrcpy_ai/lib/python3.7/site-packages/loguru/_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
KeyError: 'ssss'
```
## reason

```python
# file _logger.py

line1952    elif args or kwargs:
line1953        colored_message = None
line1954        log_record["message"] = message.format(*args, **kwargs) # this line will cause KeyError!!!!!!!!!!!
```

**Comment by Delgan** [comment]
Hi @x931890193.

I don't think this qualifies as a bug... :open_mouth: 

The logging methods (like `logger.error()`in your example) are designed and documented to act as much as possible like the built-in [`str.format()`](https://docs.python.org/3/library/stdtypes.html#str.format) method. It automatically formats a message based on optional `*args` and `**kwargs` arguments, which is more convenient that calling `message.format()` manually when logging a message.

```python
logging.warning("%s before you %s", "Look", "leap!")         # Built-in logging use old % formatting.
logging.warning("{} before you {}".format("Look", "leap!"))  # Modern formatting using {} is verbose.
logger.warning("{} before you {}", "Look", "leap!"))         # Loguru tries to make it more convenient.
```

In your example, beacause you provide `"sss"` as an argument to the logging method, Loguru thinks you want to format the message and thus call `"{ssss}".format("sss")`. This raises an error because Python except an `ssss` keyword argument to format the string, but find none (hence the `KeyError`). For example, `logger.error("{ssss}", ssss="sss")` would be valid and generate `"sss"` message. If you don't need formatting, don't pass the `"sss"` as an argument when logging your message. Otherwise, you can also disable formatting with `logger.error("{{ssss}}", "sss")` and the argument will just be ignored.

Using `str.format()` internally makes less sense now that f-string became popular, so I plan to modify the current behavior in the future, but I would say it's working as expected for now.

**Comment by x931890193** [comment]
@Delgan  
Thank you for your reply！！ 😊

I add a callback function like ：
```bash
# add callback
def fn_callback(record):
    if record['extra'].get('flag'):
        do_something()

logger = ruloger.patch(fn_callback)

# in use
http_response = {"code": 0, "msg": "", "data": None}
logger.error(http_response, flag=True) # I just want to log a dict and add a `flag` 😁
```

**Comment by Delgan** [comment]
In this case I better understand the issue you're facing. 

This is a problem that has been reported multiple times, and that's indeed why I plan to (optionally) remove the automatic formatting in a future version. In the meantime, you should use [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) when passing data which isn't intended to be formatted:

```python
logger.bind(flag=True).error(http_response)
```

**Comment by x931890193** [comment]
> 

many thx, it`s working!
