### ISSUE TITLE
many logs created with date in file name

### ISSUE THREAD

**Issue by paopjian** [Delgan/loguru#695]
I set 2 log but I found many logs with date in the file name. You can see "base64_log_20220819.2022-08-19_15-26-06_100641.log", I think it should be "base64_log_20220819.log". 
 I use uvicorn and gunicor with one thread. I have no idea why the date in the file name
``` python
logger.add("logs/log_{time:YYYYMMDD}.log",
               format="{time:YYYY-MM-DD HH:mm:ss.SSS} | {level} | {message}",
               level="INFO",
               filter=lambda record: "base64" not in record["extra"],
               rotation="12:00",
               diagnose=False,
               catch=False)
logger.add("logs/base64_log_{time:YYYYMMDD}.log",
               format="{time:YYYY-MM-DD HH:mm:ss.SSS} | {level} | {message}",
               level="INFO",
               filter=lambda record: "base64" in record["extra"],
               rotation="12:00",
               diagnose=False,
               catch=False)
logger.info(f"ACCEPT /predict/id ip:\"{req.client.host}\" hash:\"{data_hash}\" {str(data)} {str(type)}")
```
![image](https://user-images.githubusercontent.com/20377352/185581106-26c0bb76-58e1-47e8-8399-2574e0d8ec8b.png)

![image](https://user-images.githubusercontent.com/20377352/185581076-a488b164-bcca-46f3-98f2-433b02fdfbfc.png)

**Comment by Delgan** [comment]
Hi.

I think this happens because of multiple processes started by Uvicorn. Each time a new process is spawned, the entire script is likely re-executed, causing `logger.add()` to be called more times than desired.

Can you please look at this article and tell me if it helped you: [Unify Python logging for a Gunicorn/Uvicorn/FastAPI application](https://pawamoy.github.io/posts/unify-logging-for-a-gunicorn-uvicorn-app/).

Otherwise, could you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) including Uvicorn/Gunicor setup and command line?
