### ISSUE TITLE
catch not  work

### ISSUE THREAD

**Issue by nmweizi** [Delgan/loguru#70]
- python 3.6.8x64
- win10x64
- loguru 0.2.5
- **test.log File does not record KeyboardInterrupt information** 
- code
```
from loguru import logger
import time

@logger.catch(reraise=True)
def main():
    try:
        while 1:
            time.sleep(5)
    except KeyboardInterrupt:
        print('11111111111')

if __name__ == '__main__':
    logger.add("test.log", rotation="10 MB",)
    logger.info('asdf')
    main()

    print('222222222222')
```

**Comment by Delgan** [comment]
Hi @nmweizi.

This is excpected, because the default type of exceptions caught by the `@logger.catch` decorator is `Exception` from which `KeyboardInterrupt` **does not inherit**, see [Python exception hierarchy](https://docs.python.org/3/library/exceptions.html#exception-hierarchy).

The `KeyboardInterrupt` is a special kind of exception which alter the control flow of a program abruptly, the stack trace resulting of such exception is of little use. This is the type of exception that you want to stop your program, it generally should not be caught and handled silentlly (hence the `reraise=True` in your code).

If you wish to catch this type of error, you can wrap your function with `@logger.catch(KeyboardInterrupt, reraise=True)` or more generally `@logger.catch(BaseException, reraise=True)`.

**Comment by nmweizi** [comment]
thank very much
