### ISSUE TITLE
Remote Logging like Logstash

### ISSUE THREAD

**Issue by Srithar-ccs** [Delgan/loguru#736]
Hi Project Owner,

Loguru is an awesome project. I was able to solve all my logging problems with loguru.
Soon I'll be running my own set of servers, so I would like to log all the logs from multiple nodes to a central location in my local LAN.
Can you give me an example on how to log to a ELK Stack - Logstash application or write to a remote file or folder in master node ?
Thanks in advance for the help

**Comment by imlison** [comment]
Using `filebeat` is a more common practice in my opion.

**Comment by Delgan** [comment]
Sorry @Srithar-ccs  I can't help you with such a task because I'm not knowledgeable about Logstash.

Loguru works with any function as a sink, so surely you should be able to design an appropriate handler.

The closer I can think of is this snippet in the documentation: [Sending and receiving log messages across network or processes](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes).

**Comment by Srithar-ccs** [comment]
> Using `filebeat` is a more common practice in my opion.

Thank you @imlison , that's exactly what i wanted. That helps a lot. Have a great day.
