### ISSUE TITLE
Warn when using ~ in filename sink

### ISSUE THREAD

**Issue by AntarktisZ11** [Delgan/loguru#763]
I was using ~ in a filename by mistake but got no warnings about it.

Short example:
```python
from loguru import logger
logger.add("~/logs/example_app.log", mode="w")
logger.info("Testing")
```
```bash
>>> cat ~/logs/testing_logguru.log
cat: /home/pi/logs/testing_logguru.log: No such file or directory
```

---
Solution:
The correct thing is to expand filename with pathlib before using it like
```python
from pathlib import Path
filename = Path("~/logs/example_app.log").expanduser()
```
but since this was forgotten it was hard to troubleshoot without a warning.

---
P.S.
Love how easy and effortless you've made it to add nice logging, even to short scripts.

**Comment by Delgan** [comment]
Hi. ;)

This does not raise a warning because this is actually a **valid** path. It's just that it creates a literal `"~"` folder.
You can see it's content by quoting the path to avoid the `~` expansion: `cat "~/logs/example_app.log"`.

It's a little gotcha but it's the same with standard `Path()` and I don't think it should be Loguru responsibility to expand or warn about `~` in paths.

**Comment by AntarktisZ11** [comment]
Ah I see. Well that explains it well, I'll be more careful in the future when writing my CLIs

**Comment by Delgan** [comment]
Yeah, it's something to keep in mind while dealing with paths in Python.

Closing the issue then. :+1:
