### ISSUE TITLE
Loguru rating reports an error. Why? Why do the basic functions still have problems?

### ISSUE THREAD

**Issue by knightwk** [Delgan/loguru#766]
# Error description
```
--- Logging error in Loguru Handler #2 ---
Record was: {'elapsed': datetime.timedelta(seconds=8, microseconds=183127), 'exception': None, 'extra': {}, 'file': (name='urls.py', path='F:\\code_python\\django_and_loguru_test\\django_and_loguru_test\\urls.py'), 'function': 'index', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 29, 'message': 'This is an info msg. num = 999, rand_num = 9.', 'module': 'urls', 'name': 'django_and_loguru_test.urls', 'process': (id=14492, name='MainProcess'), 'thread': (id=9368, name='Thread-7'), 'time': datetime(2022, 12, 18, 21, 8, 59, 874615, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\programming\Python39\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\programming\Python39\lib\site-packages\loguru\_file_sink.py", line 173, in write
    self._terminate_file(is_rotating=True)
  File "D:\programming\Python39\lib\site-packages\loguru\_file_sink.py", line 204, in _terminate_file
    os.rename(old_path, renamed_path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:\\code_python\\django_and_loguru_test\\logs\\test.log' -> 'F:\\code_python\\django_and_loguru_test\\logs\\test.2022-12-18_21-08-51_272529.log'
--- End of logging error ---
```
# logger.py
```python
log_path = Path(BASE_DIR, "logs")

if not log_path.exists():
    log_path.mkdir()
LOG_FILE_NAME = Path(log_path, "test_.log")
from loguru import logger


class MyLogger:
    def __init__(self, log_file_path=LOG_FILE_NAME):
        self.logger = logger
        self.logger.remove()

        self.logger.add(sys.stdout,
                        format="[<green>{time:YYYY-MM-DD HH:mm:ss,SSS}</green>] "
                               "[{process.name}] "
                               "[{thread.name}] "
                               "[<cyan>{name}.{function}:{line}</cyan>] "
                               "[<level>{level}</level> ] - "
                               "<level>{message}</level>",
                        )

        self.logger.add(log_file_path, level='DEBUG',
                        format="[<green>{time:YYYY-MM-DD HH:mm:ss,SSS}</green>] "
                               "[{process.name}] "
                               "[{thread.name}] "
                               "[<cyan>{name}.{function}:{line}</cyan>] "
                               "[<level>{level}</level>] - "
                               "<level>{message}</level>",
                        rotation="1 MB")

    def get_logger(self):
        return self.logger

my_logger = MyLogger().get_logger()
```

# view.py
```python
def index(request):
    for i in range(1000):
        rand_num = randint(1, 10)
        if i % rand_num == 0:
            my_logger.info(f"This is an info msg. num = {i}, rand_num = {rand_num}.")
        else:
            my_logger.error(f"This is an info msg. num = {i}, rand_num = {rand_num}.")
    return JsonResponse({"code": 200, "msg": "success", "result": [0, 1, 2]})

urlpatterns = [
    path("index", index)
]
```

**Comment by knightwk** [comment]
During breakpoint debugging, I found that the code was executed to 208 lines, instead of downward execution, but jumped to 184 lines, resulting in the failure of renaming and an error.
![image](https://user-images.githubusercontent.com/43836437/208283172-8be2a35a-6c1c-4b98-9121-3191f0fe289e.png)

**Comment by Delgan** [comment]
Please, share the reported error as raw text instead of a screenshot so I can translate and understand it.

The "basic functions" work fine, they are all well tested and used without troubles by many users. Most likely it's an issue with handlers being added multiple times or file being already opened for whatever reason.

Also if you're able to provide a minimal reproducible example, including Django setup, that would help. The issue might also be related to usage of `multiprocessing` on Windows.

**Comment by knightwk** [comment]
I have updated the error description, please check it.

Please clone the warehouse directly for relevant minimized test code: 
[loguru_and_django_test](git@github.com:knightwk/loguru_and_django_test.git)

**Comment by knightwk** [comment]
I have updated the error description, please check.
Please use the repository directly for relevant minimum test cases: [loguru_and_django_test](https://github.com/knightwk/loguru_and_django_test.git)

**Comment by Delgan** [comment]
@knightwk  Thanks for the fully reproducible example, it helps a lot.

I was able to reproduce and investigate the issue. Actually, the bug also happens with standard `logging` while using `FileRotatingHandler`. According to [this StackOverflow answer](https://stackoverflow.com/a/23420005/2291710), this happens because Django starts two processes and re-execute the code in `settings.py`. Consequently, the file handler is added twice, and conflicts occur when they are rotated at the same time. This can be also observed by using `logger.add(f"{random.randrange(100)}.log")`: two files are created.

A proposed solution is to use `python manage.py runserver --noreload` so that Django do not spawn two subprocesses.
An alternative solution would be to arrange code to avoid the same code to be executed twice, but I don't know if it's possible.

**Comment by knightwk** [comment]
@Delgan Thank you, I've fixed it by adding --noreload.
I know that Djangos development server loads settings.py twice, but I don't know that it loads two child processes directly. Thank you very much.
