### ISSUE TITLE
Proper way to intercept stdlib logging

### ISSUE THREAD

**Issue by Fak3** [Delgan/loguru#78]
The method to intercept stdlib logging in the readme sometimes gives wrong originator of the log message. Currenty in the readme it is recommended to set depth=6:
```python
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Retrieve context where the logging call occurred, this happens to be in the 6th frame upward
        logger_opt = logger.opt(depth=6, exception=record.exc_info)
        logger_opt.log(record.levelno, record.getMessage())
```
But this fails for simple program:
```python
import logging

logging.basicConfig(level='INFO')
logging.getLogger(None).addHandler( InterceptHandler())

logging.warning('123')
```
The originator of the message is wrongly displayed as `logging:warning:1979`:
```
2019-04-02 14:24:04.558 | WARNING  | logging:warning:1979 - 123
```

Similar issue: #69

**Comment by Delgan** [comment]
Thanks for the report, I was not aware of this "bug".

This happens when using module function [`logging.warning()`](https://docs.python.org/3/library/logging.html#logging.warning) rather than the method [`logger.warning()`](https://docs.python.org/3/library/logging.html#logging.Logger.warning).

In such case, there is [one more stack needed](https://github.com/python/cpython/blob/176d26364bb67801fa522f52f20cbe44420d6942/Lib/logging/__init__.py#L2055) to reach the call site. That means that using `7` as the magic number would work here, but of course that would break others standard `logger.log()` calls.

I don't know yet what would be a proper workaround. I guess using such magic number which relies on implementation details like this has downsides as shown here. An alternative would be to manually update the Loguru's record dict (using the future `.patch()` method) but this is less elegant.

**Comment by D3f0** [comment]
Somewhat related, I've had to change the `levelno` to `levelaname` to make the level be respected. Otherwise I got `Level <number>` in the logging output, rather than `TRACE`, `DEBUG`, etc.

**Comment by Delgan** [comment]
@D3f0 Yes, I noticed that too. Using `levelname` seems correct **but** it will raise an exception if the `logging`'s level is not registered in `loguru` (try `logging.log(33, "Boom")` for example), so it should be used with care.

**Comment by guyskk** [comment]
The logging module use `_srcfile` [logging/__init__.py#L177](https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L177) to find caller frame, I think it's the correct way. `depth` is not enough to determine the caller.

**Comment by Delgan** [comment]
@guyskk @Fak3 What about replacing `depth=6` with:

```
depth = next(i for i, f in enumerate(inspect.stack()[1:]) if f.filename != logging.__file__) + 1
```

It actually mimics the [`findCaller()`](https://github.com/python/cpython/blob/5dbe0f59b7a4f39c7c606b48056bc29e406ebf78/Lib/logging/__init__.py#L1504) function used by the standard `logging` module (`_srcfile` is "private" so I used `__file__` which should be the same).

It's a little bit cumbersome, there is maybe a shorter and more elegant way to write that. At least, it seems to solve the problem and should always return the correct depth, no mater if `logging.info("Foo")` or `logging.getLogger().info("Bar")` is used.

**Comment by guyskk** [comment]
How about get caller information from `logging.LogRecord` object?

**Comment by Delgan** [comment]
@guyskk This is possible but complicated because the internal structure used by `logging` and `loguru` are fundamentally different. For example, `logging`'s record exposes `fileName` and `filepath` attributes while `loguru` encapsulates them in one `file` object with `name` and `path` attributes. 

So it would require to extend the Loguru's api with a new method in charge of converting a `logging`'s record and re-emitting it to the `loguru`'s handlers. I implemented this in the past but I was not happy with that, in the end I prefer not to add method associated with standard `logging` (it complicates both API and code base for a minor feature related to an external module), as long as there exists an alternative way achieving the same thing.

**Comment by Delgan** [comment]
I updated the `InterceptHandler()` snippet in the Readme:

```python
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())
```

It should now retrieve the correct frame information and level name. This is not very elegant, but this is the best I could do. See also my comment: https://github.com/Delgan/loguru/issues/154#issuecomment-548761213

**Comment by matthewlloyd** [comment]
If you are using Sentry and seeing `sentry_sdk.integrations.logging:sentry_patched_callhandlers:83` as the caller in your logs, just change the `while` line above to:

```python
import sentry_sdk.integrations.logging

# ...

        while frame.f_code.co_filename in (logging.__file__, sentry_sdk.integrations.logging.__file__):
```

This is needed even if you haven't explicitly enabled Sentry's logging integration, because Sentry enables it by default.
