### ISSUE TITLE
Handle multiple parameters, print() way

### ISSUE THREAD

**Issue by mrx23dot** [Delgan/loguru#786]
`logger.error("That's it, beautiful and simple logging!",  345)`
gives the same output as 
`logger.error("That's it, beautiful and simple logging!")`
ignoring 2nd parameter.

there is no reason why we could not do **kwargs** and handle everything as string, like if it was print('text', number, 'text)

Would help with transitioning from print to this lib, simply by replacing function name.

loguru==0.6.0
py 3.7

**Comment by Delgan** [comment]
Hi.

Loguru message formatting is designed to look like `str.format()` more than `print()`.

It's not something we can change without introducing breaking changes, and I think it's not desirable because `str.format()` is much more powerful than `print()` anyway. For example, `logger.format("Binary number: {:08b}", binary)` would not be as straightforward using `print()` style.

However, I plan to add a way to customize formatting eventually.
