### ISSUE TITLE
Logger.contextualize doesn't seem to work with `loop.run_in_executor`

### ISSUE THREAD

**Issue by vamshiaruru-virgodesigns** [Delgan/loguru#792]
Hi all, I imagine this is very niche. But it'd be great if you could help me out. The following snippet reproduces the issue:

```python
import asyncio
from loguru import logger

def configure_logger(queue: str):
    # todo: Json logging
    logger_format = (
        "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | "
        "<level>{level}</level> | "
        "<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> | "
        "[message_id: {extra[message_id]}] [worker_id: {extra[worker_id]}] [queue: {extra[queue]}] "
        "- <level>{message}</level>"
    )
    logger.configure(extra={"message_id": "", "worker_id": "", "queue": ""})
    logger.remove()
    logger.add(sys.stderr, format=logger_format)
 
 configure_logger()
 
 def sync_func():
    logger.info("In div")


async def testing():
    logger.info("Testing")
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, lambda: sync_func())


async def test():
    with logger.contextualize(worker_id="test", message_id="test"):
        await testing()


if __name__ == "__main__":
    asynico.run(test())
    
```
This gives output like:
```
2023-01-28 19:15:24.997 | INFO | ameyam_side_effects.workers.consumer.run:testing:79 | [message_id: test] [worker_id: test] [queue:] - Testing
2023-01-28 19:15:24.997 | INFO | ameyam_side_effects.workers.consumer.run:sync_func:75 | [message_id: ] [worker_id: ] [queue:] - In div
```

As you can see, the `In div` log line doesn't have the context variables. I imagine this is happening because of some funky internals of `run_in_executor`? While this example is very bare bones, the actual usecase is that some times I need to execute sync function in async functions, and I'd love to be able to pass context. What do you recommend?

Thanks!

**Comment by vamshiaruru-virgodesigns** [comment]
As a follow up, is there way to get what the context vars are from the logger instance? In the worst case, I can explicitly pass the logger context into the function and do `with logger.contextualize` again.

**Comment by Delgan** [comment]
Hi. :)

Thanks for the reproducible example.

The problem with `contextvars` (used internally by Loguru) not being propagated with `run_in_executor()` has been discussed in this Python bug ticket: [issue34014](https://bugs.python.org/issue34014).

It was closed as "wontfix", but an alternative has been implemented in Python 3.9. Instead of `loop.run_in_executor(None, func)` you can use [`asyncio.to_thread(func)`](https://docs.python.org/3/library/asyncio-task.html#asyncio.to_thread).

```python
async def testing():
    logger.info("Testing")
    loop = asyncio.get_running_loop()
    return await asyncio.to_thread(lambda: sync_func())
```

It should work as expected. :+1: 

I'm not planning to make the internal context used by Loguru publicly available, I don't think it should be part of the library API.

**Comment by vamshiaruru-virgodesigns** [comment]
Thanks @Delgan , `asyncio.to_thread` works! I'm closing this issue now :)

**Comment by ahmedmedo256** [comment]
#797
