### ISSUE TITLE
Retention callable function

### ISSUE THREAD

**Issue by Wang-kk714** [Delgan/loguru#798]
Hi 

I found the `retention callable` parameter description below:

> The retention occurs at rotation or at sink stop if rotation is None. Files are selected if they match the pattern "basename(.*).ext(.*)" (possible time fields are beforehand replaced with .*) based on the sink file. This parameter accepts:
> 
> a [callable](https://docs.python.org/3/library/functions.html#callable) which will be invoked before the retention process. It should accept the list of log files as argument and process to whatever it wants (moving files, removing them, etc.).

**Could you please share a brief example for that retention callable function?** (see the rotation callable function example on [code snippets](https://loguru.readthedocs.io/en/stable/resources/recipes.html#rotating-log-file-based-on-both-size-and-time) works well, but as a junior😢 my attempts for retention fail...)

stick my question here(not sure the other general retention parameter could work but my attempts failed..)
- `/INFO` folder will store all the info level files
- the log file will rotate every day but not cleaned immediately
- hope clean 7 days aged file under `/INFO`

**Comment by Delgan** [comment]
Hi. :)

The retention callable receive a list of file paths whose name matches the one of your configured sink.
For example, if you configured the sink so that it rotates every night, the list will progressively be filled with an additional file (assuming they are not deleted by your `retention` function).

```python
def retention(filelists):
    for file in filelists:
        if is_older_than_7_days(file):
            remove_file(file)

logger.add("file.log", rotation="1 day", retention=retention)
```

**Comment by Wang-kk714** [comment]
> Hi. :)
> 
> The retention callable receive a list of file paths whose name matches the one of your configured sink. For example, if you configured the sink so that it rotates every night, the list will progressively be filled with an additional file (assuming they are not deleted by your `retention` function).
> 
> ```python
> def retention(files_list):
>     for file in files_list:
>         if is_older_than_7_days(file):
>             remove_file(file)
> 
> logger.add("file.log", rotation="1 day", retention=retention)
> ```

Thank you for the example! helps a lot:)
but I'm afraid if the application done or even on the RollingUpdate, will that `file_list` disappear?

**Comment by Delgan** [comment]
@Wang-kk714 When you re-start the application, the 1st time the `retention` function is called, the list will normally not be empty and will contain the logs generated when the application previously ran. This works because Loguru does not actually "store" the list of files rotated during its execution, but instead search files using pattern matching. For example, if your file is `"file.log"`, Loguru will rename file to `"file.{current_date}.log"` during rotation, so when retention is called, it the list will contain all files matching the `"file.{current_date}.log"` name.

**Comment by Wang-kk714** [comment]
> @Wang-kk714 When you re-start the application, the 1st time the `retention` function is called, the list will normally not be empty and will contain the logs generated when the application previously ran. This works because Loguru does not actually "store" the list of files rotated during its execution, but instead search files using pattern matching. For example, if your file is `"file.log"`, Loguru will rename file to `"file.{current_date}.log"` during rotation, so when retention is called, it the list will contain all files matching the `"file.{current_date}.log"` name.

Thank you for explanation. delicate design!!!
