### ISSUE TITLE
Use color-tags within log messages

### ISSUE THREAD

**Issue by sn0opy** [Delgan/loguru#80]
Hey, I'd like to suggest an enhancement to use the existing color tags not just within the logger formatting, but also within single log messages. Example:

`logger.info("This could be a <blue>nice</blue> feature")`

**Comment by Delgan** [comment]
Hey @sn0opy, thanks for your suggestion!

Actually, this is already possible, you just have to use [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) like this:

```python
logger.opt(ansi=True).info("This is a <blue>nice</blue> feature, isn't it?")
```

The `opt()` method configures logs messages rather than handlers. The coloration has been made optional for several reasons: explicit is better than implicit, no surprising behavior if someone log raw HTML tags, colors per message like this are probably not needed globally, and this avoid having to parse the string for each logged message. However, if you want this automatically, you can always do `logger = logger.opt(ansi=True)` at the start of your script.

**Comment by sn0opy** [comment]
Totally fine with that solution. Thanks!

**Comment by j4hangir** [comment]
This was rather difficult for me to come by, maybe should be explained more clearly in the docs that if you need color, this is the way.

**Comment by amurgit** [comment]
> ansi ([bool](https://docs.python.org/3/library/functions.html#bool), optional) – Deprecated since version 0.4.1: the ansi parameter will be removed in Loguru 1.0.0, it is replaced by colors which is a more appropriate name.

logger = logger.opt(color=True)
