### ISSUE TITLE
Use Python's __call for alternative logging level methods

### ISSUE THREAD

**Issue by sn0opy** [Delgan/loguru#82]
Hey,

for a project, I added several debug levels for better debugging nuances / reduce spam, so I can start my application with `-v` or `-vvv` for more detailed debugging levels.

```python
"levels": [
    {"name": "DEBUG2", "no": 9, "color": "<blue>"},
    {"name": "DEBUG3", "no": 8, "color": "<blue>"},
    {"name": "DEBUG4", "no": 7, "color": "<blue>"},
    {"name": "DEBUG5", "no": 6, "color": "<blue>"}
]
```

Unfortunately, the way the custom levels work, instead of using `logger.debug2()` you have to use `logger.log("DEBUG2", msg)`. This kinda destroys the consitency in the code where I still want to use `.info()`, `.debug()` etc.

What about to use Python's `__call()` to create those level specific methods dynamically and throw an exception (or even add a configurable fallback) if a certain level wasn't configured.

**Comment by Delgan** [comment]
> What about to use Python's __call() to create those level specific methods dynamically

Are you referring to the PHP `__call()` method? I think the Python equivalent would be `__getattr__()`.

I understand that this can be useful, and I would myself be bothered of typing `logger.log("foo", "My message")` each time I wish to use my custom log, but this is way too magic for my tastes. I think the appropriate method should be explicitly set by the user. 

```python
def foo(message, *args, **kwargs):
    logger.opt(depth=1).log("foo", message, *args, **kwargs)

logger.foo = foo

logger.foo("Logging with foo level")
```

I should add this snippet to the documentation, though.

**Comment by sn0opy** [comment]
Yeah, I had PHP's `__call()` in mind. Looks like I've mixed that with `__call__()`: https://docs.python.org/3/reference/datamodel.html#emulating-callable-objects 

Your example describes quite the way I had in mind already, but I preferred to stick to loguru's `logger` instead of using my own module.

To make this "less" magic, one could add a seperate parameter which will then make them available. So by default, this feature is disabled.

**Comment by tuchandra** [comment]
> I understand that this can be useful, and I would myself be bothered of typing `logger.log("foo", "My message")` each time I wish to use my custom log, but this is way too magic for my tastes. I think the appropriate method should be explicitly set by the user.
> 
>  [code snipped]
> 
> I should add this snippet to the documentation, though.

I appreciate your response here, as I have run into a similar problem that required me to monkeypatch the logger. What do you recommend for when multiple files are making use of logging? Having the `def foo() ... logger.foo = foo` in multiple files increases code duplication.

My current solution is to have a `log_helper` module within my project's utils directory; this file can be summarized as:

```python
from loguru import logger

def get_logger(): return logger

def foo(): ...
def bar(): ...

logger.foo = foo
logger.bar = bar
```

and I access it using `logger = log_helper.get_logger()` in my other files. I was wondering if you had a better suggestion on how to do this.

**Comment by Delgan** [comment]
> Yeah, I had PHP's `__call()` in mind. Looks like I've mixed that with `__call__()`, which is why I thought this is available in Python as well. (https://docs.python.org/3/reference/datamodel.html#emulating-callable-objects)

Yep, but Python `__call__()` is for making object acting like a function which would otherwise raises an error `TypeError: 'X' object is not callable`. The problem here is more about accessing an attribute which does not exist, `logger.debug2` would raise `AttributeError: 'Logger' object has no attribute 'debug2'`, and this is why we need `__getattr__()` to dynamically provide the missing logging method.

> Your example describes quite the way I had in mind already, but I preferred to stick to loguru's `logger` instead of using my own module.

You can still use the loguru's `logger`, can't you? If you set up your custom logging methods at the same time as you create your new levels, these methods should be available across all your modules importing the `logger`, because this is the same Python object, so it's modified globally.

> To make this "less" magic, one could add a seperate parameter which will then make them available. So by default, this feature is disabled.

It is true that it looks less magical, but I prefer to avoid adding methods dynamically. There are many edge cases. For example, what should be the method generated for level `"FOOBAR"`: `.foobar()` or `.FOOBAR()`? If the level is `"level with spaces"` or `"123abc"`, then the corresponding method name would be invalid. If the level is `"add"` or `"bind"`, it would override existing logger method.
This is way I prefer to let the responsibility of managing custom levels to the end user. I think it's not too much boilerplate.

**Comment by Delgan** [comment]
Hi @tuchandra.

I think you should be able to define and add the new level method in just one file, and that should work across all your modules without needing to repeat the process in each of them. This is possible because when you import the `logger` from `loguru`, this is actually the same Python object which is shared. So, if a method has been added to this object in one of your file, this method is also available in your others files.

Of course, you need to make sure that the method is added before there is any other module actually using it.

The sole problem may occur with `opt()` and `bind()`, because these methods create a new `logger` object. So, I would rather suggest to patch the `Logger` class rather than the instance:

```python
def foo(_, message, *args, **kwargs):
    logger.opt(depth=1).log("foo", message, *args, **kwargs)

logger.__class__.foo = foo
```

**Comment by tuchandra** [comment]
Thanks for the response! That makes sense; it sounds like that code should go into an __init__.py or somewhere similar.

**Comment by Delgan** [comment]
Although this feature does not come "built-in" with Loguru for reasons previously discussed, I added a [code recipe](https://loguru.readthedocs.io/en/stable/resources/recipes.html#using-logging-function-based-on-custom-added-levels) to the documentation demonstrating how this can be achieved. ;)
