### ISSUE TITLE
Wouldn't it make more sense to use TRACE for exceptions instead of ERROR?

### ISSUE THREAD

**Issue by pawamoy** [Delgan/loguru#83]
When an exception occur, I use `logger.opt(exception=True).trace(e)` to print it. Since it's called "Traceback", I was expecting `logger.exception` to use TRACE level instead of ERROR.

In my program, I only print exceptions when the user selected the lowest level: TRACE, because it can get a lot more verbose.

What do you think?

If you still want to keep the ERROR level for `logger.exception` (for compatibility or other reasons), I completely understand, and doing `logger.opt(exception=True).trace(e)` instead is not so painful, but maybe this could be extended to be configurable? Something like setting the level to use for exceptions, defaulting to its current ERROR?

**Comment by Delgan** [comment]
Hello @pawamoy.

You raise an interesting point. I think the "trace" in "Traceback" and the "trace" in "logger.trace()" does not have exactly the same purpose, which may lead to confusion.

The `trace` level is weaker than the `debug`, yet as a developper I want to see the full traceback when an exception occurs even if my application is running in "debug", because this it is much helpful. Basically, `logger.exception()` print the traceback with a "error" level because this is what is done by the standard `logging` library, and doing otherwise would be too surprising in my opinion.

I think I could add an environment variable: `LOGURU_EXCEPTION_LEVEL` to determine which level severity should be used by the `logger.exception()` method.

**Comment by pawamoy** [comment]
> Basically, logger.exception() print the traceback with a "error" level because this is what is done by the standard logging library, and doing otherwise would be too surprising in my opinion.

I have nothing to say against this! Totally agree.

> yet as a developper I want to see the full traceback when an exception occurs even if my application is running in "debug"

Well, I feel the exact same way, but with trace instead of debug :)  Since you introduced trace level, I expect to take advantage of it and use it this way.

About a LOGURU_EXCEPTION_LEVEL variable, it's not exactly what I need because it puts the power in the end user's hands: not in the developer's one: I cannot enforce TRACE level unless I override the user's choice by setting the env var from within my code, which seems to be... anti-pattern?

**Comment by Delgan** [comment]
> About a LOGURU_EXCEPTION_LEVEL variable, it's not exactly what I need because it puts the power in the end user's hands, not in the developer's one: I cannot enforce TRACE level unless I override the user's choice by setting the env var from within my code, which seems to be... anti-pattern?

Oops, that would indeed be a terrible decision to add an environment variable while it's not configurable programmatically. Thanks for preventing me to do such mistake!

Well, then I prefer not to complicate the API with too much configuration options, especially considering that there exists a quite straightforward workaround using `.opt()`.

Thank you for being understanding. 😄
