### ISSUE TITLE
Document tradeoffs of using `enqueue=True`

### ISSUE THREAD

**Issue by micimize** [Delgan/loguru#836]
The docs do a good job of saying when `enqueue=True` should probably be used, but don't go into much detail on why one might want to avoid it (or if there really aren't any)

The main potential issue I've seen/thought of is slight offset or potential interleaving with main-thread output (https://github.com/Delgan/loguru/issues/571#issuecomment-1016455946).

Questions I've thought of related to this:
1. How much overhead does the worker thread incur & does it even matter? I know [asyncio runtime overhead can be significant](https://stackoverflow.com/a/55766474/2234013) but haven't dug into the details.
2. How much of a risk really is the interleaving issue? I.e, is it possible that `logger.info('foo bar'); print('baz')` can log `foobaz bar`?
3. Can `enqueue=True` result in lost logs in some edge cases where `enqueue=False` would not? For example `SIGKILL` of the main thread.

**Comment by Delgan** [comment]
Hi @micimize.

I find most of the downsides to be common sense but indeed, perhaps the doc would benefit from mentioning them.

To address your questions:

1. There is obviously some overhead as `enqueue=True` implies starting one additional thread to process the message in the background. Because of the Python GIL, everything runs on the same CPU core, and the context switch will induce performance penalties. I expect them to be negligible compared to the time to create the log record itself, though. I'm in the process of redesigning the internal implementation of `enqueue=True`, so making measurements is of no interest right now, but maybe I could share a comparison with you after that. 
2. It depends on the buffering mode of the stream. The `sys.stderr` is stream-buffered, so you won't see two messages interleaving with each other if they are only one-line length. However, if a multi-line `str` was to be wrote on `sys.stderr` (like the stacktrace of an exception), then it can happens in theory. I don't know how likely it is, but I don't think it would happen very often. In particular, I know `sys.stderr` uses a lock internally, so I suppose it can only happen when `multiprocessing` is involved. In such case, write calls must be synchronized, which is done by specifying `enqueue=True`. In this situation, writing to `sys.stderr` by other means should be discouraged as it could cause the stream to be accessed concurrently and the output to be interleaved.
3. Yes, if the main thread is abruptly killed, the pending messages won't be logged. The same problem applies if a child process stops without first calling `logger.complete()`: there would be no guarantee that the messages have been fully transferred, and they could be lost.

**Comment by anentropic** [comment]
I get this error:
```
python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

when I add `enqueue` to my handler:
```python
logger.configure(handlers=[
    {
        "sink": sys.stderr,
        "format": "<light-black>{message}</light-black>",
        "enqueue": True,
    }
])
```

It did fix my interleaving problem though

My code is using multiprocessing (a parent proc and a child proc communicating via Pipe)

I tried adding `logger.complete()` to the child just before it closes the connection at end of function, and then to the parent too, but I still get the warning.

**Comment by Delgan** [comment]
@anentropic I need to know your operating system and see your full code to help you. It can be related to the method used to start process (`"spawn"` or `"fork"`) and whether or not the `logger` object is inherited by the child process.

**Comment by anentropic** [comment]
@Delgan thanks, I'm on macOS

using the default method, which is `spawn` on this platform I believe

**Comment by Delgan** [comment]
@anentropic Because of the `"spawn"` start method, you have to pass the `logger` object when creating a `Process()` or using `map()`, this is called "inheriting". Then, in the child process, you have to use the inherited `logger`, not the one resulting from the `import` statement.

See documentation: [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument).

Otherwise, the handler won't be synchronized properly in the different processes.

**Comment by anentropic** [comment]
this still gave me the warning:

```python
import multiprocessing
from loguru import logger

def my_process(logger_):
    logger_.info("Executing function in child process")
    logger_.complete()

if __name__ == "__main__":
    process = multiprocessing.Process(target=my_process, args=(logger, ))
    process.start()
    process.join()

    logger.info("Done")
```

(I did not have the "sink is not picklable" problem mentioned for Windows)

What did get rid of the warning is doing this:

```python
import multiprocessing

def my_process():
    from loguru import logger
    logger.configure(...)

    logger.info("Executing function in child process")
    logger.complete()

def main():
    from loguru import logger
    logger.configure(...)

    process = multiprocessing.Process(target=my_process, args=())
    process.start()
    process.join()

    logger.info("Done")

if __name__ == "__main__":
    main()
```

but it's getting a bit ugly, and most of the time I don't have interleaving anyway, so have just disabled `enqueue` for now

**Comment by Delgan** [comment]
@anentropic For one thing, you're using `multiprocessing` without `enqueue=True` which can lead to unexpected behavior.

However, I don't think this is related to the `UserWarning` you're facing. There is some known problem with memory resources on MacOS: https://bugs.python.org/issue46391

This is also related to this issue: https://github.com/Delgan/loguru/issues/477
Using `multiprocessing.SimpleQueue()` seems problematic, but it will be replaced in the next Loguru version anyway.

**Comment by micimize** [comment]
@Delgan thanks for the thorough explanation. I think https://github.com/Delgan/loguru/issues/836#issuecomment-1492999969 is probably sufficient for explanation for those interested. I think the note about `logger.complete()` is especially salient/useful.

The pipe interleaving stuff is a fairly interesting topic generally (https://unix.stackexchange.com/a/476089/203864).

Will go ahead and close this :+1:
