### ISSUE TITLE
Debug issues

### ISSUE THREAD

**Issue by zhognli** [Delgan/loguru#840]
How can I configure loguru to display tensor shapes instead of tensor values in case of a bug? It is crucial to visualize the shape of the tensor rather than its values in the context of Deep Learning.

For example:
![2023-04-07_16-05](https://user-images.githubusercontent.com/127704612/230569147-a3f78d33-0ad2-4a39-9cd1-a1f494a051ba.png)

It's more intuitive to show the x.shape instead of the x.items().

**Comment by Delgan** [comment]
Loguru uses the `repr()` value of an object while displaying the stack trace. It seems the `tensor` object does not display its shape as part of its string representation, and that's why it's not visible here (or maybe it's truncated). 

Unfortunately, there isn't much we can do. You could maybe configure a different exception formatter if you know one that displays the `tensor` objects more appropriately: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).

I would rather advise to use a real debugger, or to add log messages in your code to explicitly display the size of tensors when they are created or modified.

**Comment by zhognli** [comment]
Thank you very much for your reply and suggestions.
