### ISSUE TITLE
Clarification about retention

### ISSUE THREAD

**Issue by mvanaltvorst** [Delgan/loguru#854]
Thanks for the great library! 

I am uncertain about a few points regarding `retention`. 

In the docs, I can find the following:

`The retention occurs at rotation or at sink stop if rotation is None. Files are selected if they match the pattern "basename(.*).ext(.*)" (possible time fields are beforehand replaced with .*) based on the sink file. This parameter accepts: ...`

It is unclear to me what a "sink stop" is, this is not clarified in the documentation. Furthermore, it is unclear to me what happens with the selected files. Are they deleted? 

Should I include the timestamp into the logger filename myself, or does loguru do this for me automatically?

It is also unclear to me what retention exactly does. Does it remove old files? Does it create a new file once the old file is older than x days?

It is also unclear to me why retention only takes a timedelta and not a filesize like `rotation` does.

I am sure I could figure out these things by diving into the code, however I thought it might be helpful to potentially include these points in the docs as well as I am sure I am not the only one confused. 

Thanks!

**Comment by Delgan** [comment]
Thanks for your feedback. I'll try to update the documentation according to the possible confusions you raised.

> It is unclear to me what a "sink stop" is, this is not clarified in the documentation.

Sink "stop" means when `logger.remove()` is called or when the program ends.

> Furthermore, it is unclear to me what happens with the selected files. Are they deleted?

This preliminary selection is used to sort out the log files that have most likely been created by the sink (during a rotation or a previous session) and the others unrelated files that exist in the folder. Selected files are sent to the function in charge of executing the "retention" process. They may or may not be deleted depending on the retention criteria.

> Should I include the timestamp into the logger filename myself, or does loguru do this for me automatically?

You can use `"file_{time}.log"` if you want to create a unique filename. During rotation, if the new-file to be created already exist (which happens if `"file.log"` was used), then Loguru will rename the existing file by appending a timestamp at the end of its name, thus avoiding the new file to overwrite the previous one.

> It is also unclear to me what retention exactly does. Does it remove old files? Does it create a new file once the old file is older than x days?

Yes, it removes old files base to the last time on which they were modified.
The `retention` does not create file, only `rotation` can do that.

> It is also unclear to me why retention only takes a timedelta and not a filesize like rotation does.

Because `retention` was initially designed to delete old files based on time only.
Technically, it could work with a file size, but the feature isn't built-in in Loguru.

**Comment by Delgan** [comment]
I updated the documentation.
