### ISSUE TITLE
How to reset the `elapsed` time?

### ISSUE THREAD

**Issue by Yura52** [Delgan/loguru#867]
I have a function `launcher` that runs the function `f` 100 times with different arguments. When entering the function `f`, I want the `elapsed` property to start from zero each of those 100 times. In other words, I want `f` to think that it is the "main" function and the process has just started. `.patch()` does not work for me, because other libraries will not have access to the patched logger.

P.S. I think this is a bad usage of logging overall, but my use case is not production-oriented, so I would like to achieve this somehow :) I am ready to call `logger.add` in `f` if needed. For example, is patching the elapsed time inside the `filter` function a viable solution?

**Comment by Delgan** [comment]
The `elapsed` value represents the time passed since the beginning of the program (similar to `relativeCreated` for standard logging). Therefore, it's not possible to reset it. 

The best solution would be to add your own argument to the record. If [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) is not enough, maybe you can consider using [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure)?

```python
import sys
import time
from loguru import logger
from datetime import timedelta

class LauncherTime:
    def __init__(self):
        self._start = time.time()

    def reset(self):
        self._start = time.time()

    @property
    def elapsed(self):
        return timedelta(seconds=time.time() - self._start)

launcher_time = LauncherTime()

logger.configure(
    extra={"launcher_time": launcher_time},
    handlers=[{"sink": sys.stderr, "format": "[{extra[launcher_time].elapsed}] {message}"}],
)

def f():
    launcher_time.reset()
    logger.info("Entering function")
    time.sleep(1)
    logger.info("Leaving function")

for _ in range(100):
    f()
```

**Comment by Yura52** [comment]
This is a great example, thank you!
