### ISSUE TITLE
Cannot disable loguru in cython build

### ISSUE THREAD

**Issue by senysenyseny16** [Delgan/loguru#875]
Hi,

I'm using Cython and loguru works but I can't manage (disable) logging:

```python3
from loguru import logger

logger.disable(<module_name>)
```

the above code works for source distribution and doesn't work with the binary (Cythonized) distribution.

Has anyone experienced this behavior?

**Comment by Delgan** [comment]
Hi @senysenyseny16.

Cython removes the stack frames, causing Loguru to access the wrong context when a message is logged. Therefore, the logged message is associated with an incorrect module name, and `disable()` cannot filter it properly.

I'm not aware of any possible workaround, unfortunately. :/

**Comment by senysenyseny16** [comment]
hi @Delgan.

Thanks for your reply :smiling_face_with_tear:

**Comment by Delgan** [comment]
Note that Cython compatibility with Loguru was improved by #1240.

Using `logger.disable(None)` should disable logs coming from Cython module.

The `logger.disable()` method takes as input the name of the `logger` to disable. Here, `None` is used because the logger within Cython modules has no name (due to the absence of available stack frame).
