### ISSUE TITLE
Why do you recommend to use f-string by default for formatting log-message?

### ISSUE THREAD

**Issue by thunderamur** [Delgan/loguru#878]
From README.md:
```python3
logger.info("If you're using Python {}, prefer {feature} of course!", 3.6, feature="f-strings")
```
But what do you think about that:
```python3
import sys

from loguru import logger

logger.remove()
logger.add(sys.stderr, level="INFO")

class Foo:
    def __repr__(self):
        print("useless formatting work caught")
        return self.__class__.__name__

foo = Foo()

print("format-style")
logger.debug("foo={foo}", foo=foo)

print("f-string")
logger.debug(f"{foo=}")
```

**Comment by Delgan** [comment]
Hi.

Using f-strings for formatting log messages is recommended due to their popularity and convenience. While using arguments can avoid evaluating possibly expensive `__repr__()` methods, the overhead is probably negligible for most common logged objects.

I suppose using f-string will likely be preferred by most users, although using arguments has performance advantages at the cost of a little more code verbosity.

**Comment by thunderamur** [comment]
Delgan, thanks for your answer.
