### ISSUE TITLE
unexpected behavior writing to stderr

### ISSUE THREAD

**Issue by oz123** [Delgan/loguru#89]
First, I really like the idea behind loguru.

Why is the default logger logging to stderr? and not stdout? Can you add a paragraph explaining this choice?

**Comment by Delgan** [comment]
Hello @oz123.

Actually, I made this choice without thinking too much about this, mainly because logging to `stderr` rather than `stdout` seems to be a widely accepted convention.

For example, [`logging.basicConfig()`](https://docs.python.org/3/library/logging.html#logging.basicConfig) and [`logging.StreamHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler) defaults to `stderr`. Also, the POSIX standard specifies that `stderr` is the correct stream for "diagnostic output".

The main compelling case in favor or logging to `stderr` in my opinion is that is avoid mixing the actual output of your application with debug information of your logs. Consider for example pipe-redirection like `python my_app.py | other_app` which would not be possible if logs were emitted to `stdout`.

**Comment by oz123** [comment]
@Delgan, thanks for taking the time to answer this question. I really appreciate it. This detailed answer is really helpful.

**Comment by Delgan** [comment]
Sure, no problem. 👍 

I will add some words about this choice in the documentation.

**Comment by Delgan** [comment]
I added [a paragraph](https://loguru.readthedocs.io/en/stable/resources/migration.html#fundamental-differences-between-logging-and-loguru ) near the top of the documentation, explaining rational behind this choice. :)
