### ISSUE TITLE
Question about log rotation in Docker swarm.

### ISSUE THREAD

**Issue by ggree1** [Delgan/loguru#893]
Thanks for the great library first.
This might be a silly question, but I'm writing because I need help with log rotation in a Docker Swarm environment. 

My application is deployed on Docker Swarm, and I have multiple replicas with multiple uvicorn workers running. 
When the log rotation occurs, each worker seems to have its own logging handler, resulting in separate rotations and multiple log files with the same date timestamp like below.

-rw-r--r-- 1 root   root   59645 Jun 14 10:23 access.2023-06-14_08-55-02_646537.log
-rw-r--r-- 1 root   root    6919 Jun 14 10:20 access.2023-06-14_09-03-02_585945.log
-rw-r--r-- 1 root   root    5326 Jun 14 10:20 access.log
-rw-r--r-- 1 root   root   19498 Jun 14 10:20 application.2023-06-14_09-52-38_336260.log
-rw-r--r-- 1 root   root     600 Jun 14 10:20 application.2023-06-14_02-31-26_685447.log
-rw-r--r-- 1 root   root    1797 Jun 14 10:20 application.log

I tried checking the existence of the log files for the respective date before performing the rotation, 
but it doesn't work as expected. 

Is there any idea to handle this situation?

**Comment by Delgan** [comment]
Hi @ggree1.

Unfortunately I'm not very familiar with Docker Swarm not Uvicorn.
How are parametrized the configured file handlers?

If I'm not mistaken, each Uvicorn worker run in a separate process. As you understood, that implies each worker has its own file handler. This is not visible at first, as every handler writes to the same `access.log` file. However, when rotation occurs, every file handler will create a new file to avoid overwriting the one already created by one of the others processes.

The solution to this problem is to ensure that the various processes are synchronized with each other, and that they all log to the same handler. This is usually done with `enqueue=True` argument ([see documentation](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)). Unfortunately, this requires the `logger` instance to be shared among the Uvicorn processes, which is not easily doable as far as I know.

I'm working on a possible workaround for this case, but as for now, I would suggest to configure one different file for each worker, or to send logs to an external process like `journald`.

**Comment by ggree1** [comment]
@Delgan 
Thanks for the reply.

```python
logger.add(
            config.LOG_DIR + "/access.log",
            rotation=Rotator(log_max_size, log_rotate_time, "access").should_rotate,
            retention=retention,
            format=formatter,
            level=logging_level,
            enqueue=True,
        )
        logger.add(
            config.LOG_DIR + "/application.log",
            rotation=Rotator(log_max_size, log_rotate_time, "application").should_rotate,
            retention=retention,
            format=formatter,
            level=logging_level,
            enqueue=True,
        )

class Rotator:
    def __init__(self, str_size: str, str_time: str, file_name: str):
        self._size = string_parser.parse_size(str_size)
        self.file_name = file_name
        at = string_parser.parse_time(str_time)
        now = datetime.now()
        today_at_time = now.replace(hour=at.hour, minute=at.minute, second=at.second)
        if now >= today_at_time:
            self._next_rotate = today_at_time + timedelta(days=1)
        else:
            self._next_rotate = today_at_time

    def should_rotate(self, message, file):
        file.seek(0, 2)
        if file.tell() + len(message) > self._size:
            return True
        if message.record["time"].timestamp() >= self._next_rotate.timestamp():
            self._next_rotate += timedelta(days=1)
            return True
        return False
``` 

My handler configuration is like above.

As you mentioned, it seems that resolving the issue would require separate log collection and centralization through Docker logs.

When logging with Logback in Java, I had no problems with rotation across multiple instances. You might find it helpful to refer to that.

Thank you once again for your thoughtful response.

```
<appender name="File" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>${LOG_PATH}.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
      <fileNamePattern>${LOG_PATH}_%d{yyyy_MM_dd}_%i.log</fileNamePattern>
      <maxFileSize>50MB</maxFileSize>
      <maxHistory>10</maxHistory>
      <totalSizeCap>3GB</totalSizeCap>
    </rollingPolicy>
    <encoder>
      <pattern>${LOG_PATTERN}</pattern>
    </encoder>
  </appender>
  

-rw-r--r--    1 root     root      13941026 Jun 16 01:48 application.log
-rw-r--r--    1 root     root      30920140 Jun  6 14:59 application_2023_06_06_0.log
-rw-r--r--    1 root     root      30930894 Jun  7 14:59 application_2023_06_07_0.log
-rw-r--r--    1 root     root      30920140 Jun  8 14:59 application_2023_06_08_0.log
-rw-r--r--    1 root     root      30930894 Jun  9 14:59 application_2023_06_09_0.log
-rw-r--r--    1 root     root      30917896 Jun 10 14:59 application_2023_06_10_0.log
-rw-r--r--    1 root     root      30928650 Jun 11 14:59 application_2023_06_11_0.log
-rw-r--r--    1 root     root      30917896 Jun 12 14:59 application_2023_06_12_0.log
-rw-r--r--    1 root     root      30917896 Jun 13 14:59 application_2023_06_13_0.log
-rw-r--r--    1 root     root      30928650 Jun 14 14:59 application_2023_06_14_0.log
-rw-r--r--    1 root     root      30920140 Jun 15 14:59 application_2023_06_15_0.log
```

**Comment by Delgan** [comment]
Thanks for sharing about `Logback`, I'll take a look. :+1:
