### ISSUE TITLE
Custom levels

### ISSUE THREAD

**Issue by muenchenscott** [Delgan/loguru#895]
Loguru Version 0.7.0

First off, THANK YOU! Loguru is a great Python logging library. And secondly, thanks for any advice you can offer here.

My question relates to the 'non-standard' but 'common enough' levels that are pre-configured: TRACE  and SUCCESS.
I use 3 sinks in this wonderful logging setup: stderr, logfile, and a BetterStack Logtail_Handler for web-based log management.

I've customized the levels using the loguru.logger.level(name='', icon='') function. (I am ignoring the no and color for the sake of brevity) The stderr and logfile reporting is fine (albeit I don't have the icon in my logfile format). Logtail works great too, BUT I get crazy Level names for TRACE and SUCCESS. They get logged as 'LEVEL 5' and 'LEVEL 25' and I don't know where the disconnect with logtail is. The other log information in the record is coming through just fine.

Except from stderr/console:
2023-06-16 05:09:42.840 | TRACE    | loglue:test_logging():212  ♾️ A trace message.
2023-06-16 05:09:42.844 | SUCCESS  | loglue:test_logging():215  ☘️ A success message.
2023-06-16 05:09:42.845 | WARNING  | loglue:test_logging():216  ⚠️ A warning message.

Excerpt from logtail log:  
2023-06-16 05:09:42.840 [testy] [LEVEL 5] 5424 22804 loglue.py 212  | test_logging() | A trace message.
2023-06-16 05:09:42.844 [testy] [LEVEL 25] 5424 22804 loglue.py 215  | test_logging() | A success message.
2023-06-16 05:09:42.845 [testy] [WARNING] 5424 22804 loglue.py 216  | test_logging() | A warning message.

I really appreciate your time and advice.
👍

**Comment by Delgan** [comment]
Hi @muenchenscott, glad you appreciate Loguru. :)

Basically, there are two possible reasons why `"Level 5"` instead of `"TRACE"` appears in the logs:
- when using `logger.log(5, "Some message")`: Loguru associates a level name with a severity number, but not the reverse (because multiple level names could share the same severity). Therefore, when a integer instead of a string is used as the level,  Loguru interprets this as an "anonymous" level and simply displays `"Level X"`.
- when using handlers from the standard `logging` library, the logged record needs to be converted. This is done using the level severity number from Loguru. Contrary to Loguru, the standard `logging` library will try to match the severity to a level name. It therefore works well for levels that are common to both libs, Loguru can emit a standard record with `level` being `30` and it'll be formatted by standard library as `"WARNING"`. However, when converting a level that is not available in the standard library like `5` for `"TRACE"` or `25` for `"SUCCESS"`, the standard handler will not be able to find the name of the corresponding level and will falback to `"Level X"`.

I guess the second case applies to you, because Logtail uses a handler from the standard library. A possible workaround is to add `"TRACE"` and `"SUCCESS"` to the standard library using [`logging.addLevelName()`](https://docs.python.org/3/library/logging.html#logging.addLevelName). :+1:

**Comment by muenchenscott** [comment]
Thank you Delgan. As you surmised, option 2 would be the most relevant, as I'm not using the severity number in the logger.log(). 

That's an interesting situation and I do respect your design considerations.  I've been trying to keep my module free of the built-in logging library but it might be worth trying to isolate/limit it to a align_level_names() function. Will let you know if I have any success worth writing about!
:)  Peace.
