### ISSUE TITLE
Log to file but not to terminal

### ISSUE THREAD

**Issue by shadowrylander** [Delgan/loguru#90]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I apologize if this has been documented already, however, I can't seem to find it: Is there any way to log `logger.[level]` messages to the file in the `add()` function, but not to terminal? I want to include a debug option in my program, which will show the user exactly what's happening in the code as it's running! <br>
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the help!

**Comment by Delgan** [comment]
Hi @shadowrylander. :)

Yeah, this is totally possible, you just have to first [`.remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default handler. You are seeing logs emitted to the terminal because, internally, Loguru automatically add a `sys.stderr` sink during import. If you wish to get ride of this default behavior, you can simply replace this sink with yours.

```python
logger.remove()

if "--debug" in sys.argv:
    logger.add("logs_{time}.log")
```

**Comment by shadowrylander** [comment]
Thank you very much!
Therefore, if I do something like this, given that I'm using the [`click`](https://click.palletsprojects.com/en/7.x/) interface (not entirely relevant):
```python
if not debug:
    logger.remove()
logger.add(
    f"{d.configDir}/logs/melmetal.{d.logTime}.log",
    rotation="2 months",
)
```

**Comment by shadowrylander** [comment]
Yep! It works! Thank you so much, again!
