### ISSUE TITLE
`mypy` error in the `logger.configure(**config)` example from the documentation

### ISSUE THREAD

**Issue by DeadNews** [Delgan/loguru#920]
Looks like `mypy` issue.
But I'll leave it here just in case.

----

https://github.com/Delgan/loguru/blob/493fb2d5be52da5749c2cad5ed443ef54b57db57/README.rst?plain=1#L368-L376

or

https://github.com/Delgan/loguru/blob/493fb2d5be52da5749c2cad5ed443ef54b57db57/tests/test_configure.py#L69-L78

Causing the following `mypy` error:

```sh
test.py:15:20: error: Argument 1 to "configure" of "Logger" has incompatible type "**dict[str, Collection[object]]"; expected "Sequence[dict[str, Any]]"  [arg-type]
test.py:15:20: error: Argument 1 to "configure" of "Logger" has incompatible type "**dict[str, Collection[object]]"; expected "Sequence[LevelConfig] | None"  [arg-type]
test.py:15:20: error: Argument 1 to "configure" of "Logger" has incompatible type "**dict[str, Collection[object]]"; expected "dict[Any, Any] | None"  [arg-type]
test.py:15:20: error: Argument 1 to "configure" of "Logger" has incompatible type "**dict[str, Collection[object]]"; expected "Callable[[Record], None] | None"  [arg-type]
test.py:15:20: error: Argument 1 to "configure" of "Logger" has incompatible type "**dict[str, Collection[object]]"; expected "Sequence[tuple[str | None, bool]] | None"  [arg-type]
```

This code does not cause any `mypy` errors:

```py
import sys
from typing import Any

from loguru import logger

# For scripts
config: dict[str, Any] = {
    "handlers": [
        {"sink": sys.stdout, "format": "{time} - {message}"},
        {"sink": "file.log", "serialize": True},
    ],
    "extra": {"user": "someone"},
}
logger.configure(**config)
```

or

```py
import sys
from collections.abc import Sequence
from typing import Any, TypedDict

from loguru import logger


class Config(TypedDict):
    """Loguru config."""

    handlers: Sequence[dict[str, Any]]
    extra: dict[Any, Any] | None


# For scripts
config: Config = {
    "handlers": [
        {"sink": sys.stdout, "format": "{time} - {message}"},
        {"sink": "file.log", "serialize": True},
    ],
    "extra": {"user": "someone"},
}
logger.configure(**config)
```

ref: https://github.com/python/mypy/issues/14073, https://github.com/python/mypy/issues/5382

**Comment by Delgan** [comment]
Thanks for the report and the Mypy references.

From what I understand there's not much we can do on the Loguru side unfortunately.

We could add a `ConfigDict` type publicly available. However, that doesn't solve the underlying problem. By default, an error will still be raised if the user does not explicitly add type-annotation to the `config` dictionary. Most importantly, this would only applies to `configure()`. If the user decides to use `dict` unpacking to call let's say `logger.add()`, they will face the same issue.
This implies that each method would need to define an associated `TypedDict` in case the user wanted to use `dict` unpacking, which becomes very cumbersome and not desirable.

We could also add a `@overload` to `logger.configure()` type hints but that means that some invalid configurations will no longer be detected.

It looks like Mypy should extract `Literal` from these `dict` when possible, and map them to the method signature (which is not trivial as Mypy can't guess the `dict` is immutable and not generic). At least, the `config` type should be infered as `dict[str, Any]` instead of current `dict[str, Collection[object]]`. Pyright seems to handle that correctly.
