### ISSUE TITLE
How do I bind in place so I don't have to pass by reference with a mutable?

### ISSUE THREAD

**Issue by narkeeso** [Delgan/loguru#921]
```python
from loguru import logger

def bar(log_ref: List):
  log_ref[0] = log_ref[0].bind(b="b")

def foo():
  log_ref = [logger.bind(name="foo")]
  log_ref[0] = log_ref[0].bind(a="a")
  
  try:
    bar(log_ref)
  except Exception as e:
    # When finally logged, log_ref[0] has all bound variables (a and b)
    log_ref[0].error(e)
```

This works... but it's ugly. I understand there is `logger.contextualize()` but that only works within a `with` scope and doesn't seem like the right tool to accomplish the above. This is a really powerful method to breadcrumb information into a logging instance. Is there an alternative way to do this that I'm missing from the docs?

I was going to try to extend loguru.Logger and create something like a bound logger/context logger but it seems that class is not exported to prevent confusion of usage? Thoughts on having a BoundLogger/ContextLogger? Here's an example:

```python
# create a context logger with some initial context
logger = loguru.ContextLogger(a="a", b="b")
c = foo()
logger.context(c=c)
d = bar()
logger.context(d=d)
logger.info("baz") # outputs with all the context
```

**Comment by Delgan** [comment]
Hi.

Do you have an example of use case that would help me understand the benefit of this feature?


In any case, I would suggest the following workaround:

```python
import sys

from loguru import logger

logger_extra = {}

def contextualize_logger(**kwargs):
    logger_extra.update(kwargs)

logger.configure(patcher=lambda record: record["extra"].update(logger_extra))

contextualize_logger(a="a", b="b")
contextualize_logger(c="c")
contextualize_logger(d="d")

logger.remove()
logger.add(sys.stderr, format="{extra} {message}")
logger.info("baz")  # => "{'a': 'a', 'b': 'b', 'c': 'c', 'd': 'd'} baz"
```

**Comment by narkeeso** [comment]
Thanks for the workaround! That looks like it could be rewritten as a class to return a new contextual logger. I'm going to give that a go!

So this may or may not be best practice, but if you imagine an API that has a handler function and another function that contains the business logic. Inside the business logic there can be a lot of context that would be useful for debugging when an exception is thrown. In the example I gave above `foo()` is the handler and `bar()` is the business logic. I'll rewrite it here for with a little more clarity.

```python
from loguru import logger


def create_user_service(log_ref: List, name: str):
  log_ref[0] = log_ref[0].bind(b="b")
  # create a new entity in the database and return create_id
  created_id = db.insert().values()
  log_ref[0] = log_ref[0].bind(id=created_id)
  # imagine the following query throws an exception, without binding in place we lose all logging context thus far
  db.query().where(id = created_id)
  

def create_user_handler(request):
  log_ref = [logger.bind(name=request.name)]
  
  try:
    create_user_service(log_ref, name)
  except Exception as e:
    log_ref[0].error(e)
```

**Comment by narkeeso** [comment]
I just tried it with the workaround but I think the problem with configure is that it globally updates the extra record across all loggers and the intent is to have a scoped context. Correct me if I'm wrong.

**Comment by Delgan** [comment]
Thank you for the concrete use case example. It's clearer now, and I agree that using `logger.configure()` wouldn't be appropriate. I feel that instead of trying to make the `logger` mutable, you could just as well pass a contextual `dict()` as an argument to your function. What do you think?

```python
def create_user_service(name: str, context: dict):
  # We can also imaging using "logger.patch()" if needed.
  context.update(b="b")
  created_id = db.insert().values() 
  context.update(id=created_id)
  db.query().where(id = created_id)
  
def create_user_handler(request):
  context = {}
  try:
    create_user_service(name, context)
  except Exception as e:
    logger.bind(**context).error(e)
```

However, it doesn't seem to be a very common pattern. It's an interesting problem, and I don't have a truly elegant solution to propose. However, I'm not convinced that the `logger` should be passed as an argument and used as a means for providing contextual information to the parent. I prefer to let Loguru follows a classical top-down approach for contextualization.

In your case, I think adding a `try` / `except` around `db.query().where()` is acceptable if you know that this call can fail, then possibly throw a custom exception with the interesting context. Alternatively, the function could be divided into multiple stages so that the `created_id` value is retrieved by the parent in the first place and then passed to a second function of the business logic. In can of error, the handler can display the known contextual information.

All in all, it's not just an issue related to Loguru. The broader management of exceptions and their context in Python can be discussed. Therefore, using an alternative exception formatter that displays the stack trace might be beneficial for you (eg. [`stackprinter`](https://github.com/cknd/stackprinter)).

**Comment by narkeeso** [comment]
Yeah, I've been thinking about it more and I think you're right. Thanks for the detailed response, suggestions and hearing me out. I was considering an exception handler that could have added context but I think there's some benefits of having the logger have context regardless of whether or not an exception was thrown. For now passing the logger stored in a mutable is working but I'll likely refactor it to work more the context example you gave. I'll close this out!
