### ISSUE TITLE
Formatter to display remaining extra in message?

### ISSUE THREAD

**Issue by artemisart** [Delgan/loguru#941]
Hello, I was trying to automatically display extras in log messages (to still see them for sinks with serialize=False) without duplicating args already in the message, and I tried with a formatter (format callable) or patcher but in both case I get the record with the message already formatted so I cannot know which extra are already in the message, is there any way to do it?
Example of output I would like:
```
logger.info("this is a test {a}", a=1, b=2)
# this is a test 1 {'b': 2}
```
What I can get currently, adding e.g. {extra} to the message format: `this is a test 1 {'a': 1, 'b': 2}`

**Comment by Delgan** [comment]
Hello.

This is not possible as of today. However, I plan to changes a few things regarding message formatting, and to disable usage of keyword arguments (while preserving positional only). I recommend that you start using this pattern, as it's certainly what we'll be implemented in a future release:

```python
logger.info("This is a test {}", 1, b=2)
```

**Comment by Delgan** [comment]
I notably explain my reasoning here: https://github.com/Delgan/loguru/issues/897#issuecomment-1605347697

In Loguru, keyword arguments are used for both message formatting and structured logging. It hasn't always been the case. Initially, it was only used for message formatting. However, there was a strong demand for structured logging support through keyword arguments. So, I extended its functionality to also automatically populate the `extra` dictionary. In retrospect, this was a mistake as it caused recurring issues to users, especially when combining it with f-strings. For example:

```python
some_dict = {"foo": "bar"}
logger.info(f"There is a dict {some_dict}", structured_argument=123)
# => This raises a "KeyError" argument because braces of "some_dict" confuses the formatter.
```

The two usages are not compatible in all situations, and I would like to address this. I have chosen to (in the future) remove the use of keyword arguments for formatting since it has become quite redundant with f-strings. Additionally, I realized that structured logging is a much more convenient technique. Instead of having to craft a sentence to include the desired values, one can write a generic message and place the values as arguments. For example:

```python
# Bad.
logger.info("Email sent to {} from address {} (bytes={}, date={})", dest=..., src=..., bytes=..., date=...)

# Good.
logger.info("Email sent", dest=..., src=..., bytes=..., date=...)
# => Message will later be automatically formatted as "Email sent (dest=..., src=..., bytes=..., date=...)".

```

For these reasons, I believe it's best to do away with keyword arguments, even though I'm not entirely satisfied (as it's surprising to have positional-only formatting), it's the only solution that seems viable to me.

**Comment by artemisart** [comment]
Thanks, I get it. So to have something like your last line the closest we can do today is add " {extra}" to LOGURU_FORMAT correct?

**Comment by Delgan** [comment]
> Thanks, I get it. So to have something like your last line the closest we can do today is add " {extra}" to LOGURU_FORMAT correct?

Yes.
