### ISSUE TITLE
Make it easy to set the level of the default logger

### ISSUE THREAD

**Issue by johann-petrak** [Delgan/loguru#98]
Given that loguru is meant to make logging very easy, changing the log-level of the default logger, which is something probably everyone wants to do at some point, is rather complex and involved. 
This very basic functionality should be made more easy, so even if newly added loggers are immutable why not at least add something like `logger.set_default_level(newlevel)`? This would help a vast majority of very basic uses.

**Comment by Delgan** [comment]
Hi @johann-petrak.

I'm not sure if you mean changing the default level once the `logger` has been used, or during initialization of the program. So, for disambiguation, note that it is possible to configure the default level by setting the `LOGURU_LEVEL` environment variable. The logger will automatically use this value to setup the default handler without any further configuration needed.

About adding a new `.set_default_level()` method, I'm honestly not a big fan of that. The default handler is not mean to be special in any way, it's just a regular handler which happens to have been added automatically. It must not be treated differently from others.

Adding such method raises several questions: what if `LOGURU_AUTOINIT` is set to `False`? What if the default handler has been removed? Why not also add a way to set the default format? This also leads to the question of why this method should be voluntarily limited to the default handler rather allowing all handlers to be modified.

What are some examples of the basic uses cases you are thinking about? For now, I would do this:

```python
logger.remove()
logger.add(sys.stderr, level=newlevel)
```

I think this is very easy and not much boilerplate that would justify adding a new method to the API.

**Comment by Delgan** [comment]
@johann-petrak Does my explanation make sense to you? Do you any example where the `remove()` / `add()` pattern would be insufficient?

**Comment by johann-petrak** [comment]
I think you are right, I can see the problems adding this could cause.

**Comment by shelllee** [comment]
> Adding such method raises several questions: what if `LOGURU_AUTOINIT` is set to `False`? What if the default handler has been removed? Why not also add a way to set the default format? This also leads to the question of why this method should be voluntarily limited to the default handler rather allowing all handlers to be modified.

I think there are too many designs!

**Comment by williamfzc** [comment]
I used default logger in my project, and released it on pypi. But I still have some questions:

- If I am going to set log level to `INFO` in my project, I have to remove the default logger and add a new one.
- It works fine. But if some other developers used my project as a dep, and they are going to set a custom logger, they also have to remove the existed one, which have been defined in my project, and add their new one. Which means, my pre-conf logger has been dropped.

Any suggestions ?

**Comment by Delgan** [comment]
Hi @williamfzc. It is important to differentiate whether you publish your project as a **library** or as an **application**.

In the first case, you should not `.add()` any handler from within your library. Especially to prevent confusing your users. This is similar to what is suggested [in the standard `logging` library](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library).

You can use the `logger` inside your library, but you should restrict the use of `.add()` to the applications using your library. If you want to share a pre-configured logger, you probably should add a function to your API so user can decide between using yours or their own. Alternatively, you can configure the `logger` in a `if __name__ == "__main__"` branch or in a `__main__.py` file so that it's not executed while someone import your library.

Also, note that it's best to call [`disable("your_lib")`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.disable) when initializing your library so that by default your logs don't get mixed up with user logs.

If I haven't answered your question accurately enough, let me know. ;)

**Comment by williamfzc** [comment]
@Delgan Thanks for your suggestions very much :)
