### ISSUE TITLE
How to escape `\` before tag

### ISSUE THREAD

**Issue by yanyongyu** [Delgan/loguru#988]
In my server application, i'm using loguru logger to log messages from client. But in some case, the log failed with the error: https://github.com/nonebot/adapter-onebot/issues/74 `ValueError: Closing tag "</le>" has no corresponding opening tag`

Here is the example of the case:

```python
message = r"\\<le>test</le>"
logger.opt(colors=True).info(message)
```

It seems double `\` cannot escape the escape before tag according to the ansi parser. how can i escape this message currectly?

https://github.com/Delgan/loguru/blob/e1f48c91cf2646b6429020f784881cd200663114/loguru/_colorizer.py#L223-L232

**Comment by AlTosterino** [comment]
Hey,

Hmm, are you able to add space after `\\`? I just checked and adding a space is fixing the issue you are facing. Note that this is just  workaround.

```python
from loguru import logger

if __name__ == "__main__":
    logger.remove()
    logger.add(sys.stdout)
    logger.opt(colors=True).info("\\ <le>test</le>")
    # 2023-09-19 17:40:56.966 | INFO     | __main__:<module>:8 - \ test
```

**Comment by Delgan** [comment]
You need to escape both opening and closing tags.

```python
message = "\<le>test\</le>"
logger.opt(colors=True).info(message)
# Output: "<le>test</le>"
```

Note that you shouldn't generally combine `colors=True` with messages that may contain arbitrary data. It's better to pass them as arguments, to avoid false positives of this type.

```python
logger.opt(colors=True).info("<green>Parsed data:</green> <blue>{}</blue>", data)
```

**Comment by Delgan** [comment]
In this case, you need to escape the two tags in addition to the `\` already present. 

```python
message = r"\\<le>test\</le>"
logger.opt(colors=True).info(message)
```

Loguru uses tags such as `<le>` to colorize the message. To avoid the tag being interpreted as a colorization command, it must be preceded by `\`. In such case, `"\<le>"` is converted to `"<le>"`. Because you want to preserve the `\` from your original message, you need two `\`: the one to escape colors, and the one from your original message.

**Comment by yanyongyu** [comment]
May be i should provide detailed info about the caee.:joy:

We have a tokenizer to parse the input string, and highlight special tokens. Here is an example with detailed steps:

1. Input: `This is a message with [special_token]`
2. tokenize result: `This a message with `, `[special_token]`
3. output: `This a message with <le>[special_token]</le>`

Once there is a `\` before special token, the highlight is failed to display:

1. Input: `This is a message with \[special_token]`
2. tokenize result: `This a message with \`, `[special_token]`
3. output: `This a message with \<le>[special_token]</le>`

The output is not a valid loguru markup message.

**Comment by Delgan** [comment]
Thanks for the explanation. I'm sorry, this is indeed a bug. It's not possible to display a literal "\" immediately before a text to be colored. Thanks for the report.

The workaround provided by @AlTosterino seems to be the simplest solution for now.

**Comment by Delgan** [comment]
Fixed on `master` branch. It is now possible to use double backslash to display a literal `\` without escaping the color markup.

For example, the following code will now print `Message: \test` with `test` being blue colored:

```python
from loguru import logger

logger.opt(colors=True).info(r"Message: \\<le>test</le>")
```

**Comment by dzenanz** [comment]
With `loguru==0.7.3` I am running into a similar problem. I have this line:
`logger.opt(colors=True).info("Processing <yellow>{}</yellow>".format(current_dir))`
If `current_dir` ends with a backslash (common on Windows, e.g. `M:\Dev\`), there is an error:
```log
Traceback (most recent call last):
  File "M:\Dev\main.py", line 52, in <module>
    logger.opt(colors=True).info("Processing <yellow>{}</yellow>".format(current_dir))
  File "M:\Dev\venv\lib\site-packages\loguru\_logger.py", line 2078, in info
    __self._log("INFO", False, __self._options, __message, args, kwargs)
  File "M:\Dev\venv\lib\site-packages\loguru\_logger.py", line 2051, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
  File "M:\Dev\venv\lib\site-packages\loguru\_colorizer.py", line 379, in prepare_simple_message
    tokens = parser.done()
  File "M:\Dev\venv\lib\site-packages\loguru\_colorizer.py", line 277, in done
    raise ValueError('Opening tag "<%s>" has no corresponding closing tag' % faulty_tag)
ValueError: Opening tag "<yellow>" has no corresponding closing tag
```

**Comment by Delgan** [comment]
@dzenanz Since you're manually calling `str.format()`, the `logger` receives an already formatted message:

```python
"Processing <yellow>M:\\dev\\</yellow>"
```

Then, because `colors=True` for this message, Loguru will try to parse it according to the color markup rules. In particular, because of the `"\"` inadvertently added,  it'll escape `"</yellow>"` (closing tag) resulting un an unpaired `"<yellow>"` (opening tag).

Loguru cannot guess whether the escaping was intentional or not. For this reason, it is wise for every logged message to be a literal string, i.e. do not apply any pre-formatting with uncontrolled dynamic fields (such as `current_dir` in your case). This applies to f-strings, as well, which can cause such errors.

Instead, the formatting should be deferred using `*args` or `**kwargs` so that Loguru can first parse the colors, then format the message:

```python
logger.opt(colors=True).info("Processing <yellow>{}</yellow>", current_dir)
```

**Comment by dzenanz** [comment]
Thank you for the explanation. I just started using loguru, and I apparently did not read the documentation carefully enough. Also, autosuggest might deserve part of the blame.
